import Link from "next/link";
import { AccessError } from "@/server/authorization/engine";
import { NiceJobsUnavailable } from "@/server/nicejobs/input";
import { applicationService as service } from "@/server/nicejobs/applications";
import { applicationStates } from "@/server/nicejobs/application-configuration";
import { ApplicationCommand, CandidateApplicationForm } from "./application-form";
import { workspaceReturnKeys } from "@/lib/workspace-navigation";
import { WorkspaceReturnFields } from "@/components/ui/workspace-return-fields";
import { ZodError } from "zod";
import { RecruitmentWorkspace } from "./recruitment-workspace";
import { randomUUID } from "node:crypto";
import { OnboardingCommand } from "./onboarding-form";
import { onboardingService } from "@/server/nicejobs/onboarding";

export async function ApplicationWorkspace({ userId, realm, base, query }: { userId: string; realm: string; base: string; query: Record<string, string | string[] | undefined> }) {
  const value = (key: string) => typeof query[key] === "string" ? query[key] as string : undefined;
  const view = value("view") ?? "my-applications", own = view !== "applications";
  const href = (changes: Record<string, string | undefined>) => {
    const p = new URLSearchParams();
    for (const key of ["view", "status", "companyId", "divisionId", "versionId", "search", "interviewFrom", "interviewTo", ...workspaceReturnKeys]) if (value(key)) p.set(key, value(key)!);
    for (const [key, v] of Object.entries(changes)) if (v) p.set(key, v); else p.delete(key);
    return `${base}?${p}`;
  };
  try {
    const navigation = await service.navigation(userId);
    const training = await onboardingService.navigation(userId);
    const filters = { ...(value("companyId") ? { companyId: value("companyId") } : {}), ...(value("divisionId") ? { divisionId: value("divisionId") } : {}), ...(value("versionId") ? { versionId: value("versionId") } : {}), ...(value("status") ? { status: value("status") } : {}), ...(value("interviewFrom") ? { interviewFrom: value("interviewFrom") } : {}), ...(value("interviewTo") ? { interviewTo: value("interviewTo") } : {}), search: value("search") ?? "", ...(value("cursor") ? { after: value("cursor") } : {}) };
    const detail = value("reference") ? await service.detail(userId, value("reference")!, own, value("historyBefore") ? Number(value("historyBefore")) : undefined) : null;
    const opportunities = view === "opportunities" && !detail ? await service.opportunities(userId, filters) : null;
    const applications = !opportunities && !detail ? await service.list(userId, own, filters) : null;
    const options = !own && !detail ? await service.options(userId, false, value("versionId")) : null;
    return <div className="nj-workspace"><header><p>AIRA Career Hub / Nice Jobs</p><h1>{detail ? detail.applicationId ?? "Draft application" : view === "opportunities" ? "Available jobs" : own ? "My Applications" : "Applications"}</h1></header>
      <nav aria-label="Nice Jobs applications">{[["opportunities", "Available jobs", navigation.own], ["my-applications", "My Applications", navigation.own], ["applications", "Applications", navigation.manage], ["templates", "Job Templates", navigation.templates]].filter(([, , allowed]) => allowed).map(([key, label]) => <Link key={String(key)} href={href({ view: String(key), reference: undefined, cursor: undefined, versionId: undefined, status: undefined, divisionId: undefined, search: undefined })} aria-current={view === key ? "page" : undefined}>{label}</Link>)}{[["my-onboarding", "My Onboarding", training.own], ["onboarding", "Onboarding", training.manage], ["my-reviews", "My Reviews", training.reviews]].filter(([, , allowed]) => allowed).map(([key, label]) => <Link key={String(key)} href={href({ view: String(key), reference: undefined, status: undefined, cursor: undefined })}>{label}</Link>)}</nav>
      {detail ? <><Link href={href({ reference: undefined, cursor: undefined })}>Back to applications</Link><h2>{detail.title}</h2><dl className="nj-detail"><dt>Candidate</dt><dd>{detail.candidateName}</dd><dt>Company</dt><dd>{detail.company}</dd><dt>Division</dt><dd>{detail.division}</dd><dt>Submitted</dt><dd>{detail.submittedAt?.toISOString().slice(0, 10) ?? "Not submitted"} {detail.submittedAt && "UTC"}</dd><dt>Status</dt><dd>{detail.status.replaceAll("_", " ")}</dd><dt>Eligibility</dt><dd>{detail.eligibilityStatus.replaceAll("_", " ")}</dd><dt>Screening</dt><dd>{detail.screeningStatus.replaceAll("_", " ")}</dd><dt>Next step</dt><dd>{detail.nextStep}</dd>{detail.candidateMessage && <><dt>Message</dt><dd>{detail.candidateMessage}</dd></>}</dl>
        {detail.status === "OFFER_ACCEPTED" && own && training.own && <section><h2>Orientation &amp; OJT</h2><OnboardingCommand realm={realm} own command={{ applicationReference: detail.reference, revision: detail.revision, operation: "ENROLL", idempotencyKey: randomUUID() }} label="Enroll in onboarding" /><Link href={href({ view: "my-onboarding", reference: detail.reference })}>Open My Onboarding</Link></section>}
        <RecruitmentWorkspace userId={userId} reference={detail.reference} own={own} realm={realm} href={href} interviewsAfter={value("interviewsAfter")} offersAfter={value("offersAfter")} interviewerSearch={value("interviewerSearch")} interviewersAfter={value("interviewersAfter")} />
        {own && detail.canEdit && <CandidateApplicationForm key={detail.revision} realm={realm} reference={detail.reference} revision={detail.revision} form={detail.form} initial={detail.answers} />}
        {own && detail.status === "DRAFT" && !detail.canEdit && <p>This job version is no longer receiving applications. Your draft is preserved.</p>}
        {own && detail.canWithdraw && <ApplicationCommand realm={realm} operation="WITHDRAW" reference={detail.reference} revision={detail.revision} label="Withdraw application" confirm />}
        {detail.management && <><h2>Management review</h2><p>{detail.management.candidate} / Job version {detail.management.version}</p><h3>Application answers</h3><dl className="nj-detail">{detail.form.fields.map(f => <div key={f.key}><dt>{f.label}</dt><dd>{String(detail.answers[f.key] ?? "Not provided")}</dd></div>)}</dl>
          <div className="nj-actions">{[
            ["ELIGIBILITY", "Evaluate eligibility", "evaluate", ["SUBMITTED", "ELIGIBILITY_REVIEW"].includes(detail.status)],
            ["SCREENING", "Evaluate screening", "evaluate", detail.status === "SCREENING" && ["PENDING", "NOT_CONFIGURED"].includes(detail.screeningStatus)],
            ["ELIGIBILITY_REVIEW", "Resolve eligibility review", "evaluate", detail.status === "ELIGIBILITY_REVIEW" && detail.eligibilityStatus === "NEEDS_REVIEW"],
            ["SCREENING_REVIEW", "Resolve screening review", "evaluate", detail.status === "SCREENING" && detail.screeningStatus === "NEEDS_REVIEW"],
            ["SHORTLIST", "Shortlist", "shortlist", detail.status === "SCREENING" && detail.eligibilityStatus === "ELIGIBLE" && detail.screeningStatus === "PASSED"],
            ["REJECT", "Reject", "reject", ["SUBMITTED", "ELIGIBILITY_REVIEW", "SCREENING"].includes(detail.status)],
            ["CLOSE", "Close record", "close", ["REJECTED", "WITHDRAWN"].includes(detail.status)],
          ].filter(([, , key, available]) => available && detail.management!.permissions[String(key)]).map(([operation, label]) => <details key={String(operation)}><summary>{label}</summary><ApplicationCommand realm={realm} operation={String(operation)} reference={detail.reference} revision={detail.revision} label={String(label)} confirm><label>Management-only reason<textarea name="reason" required maxLength={1000} /></label>{["ELIGIBILITY_REVIEW", "SCREENING_REVIEW"].includes(String(operation)) && <label>Verified result<select name="reviewResult" required><option value="">Select</option>{(operation === "ELIGIBILITY_REVIEW" ? ["ELIGIBLE", "INELIGIBLE"] : ["PASSED", "FAILED"]).map(result => <option key={result}>{result}</option>)}</select></label>}{operation === "REJECT" && <>{!!detail.form.rejectionCategories.length && <label>Reason category<select name="category" required><option value="">Select</option>{detail.form.rejectionCategories.map(c => <option key={c}>{c}</option>)}</select></label>}<label>Candidate-visible message<textarea name="candidateMessage" maxLength={1000} /></label></>}</ApplicationCommand></details>)}</div>
          <h3>Decision history and evidence</h3><ol className="nj-history">{detail.management.history.map(h => <li key={h.id}><strong>{h.action.replaceAll("_", " ")}</strong><p>{h.actor} / {h.previousState} to {h.nextState} / {h.createdAt.toISOString()}</p>{h.internalReason && <p>Management-only: {h.internalReason}</p>}{h.candidateMessage && <p>Candidate-visible: {h.candidateMessage}</p>}{h.evidence && <details><summary>Evaluation evidence</summary><pre>{JSON.stringify(JSON.parse(h.evidence), null, 2)}</pre></details>}<small>Audit event: {h.eventId}</small></li>)}</ol>{detail.management.nextRevision !== null && <Link href={href({ reference: detail.reference, historyBefore: String(detail.management.nextRevision) })}>Older history</Link>}
        </>}
      </> : <><form method="get" action={base} className="nj-filters"><WorkspaceReturnFields query={query} /><input type="hidden" name="view" value={view} />{!options && value("companyId") && <input type="hidden" name="companyId" value={value("companyId")} />}<label>{own ? "Search" : "Application ID or candidate"}<input name="search" maxLength={120} defaultValue={value("search") ?? ""} /></label>{!opportunities && <label>Status<select name="status" defaultValue={value("status") ?? ""}><option value="">All statuses</option>{applicationStates.map(s => <option key={s} value={s}>{s.replaceAll("_", " ")}</option>)}</select></label>}{options && <><label>Company<select name="companyId" defaultValue={value("companyId") ?? options.company.id}><option value={options.company.id}>{options.company.name}</option></select></label><label>Division<select name="divisionId" defaultValue={value("divisionId") ?? ""}><option value="">All divisions</option>{options.divisions.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Job version<select name="versionId" defaultValue={value("versionId") ?? ""}><option value="">All job versions</option>{options.versions.map(v => <option key={v.id} value={v.id}>{v.title} / v{v.number}</option>)}</select></label></>}{!own && <><label>Interview from (UTC)<input name="interviewFrom" type="date" defaultValue={value("interviewFrom")} /></label><label>Interview to (UTC)<input name="interviewTo" type="date" defaultValue={value("interviewTo")} /></label></>}<button className="button">Filter</button><Link href={href({ interviewFrom: undefined, interviewTo: undefined, status: undefined, search: undefined, divisionId: undefined, versionId: undefined, cursor: undefined })}>Clear filters</Link></form>
        {opportunities && <div className="nj-application-list">{!opportunities.records.length && <p>No published jobs are receiving applications.</p>}{opportunities.records.map(job => <article key={job.id}><h2>{job.title}</h2><p>{job.company}</p><p>{job.description}</p><ApplicationCommand realm={realm} operation="CREATE" versionId={job.id} label="Start application" base={href({ view: "my-applications", versionId: undefined, status: undefined, search: undefined, divisionId: undefined })}><label>Business division<select name="divisionId" required>{job.areas.map(a => <option key={a.divisionId} value={a.divisionId}>{a.division.name}</option>)}</select></label></ApplicationCommand></article>)}</div>}
        {applications && <div className="nj-application-list">{!applications.records.length && <p>{own ? "No applications match these filters." : "No applications in your authorized scope match these filters."}</p>}{applications.records.map(a => <article key={a.reference}><h2><Link href={href({ reference: a.reference, cursor: undefined })}>{a.applicationId ?? "Draft application"}</Link></h2><h3>{a.title}</h3>{"candidate" in a && <p>{String(a.candidate)}</p>}<p>{a.company} / {a.division}</p><p>{a.submittedAt?.toISOString().slice(0, 10) ?? "Not submitted"}</p><strong>{a.status.replaceAll("_", " ")}</strong><p>{a.nextStep}</p></article>)}</div>}
        {(opportunities?.nextCursor || applications?.nextCursor) && <Link className="button button-secondary" href={href({ cursor: opportunities?.nextCursor ?? applications?.nextCursor ?? undefined })}>Next page</Link>}
      </>}
    </div>;
  } catch (e) {
    if (e instanceof AccessError) return <section className="nj-workspace"><h1>Nice Jobs</h1><p role="alert">This view is not available to your account.</p><Link href={`${base}?view=my-applications`}>My Applications</Link> <Link href={`${base}?view=applications`}>Management applications</Link></section>;
    if (e instanceof NiceJobsUnavailable) return <section className="nj-workspace"><h1>Nice Jobs</h1><p role="alert">Nice Jobs is currently unavailable.</p></section>;
    if (e instanceof ZodError) return <section className="nj-workspace"><h1>Applications</h1><p role="alert">Invalid filters or application reference.</p><Link href={`${base}?view=${view}`}>Reset view</Link></section>;
    throw e;
  }
}
