"use client";
import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { ApplicationCommand } from "./application-form";
import { applicationConfiguration, eligibilityConfiguration, screeningConfiguration, fieldTypes, type FormConfiguration } from "@/server/nicejobs/application-configuration";
type Rule = { field: string; operator: "EQ" | "INCLUDES" | "GTE" | "LTE"; value: string | number | boolean; review: boolean; weight: number; required: boolean };
export function ConfigurationEditor({ realm, versionId, revision, initial }: { realm: string; versionId: string; revision: number; initial: Record<string, unknown> | null }) {
  const form = applicationConfiguration.safeParse(initial?.application), eligibility = eligibilityConfiguration.safeParse(initial?.eligibility), screening = screeningConfiguration.safeParse(initial?.screening);
  const [fields, setFields] = useState<FormConfiguration["fields"]>(form.success ? form.data.fields : []);
  const [duplicatePolicy, setDuplicatePolicy] = useState(form.success ? form.data.duplicatePolicy : "ACTIVE_PER_VERSION");
  const [rules, setRules] = useState<Rule[]>(eligibility.success ? eligibility.data.rules.map(r => ({ ...r, weight: 1, required: false })) : []);
  const [questions, setQuestions] = useState<Rule[]>(screening.success ? screening.data.questions : []);
  const [passMark, setPassMark] = useState(screening.success ? screening.data.passMark : 70);
  const [categories, setCategories] = useState(form.success ? form.data.rejectionCategories.join("\n") : "");
  const config = { ...initial, schemaVersion: 1, application: { fields, duplicatePolicy, withdrawalStates: form.success ? form.data.withdrawalStates : ["DRAFT", "SUBMITTED", "ELIGIBILITY_REVIEW", "SCREENING"], rejectionCategories: categories.split("\n").map(v => v.trim()).filter(Boolean) }, eligibility: rules.length ? { rules: rules.map(({ field, operator, value, review }) => ({ field, operator, value, review })) } : null, screening: questions.length ? { questions, passMark } : null };
  const newRule = (): Rule => ({ field: fields[0]?.key ?? "", operator: "EQ", value: "", review: false, weight: 1, required: false });
  const ruleEditor = (rows: Rule[], set: (rows: Rule[]) => void, scored: boolean) => <>{rows.map((r, i) => {
    const change = (patch: Partial<Rule>) => set(rows.map((row, n) => n === i ? { ...row, ...patch } : row));
    return <fieldset key={i}><legend>{scored ? "Screening question" : "Eligibility rule"} {i + 1}</legend><label>Answer field<select value={r.field} onChange={e => change({ field: e.target.value })}><option value="">Select</option>{fields.map(f => <option key={f.key} value={f.key}>{f.label || f.key}</option>)}</select></label><label>Comparison<select value={r.operator} onChange={e => change({ operator: e.target.value as Rule["operator"] })}><option value="EQ">Equals</option><option value="INCLUDES">Contains selection</option><option value="GTE">At least</option><option value="LTE">At most</option></select></label><label>Expected answer<input value={String(r.value)} onChange={e => { const type = fields.find(f => f.key === r.field)?.type; change({ value: type === "NUMBER" ? Number(e.target.value) : type === "BOOLEAN" ? e.target.value === "true" : e.target.value }); }} /></label><label className="nj-check"><input type="checkbox" checked={r.review} onChange={e => change({ review: e.target.checked })} />Human review required</label>{scored && <><label>Weight<input type="number" min={1} max={100} value={r.weight} onChange={e => change({ weight: Number(e.target.value) })} /></label><label className="nj-check"><input type="checkbox" checked={r.required} onChange={e => change({ required: e.target.checked })} />Must match to pass</label></>}<button className="button button-secondary" type="button" aria-label={`Remove ${scored ? "question" : "rule"} ${i + 1}`} title="Remove" onClick={() => set(rows.filter((_, n) => n !== i))}><Trash2 size={16} /></button></fieldset>;
  })}<button type="button" className="button button-secondary" disabled={rows.length >= 40 || !fields.length} onClick={() => set([...rows, newRule()])}><Plus size={16} />{scored ? "Add screening question" : "Add eligibility rule"}</button></>;
  return <ApplicationCommand realm={realm} operation="CONFIGURE" versionId={versionId} revision={revision} label="Save application configuration"><input type="hidden" name="configuration" value={JSON.stringify(config)} /><h3>Application fields</h3>{fields.map((f, i) => {
    const change = (patch: Partial<typeof f>) => setFields(fields.map((field, n) => n === i ? { ...field, ...patch } : field));
    return <fieldset key={i}><legend>Field {i + 1}</legend><label>Field key<input value={f.key} maxLength={50} onChange={e => change({ key: e.target.value })} /></label><label>Label<input value={f.label} maxLength={120} onChange={e => change({ label: e.target.value })} /></label><label>Answer type<select value={f.type} onChange={e => change({ type: e.target.value as typeof f.type })}>{fieldTypes.map(t => <option key={t}>{t}</option>)}</select></label>{["SELECT", "MULTI_SELECT"].includes(f.type) && <label>Options<textarea value={f.options?.join("\n") ?? ""} onChange={e => change({ options: e.target.value.split("\n").filter(Boolean) })} /></label>}<label className="nj-check"><input type="checkbox" checked={f.required} onChange={e => change({ required: e.target.checked })} />Required</label><label>Show when<select value={f.when?.field ?? ""} onChange={e => change({ when: e.target.value ? { field: e.target.value, operator: "EQ", value: "" } : undefined })}><option value="">Always</option>{fields.filter(other => other.key !== f.key).map(other => <option key={other.key} value={other.key}>{other.label || other.key}</option>)}</select></label>{f.when && <label>Equals<input value={String(f.when.value)} onChange={e => { const type = fields.find(other => other.key === f.when!.field)?.type; change({ when: { ...f.when!, value: type === "NUMBER" ? Number(e.target.value) : type === "BOOLEAN" ? e.target.value === "true" : e.target.value } }); }} /></label>}<button type="button" className="button button-secondary" aria-label={`Remove field ${i + 1}`} title="Remove field" onClick={() => setFields(fields.filter((_, n) => n !== i))}><Trash2 size={16} /></button></fieldset>;
  })}<button type="button" className="button button-secondary" disabled={fields.length >= 40} onClick={() => setFields([...fields, { key: `field_${fields.length + 1}`, label: "", type: "TEXT", required: false }])}><Plus size={16} />Add field</button><h3>Eligibility</h3>{ruleEditor(rules, setRules, false)}<h3>Screening</h3>{ruleEditor(questions, setQuestions, true)}{questions.length > 0 && <label>Pass mark (%)<input type="number" min={0} max={100} value={passMark} onChange={e => setPassMark(Number(e.target.value))} /></label>}<label>Duplicate policy<select value={duplicatePolicy} onChange={e => setDuplicatePolicy(e.target.value as typeof duplicatePolicy)}><option value="ACTIVE_PER_VERSION">One active application per version</option><option value="ONE_PER_VERSION">One application per version</option></select></label><label>Rejection categories<textarea maxLength={2400} value={categories} onChange={e => setCategories(e.target.value)} /></label></ApplicationCommand>;
}
