import { randomUUID } from "node:crypto";
import Link from "next/link";
import { ZodError } from "zod";
import { onboardingService as service } from "@/server/nicejobs/onboarding";
import { onboardingStates } from "@/server/nicejobs/onboarding-input";
import { AccessError } from "@/server/authorization/engine";
import { NiceJobsUnavailable } from "@/server/nicejobs/input";
import { workspaceReturnKeys } from "@/lib/workspace-navigation";
import { WorkspaceReturnFields } from "@/components/ui/workspace-return-fields";
import { OnboardingCommand } from "./onboarding-form";

export async function OnboardingWorkspace({ userId, realm, base, query }: { userId: string; realm: string; base: string; query: Record<string, string | string[] | undefined> }) {
  const value = (k: string) => typeof query[k] === "string" ? query[k] as string : undefined;
  const view = value("view") ?? "my-onboarding", own = view === "my-onboarding";
  const keys = ["view", "companyId", "divisionId", "versionId", "reviewerUserId", "status", "readinessStatus", "search", ...workspaceReturnKeys];
  const href = (changes: Record<string, string | undefined>) => { const p = new URLSearchParams(); for (const k of keys) if (value(k)) p.set(k, value(k)!); for (const [k, v] of Object.entries(changes)) if (v) p.set(k, v); else p.delete(k); return `${base}?${p}`; };
  try {
    const nav = await service.navigation(userId);
    const d = value("reference") ? await service.detail(userId, value("reference")!, own, value("progressAfter")) : null;
    const filters = Object.fromEntries(keys.filter(k => !["view", ...workspaceReturnKeys].includes(k)).filter(k => value(k)).map(k => [k, value(k)]));
    const list = !d ? await service.list(userId, own, { ...filters, ...(value("cursor") ? { after: value("cursor") } : {}) }, view === "my-reviews") : null;
    const options = !d && !own ? await service.options(userId) : null;
    const command = (operation: string, extra = {}) => ({ applicationReference: d!.reference, revision: d!.revision, operation, idempotencyKey: randomUUID(), ...extra });
    return <section className="nj-workspace"><header><p>AIRA Career Hub / Nice Jobs</p><h1>{d ? d.title : own ? "My Onboarding" : view === "my-reviews" ? "My Reviews" : "Onboarding"}</h1></header>
      <nav aria-label="Nice Jobs training">{[["my-onboarding", "My Onboarding", nav.own], ["onboarding", "Onboarding", nav.manage], ["my-reviews", "My Reviews", nav.reviews]].filter(([, , allowed]) => allowed).map(([key, label]) => <Link key={String(key)} href={href({ view: String(key), cursor: undefined, status: undefined, readinessStatus: undefined })} aria-current={view === key ? "page" : undefined}>{label}</Link>)}<Link href={href({ view: own ? "my-applications" : "applications", status: undefined, readinessStatus: undefined, reviewerUserId: undefined })}>Applications</Link></nav>
      {d ? <><Link href={href({ reference: undefined })}>Back to {own ? "My Onboarding" : view === "my-reviews" ? "My Reviews" : "Onboarding"}</Link><p>{d.candidate} / {d.company} / {d.division} / Job version {d.version}</p><strong>{d.status.replaceAll("_", " ")}</strong>{d.status === "READY" && <p>Ready for activation. Not activated.</p>}
        <div className="nj-training-summary">{[["Orientation", d.orientation], ["OJT", d.ojt]].map(([title, progress]) => { const p = progress as typeof d.orientation; return <div key={String(title)}><h2>{String(title)}</h2>{p.configured ? <><p>{p.completed} of {p.required} mandatory requirements completed</p><progress aria-label={`${title} completion`} max={p.required} value={p.completed} /></> : <p>NOT CONFIGURED</p>}</div>; })}</div>
        {own && d.status === "NOT_STARTED" && d.orientation.configured && <OnboardingCommand key={d.revision} realm={realm} own command={command("START_ORIENTATION")} label="Start orientation" />}
        {own && d.status === "ORIENTATION" && !d.orientationCompleted && d.orientation.configured && d.orientation.completed === d.orientation.required && <OnboardingCommand key={d.revision} realm={realm} own command={command("FINISH_ORIENTATION")} label="Finish orientation" />}
        {own && d.status === "ORIENTATION" && d.orientationCompleted && d.ojt.configured && <OnboardingCommand key={d.revision} realm={realm} own command={command("START_OJT")} label="Start OJT" />}
        {!d.reviewerAssigned && <p>Trainer or mentor not assigned.</p>}{!d.readinessReviewerAssigned && <p>Readiness reviewer not assigned.</p>}
        {own && d.nextRequirement && <p><strong>Next: </strong><a href={`#training-${d.nextRequirement.id}`}>{d.nextRequirement.title}</a>{d.nextRequirement.status === "SUBMITTED" && " / Awaiting trainer review"}</p>}
        {d.permissions.assign && !["READY", "CANCELLED"].includes(d.status) && <details><summary>Assign trainer or mentor</summary><OnboardingCommand realm={realm} own={false} command={command("ASSIGN_REVIEWER")} label="Assign reviewer" management assign="OJT" reviewers={d.reviewerChoices} /></details>}
        {d.permissions.manage && !["READY", "CANCELLED"].includes(d.status) && <details><summary>Assign readiness reviewer</summary><OnboardingCommand realm={realm} own={false} command={command("ASSIGN_REVIEWER")} label="Assign readiness reviewer" management assign="READINESS" reviewers={d.readinessChoices} /></details>}
        <h2>Training requirements</h2><div className="nj-application-list">{d.progress.map(p => <article key={p.id} id={`training-${p.id}`}><p>{p.phase.replaceAll("_", " ")} / {p.contentType}</p><h3>{p.title}</h3><strong>{p.status.replaceAll("_", " ")}</strong><p>{p.text}</p>{p.expectedOutcome && <p>Expected outcome: {p.expectedOutcome}</p>}{p.link && <a href={p.link} target="_blank" rel="noreferrer noopener">Open lesson</a>}{p.privateContent && <p>Private content delivery is not configured. Contact your trainer.</p>}{p.dueAt && <p>Due {p.dueAt.toISOString().slice(0, 10)} UTC</p>}<p>Attempts: {p.attempt} of {p.maxAttempts}{p.reviewRequired && " / Human review required"}</p>
          {p.actionable && !p.privateContent && <OnboardingCommand key={`${p.id}:${d.revision}`} realm={realm} own command={command(p.phase === "ORIENTATION" ? "COMPLETE_LESSON" : p.phase === "ASSESSMENT" ? "SUBMIT_ASSESSMENT" : "SUBMIT_ACTIVITY", { progressId: p.id })} label={p.form ? "Submit assessment" : p.evidenceRequired ? "Submit evidence" : "Complete requirement"} form={p.form} evidence={!!p.evidenceRequired} />}
          {p.submissions.map(s => <div key={s.id}><p>Attempt {s.attempt}: {s.result.replaceAll("_", " ")}{s.score !== null && ` / Score ${s.score.toFixed(1)}%`}</p>{s.feedback && <p>{s.feedback}</p>}{"evidence" in s && <details><summary>Submitted evidence</summary><pre>{JSON.stringify(s.evidence, null, 2)}</pre>{s.privateNotes && <p>Private notes: {String(s.privateNotes)}</p>}</details>}{d.permissions.review && p.status === "SUBMITTED" && s.attempt === p.attempt && <OnboardingCommand realm={realm} own={false} command={command("REVIEW", { submissionId: s.id })} label="Save review" management review assessment={p.phase === "ASSESSMENT"} />}</div>)}</article>)}</div>
        {d.nextCursor && <Link href={href({ reference: d.reference, progressAfter: d.nextCursor })}>More training requirements</Link>}
        <h2>Readiness</h2><p>{d.readinessCriteria ?? "NOT CONFIGURED"}</p><dl className="nj-detail">{Object.entries(d.checks).map(([key, status]) => <div key={key}><dt>{key}</dt><dd>{status.replaceAll("_", " ")}</dd></div>)}</dl>
        {own && d.status === "OJT" && <OnboardingCommand realm={realm} own command={command("REQUEST_READINESS")} label="Request readiness review" />}
        {d.permissions.decide && d.status === "READINESS_REVIEW" && <OnboardingCommand realm={realm} own={false} command={command("DECIDE_READINESS")} label="Save readiness decision" management readiness />}
        {d.reviews.map(r => <p key={r.id}>{r.outcome.replaceAll("_", " ")} / {r.reviewedAt.toISOString()} {r.feedback}</p>)}
        {d.permissions.manage && !["READY", "CANCELLED"].includes(d.status) && <details><summary>Onboarding follow-up</summary><OnboardingCommand realm={realm} own={false} command={command("REMIND")} label="Send reminder" management />{["NOT_READY", "READINESS_REVIEW"].includes(d.status) && <OnboardingCommand realm={realm} own={false} command={command("REOPEN")} label="Reopen OJT" management />}<OnboardingCommand realm={realm} own={false} command={command("CANCEL")} label="Cancel onboarding" management /></details>}
      </> : <><form method="get" action={base} className="nj-filters"><WorkspaceReturnFields query={query} /><input type="hidden" name="view" value={view} /><label>Search<input name="search" maxLength={120} defaultValue={value("search")} /></label><label>Status<select name="status" defaultValue={value("status") ?? ""}><option value="">All</option>{onboardingStates.map(s => <option key={s}>{s}</option>)}</select></label><label>Readiness<select name="readinessStatus" defaultValue={value("readinessStatus") ?? ""}><option value="">All</option>{["PENDING", "READY", "NOT_READY", "NEEDS_REVIEW"].map(s => <option key={s}>{s}</option>)}</select></label>{options && <><label>Company<select name="companyId" defaultValue={value("companyId") ?? options.company.id}><option value={options.company.id}>{options.company.name}</option></select></label><label>Division<select name="divisionId" defaultValue={value("divisionId") ?? ""}><option value="">All authorized divisions</option>{options.divisions.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Job version<select name="versionId" defaultValue={value("versionId") ?? ""}><option value="">All authorized job versions</option>{options.versions.map(o => <option key={o.id} value={o.id}>{o.title} / v{o.number}</option>)}</select></label><label>Reviewer<select name="reviewerUserId" defaultValue={value("reviewerUserId") ?? ""}><option value="">All assigned reviewers</option>{options.reviewers.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{options.limited && <p>Filter choices are limited to 100 records. Narrow the list using search.</p>}</>}<button className="button">Filter</button></form><div className="nj-application-list">{!list?.records.length && <p>No onboarding records match these filters in your authorized scope.{own && " Accept an offer and enroll from My Applications."}</p>}{list?.records.map(r => <article key={r.id}><h2><Link href={href({ reference: r.reference })}>{r.title}</Link></h2><p>{r.candidate} / {r.division} / v{r.version}</p><strong>{r.status.replaceAll("_", " ")}</strong><p>Readiness: {r.readinessStatus.replaceAll("_", " ")}</p>{Object.entries(r.configuration).filter(([, configured]) => !configured).map(([key]) => <p key={key}>{key}: NOT CONFIGURED</p>)}</article>)}</div>{list?.nextCursor && <Link href={href({ cursor: list.nextCursor })}>Next page</Link>}</>}
    </section>;
  } catch (e) {
    if (e instanceof AccessError || e instanceof NiceJobsUnavailable || e instanceof ZodError) return <section className="nj-workspace"><h1>Onboarding</h1><p role="alert">{e instanceof ZodError ? "Invalid onboarding filters." : e instanceof NiceJobsUnavailable ? "Nice Jobs is currently unavailable." : "This onboarding view is not available to your account."}</p><Link href={`${base}?view=${view}`}>Back to onboarding</Link></section>;
    throw e;
  }
}
