"use client";
import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { z } from "zod";
import { interviewConfiguration, offerConfiguration, managementConfiguration, interviewTypes } from "@/server/nicejobs/recruitment-input";
import { ApplicationCommand } from "./application-form";
type Interview = z.infer<typeof interviewConfiguration>;
export function RecruitmentConfiguration({ realm, versionId, revision, initial, choices }: { realm: string; versionId: string; revision: number; initial: Record<string, unknown> | null; choices: { divisions: { id: string; name: string }[]; controls: { id: string; name: string; organizationId: string }[] } }) {
  const parsed = interviewConfiguration.safeParse(initial?.interview), offer = offerConfiguration.safeParse(initial?.offer), management = managementConfiguration.safeParse(initial?.management);
  const [interview, setInterview] = useState<Interview | null>(parsed.success ? parsed.data : null);
  const [policies, setPolicies] = useState(management.success ? management.data.policies : []);
  const [offerConfig, setOffer] = useState<z.infer<typeof offerConfiguration> | null>(offer.success ? offer.data : null);
  const config = { ...initial, schemaVersion: 1, interview: interview ?? initial?.interview ?? null, management: policies.length ? { policies } : null, offer: offerConfig ?? initial?.offer ?? null };
  return <ApplicationCommand realm={realm} operation="CONFIGURE" versionId={versionId} revision={revision} label="Save interview and offer configuration"><input type="hidden" name="configuration" value={JSON.stringify(config)} />
    <h3>Interview configuration</h3>{!interview ? <><p>INTERVIEW NOT CONFIGURED</p><button className="button button-secondary" type="button" onClick={() => setInterview({ enabled: true, type: "ONLINE", duration: 30, minInterviewers: 1, maxInterviewers: 1, questions: [], evaluationRequired: true })}><Plus size={16} />Configure interview</button></> : <><label className="nj-check"><input type="checkbox" checked={interview.enabled} onChange={e => setInterview({ ...interview, enabled: e.target.checked })} />Interview required</label><label>Method<select value={interview.type} onChange={e => setInterview({ ...interview, type: e.target.value as Interview["type"] })}>{interviewTypes.map(t => <option key={t}>{t}</option>)}</select></label>{["duration", "minInterviewers", "maxInterviewers"].map(key => <label key={key}>{key === "duration" ? "Duration (minutes)" : key === "minInterviewers" ? "Minimum interviewers" : "Maximum interviewers"}<input type="number" min={key === "duration" ? 5 : 1} max={key === "duration" ? 240 : 10} value={interview[key as "duration"]} onChange={e => setInterview({ ...interview, [key]: Number(e.target.value) })} /></label>)}<label className="nj-check"><input type="checkbox" checked={interview.evaluationRequired} onChange={e => setInterview({ ...interview, evaluationRequired: e.target.checked })} />Evaluation required</label>
      {interview.questions.map((q, index) => { const change = (patch: Partial<typeof q>) => setInterview({ ...interview, questions: interview.questions.map((row, n) => n === index ? { ...row, ...patch } : row) }); return <fieldset key={index}><legend>Question {index + 1}</legend><label>Question key<input value={q.key} maxLength={50} onChange={e => change({ key: e.target.value })} /></label><label>Question<textarea value={q.question} maxLength={1000} required onChange={e => change({ question: e.target.value })} /></label><label>Type<select value={q.type} onChange={e => change({ type: e.target.value as typeof q.type })}>{["TEXT", "SINGLE_SELECT", "MULTI_SELECT", "RATING", "YES_NO"].map(t => <option key={t}>{t}</option>)}</select></label>{q.type.includes("SELECT") && <label>Options<textarea value={q.options?.join("\n") ?? ""} onChange={e => change({ options: e.target.value.split("\n").filter(Boolean) })} /></label>}{["order", "weight"].map(key => <label key={key}>{key === "order" ? "Order" : "Weight"}<input type="number" min={key === "order" ? 0 : 1} max={key === "order" ? 1000 : 100} value={q[key as "order"]} onChange={e => change({ [key]: Number(e.target.value) })} /></label>)}{["required", "active"].map(key => <label key={key} className="nj-check"><input type="checkbox" checked={q[key as "required"]} onChange={e => change({ [key]: e.target.checked })} />{key}</label>)}<button type="button" className="button button-secondary" aria-label={`Remove question ${index + 1}`} title="Remove question" onClick={() => setInterview({ ...interview, questions: interview.questions.filter((_, n) => n !== index) })}><Trash2 size={16} /></button></fieldset>; })}
      <button type="button" className="button button-secondary" disabled={interview.questions.length >= 40} onClick={() => setInterview({ ...interview, questions: [...interview.questions, { key: "question_" + (interview.questions.length + 1), question: "", type: "TEXT", required: true, active: true, weight: 1, order: interview.questions.length + 1 }] })}><Plus size={16} />Add question</button></>}
    <h3>Management approval policy</h3>{choices.divisions.map(d => <label key={d.id}>{d.name}<select value={policies.find(p => p.divisionId === d.id)?.controlPointId ?? ""} onChange={e => setPolicies([...policies.filter(p => p.divisionId !== d.id), ...(e.target.value ? [{ divisionId: d.id, controlPointId: e.target.value }] : [])])}><option value="">Not configured</option>{choices.controls.filter(c => c.organizationId === d.id).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>)}
    <h3>Offer template</h3>{!offerConfig ? <><p>OFFER NOT CONFIGURED</p><button type="button" className="button button-secondary" onClick={() => setOffer({ title: "", content: { startDate: null, compensation: null, incentives: null, expectations: null, terms: null }, validityDays: null, declineReasonRequired: false })}><Plus size={16} />Configure offer</button></> : <><label>Offer title<input value={offerConfig.title} required maxLength={200} onChange={e => setOffer({ ...offerConfig, title: e.target.value })} /></label><label>Template reference<input value={offerConfig.reference ?? ""} maxLength={200} onChange={e => setOffer({ ...offerConfig, reference: e.target.value || undefined })} /></label>{["startDate", "compensation", "incentives", "expectations", "terms"].map(key => <label key={key}>{key === "startDate" ? "Start date" : key[0].toUpperCase() + key.slice(1)}{key === "startDate" ? <input type="date" value={offerConfig.content.startDate ?? ""} onChange={e => setOffer({ ...offerConfig, content: { ...offerConfig.content, startDate: e.target.value || null } })} /> : <textarea value={offerConfig.content[key as "terms"] ?? ""} maxLength={4000} onChange={e => setOffer({ ...offerConfig, content: { ...offerConfig.content, [key]: e.target.value || null } })} />}</label>)}<label>Validity (days)<input type="number" min={1} max={365} value={offerConfig.validityDays ?? ""} onChange={e => setOffer({ ...offerConfig, validityDays: e.target.value ? Number(e.target.value) : null })} /></label><label className="nj-check"><input type="checkbox" checked={offerConfig.declineReasonRequired} onChange={e => setOffer({ ...offerConfig, declineReasonRequired: e.target.checked })} />Decline reason required</label></>}
  </ApplicationCommand>;
}
