import Link from "next/link";
import { recruitmentService } from "@/server/nicejobs/recruitment";
import { RecruitmentCommand } from "./recruitment-command";

export async function RecruitmentWorkspace({ userId, reference, own, realm, href: destination, interviewsAfter, offersAfter, interviewerSearch, interviewersAfter }: { userId: string; reference: string; own: boolean; realm: string; href: (changes: Record<string, string | undefined>) => string; interviewsAfter?: string; offersAfter?: string; interviewerSearch?: string; interviewersAfter?: string }) {
  const href = (changes: Record<string, string | undefined>) => destination({ reference, interviewerSearch, ...changes });
  const d = await recruitmentService.detail(userId, reference, own, { ...(interviewsAfter ? { interviewsAfter } : {}), ...(offersAfter ? { offersAfter } : {}), ...(interviewerSearch ? { interviewerSearch } : {}), ...(interviewersAfter ? { interviewersAfter } : {}) });
  const can = (key: string) => d.permissions["nicejobs." + key] && (!key.startsWith("offer.") || key === "offer.read" || d.permissions["nicejobs.offer.read"]);
  const reason = <label>Private reason / notes<textarea name="reason" required maxLength={1000} /></label>;
  const command = (operation: string, label: string, children?: React.ReactNode, extra = {}) => <RecruitmentCommand key={operation + JSON.stringify(extra)} realm={realm} command={{ reference, revision: d.revision, operation, ...extra }} label={label}>{children}</RecruitmentCommand>;
  const date = (value: Date | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: d.timezone ?? "Asia/Kolkata" }).format(value) + " (" + (d.timezone ?? "Asia/Kolkata") + ")" : "Not scheduled";
  const contentFields = (snapshot?: Record<string, unknown>) => <>{["startDate", "compensation", "incentives", "expectations", "terms"].map(key => <label key={key}>{key === "startDate" ? "Start date" : key[0].toUpperCase() + key.slice(1)}{key === "startDate" ? <input name={"content:" + key} type="date" defaultValue={String(snapshot?.[key] ?? "")} /> : <textarea name={"content:" + key} maxLength={4000} defaultValue={String(snapshot?.[key] ?? "")} />}</label>)}</>;
  return <section className="nj-recruitment"><h2>Interview &amp; offer</h2>
    {!d.interviewConfigured && <p>INTERVIEW NOT CONFIGURED</p>}{d.interviewRequired === false && <p>Interview not required by this job version.</p>}
    {!own && can("interview.schedule") && d.interviewRequired && (d.status === "SHORTLISTED" || d.status === "MANAGEMENT_REVIEW" && d.review?.status === "NEEDS_REVIEW") && <details><summary>Prepare interview</summary><form method="get" action={href({ interviewersAfter: undefined }).split("?")[0]} className="nj-filters">{[...new URLSearchParams(href({ interviewersAfter: undefined, interviewerSearch: undefined }).split("?")[1])].map(([key, value]) => <input key={key} type="hidden" name={key} value={value} />)}<label>Find interviewer<input name="interviewerSearch" maxLength={120} defaultValue={interviewerSearch} /></label><button className="button">Search</button></form>{d.nextPanel && <Link href={href({ interviewerSearch, interviewersAfter: d.nextPanel })}>More interviewers</Link>}{command("CREATE_INTERVIEW", "Create interview", <>{reason}<label>Interviewers<select aria-label="Interviewers" name="interviewerIds" required multiple>{d.panelOptions.map(p => <option key={p.id} value={p.id}>{p.person?.displayName}</option>)}</select></label>{!d.panelOptions.length && <p>No eligible interviewer accounts in this scope.</p>}</>)}</details>}
    {d.interviews.map(i => <article key={i.reference} className="nj-record"><h3>Interview {i.number} / {i.type}</h3><dl className="nj-detail"><dt>Status</dt><dd>{i.status.replaceAll("_", " ")}</dd><dt>Time</dt><dd>{date(i.scheduledAt)}</dd><dt>Duration</dt><dd>{i.duration} minutes</dd><dt>Location / reference</dt><dd>{i.location || "Not configured"}</dd><dt>Instructions</dt><dd>{i.instructions || "Not provided"}</dd></dl>
      {own && d.status === "INTERVIEW" && i.status === "SCHEDULED" && command("REQUEST_RESCHEDULE", "Request reschedule", <label>Reason<textarea name="reason" required maxLength={1000} /></label>, { interviewReference: i.reference, recordRevision: i.revision })}
      {!own && d.status === "INTERVIEW" && can("interview.schedule") && ["PENDING", "SCHEDULED", "RESCHEDULE_REQUESTED"].includes(i.status) && <details><summary>Scheduling and attendance</summary>{command("SCHEDULE", i.status === "PENDING" ? "Schedule interview" : "Reschedule interview", <>{reason}<label>Interview time (UTC)<input name="scheduledAt" type="datetime-local" step={60} required /></label><label>Location / reference<input name="location" maxLength={500} defaultValue={i.location ?? ""} /></label><label>Candidate instructions<textarea name="instructions" maxLength={2000} defaultValue={i.instructions ?? ""} /></label></>, { interviewReference: i.reference, recordRevision: i.revision })}{["CANCEL_INTERVIEW", ...(i.status === "SCHEDULED" ? ["COMPLETE_INTERVIEW", "NO_SHOW"] : [])].map(op => command(op, op.replaceAll("_", " "), reason, { interviewReference: i.reference, recordRevision: i.revision }))}</details>}
      {"assigned" in i && i.assigned && d.status === "INTERVIEW" && can("interview.evaluate") && !i.evaluations?.some(e => e.userId === userId && e.submitted) && ["SCHEDULED", "COMPLETED"].includes(i.status) && <details><summary>Submit private evaluation</summary><RecruitmentCommand realm={realm} command={{ reference, revision: d.revision, operation: "EVALUATE", interviewReference: i.reference, recordRevision: i.revision }} label="Submit evaluation" questions={i.questions}>{reason}<label>Recommendation<select name="recommendation" required><option value="">Select</option>{["RECOMMEND", "DO_NOT_RECOMMEND", "NEEDS_REVIEW"].map(r => <option key={r}>{r}</option>)}</select></label></RecruitmentCommand></details>}
      {"evaluations" in i && i.evaluations?.map(e => <details key={e.userId}><summary>{e.submitted ? "Submitted evaluation" : "Evaluation pending"} / {e.name}</summary>{e.evaluation && <><p>{e.evaluation.recommendation} / Score {e.evaluation.weightedScore.toFixed(1)}%</p><p>{e.evaluation.notes}</p><dl className="nj-detail">{Object.entries(e.evaluation.answers).map(([key, answer]) => <div key={key}><dt>{i.questions?.find(q => q.key === key)?.question ?? key}</dt><dd>{String(answer)}</dd></div>)}</dl></>}</details>)}
    </article>)}
    {d.nextInterviews && <Link href={href({ interviewsAfter: d.nextInterviews })}>Older interview records</Link>}
    {!own && can("management.review") && <section><h3>Management decision</h3><p>{d.review?.status.replaceAll("_", " ")}</p>{["SHORTLISTED", "MANAGEMENT_REVIEW"].includes(d.status) && (!d.review?.request || d.review?.status === "NEEDS_REVIEW") && command("START_REVIEW", "Request management approval", reason)}{d.status === "MANAGEMENT_REVIEW" && d.review?.request && <>{["SUBMITTED", "DRAFT"].includes(d.review.request.status) && command("MORE_REVIEW", "Request further review", reason)}<ol className="nj-history">{d.review.request.approvals.map(a => <li key={a.id}><strong>Level {a.stageIndex + 1} / {a.status}</strong><p>{a.approver?.person?.displayName ?? "Recorded approver"}</p><p>{a.comment}</p>{a.decidedAt && <p>{date(a.decidedAt)}</p>}{a.status === "PENDING" && d.permissions["approval.decide"] && a.approverUserId === userId && ["APPROVED", "REJECTED"].filter(decision => can(decision === "APPROVED" ? "management.approve" : "management.reject")).map(decision => command("DECIDE", decision === "APPROVED" ? "Approve" : "Reject", <>{reason}<label>Candidate-visible message<textarea name="candidateMessage" maxLength={1000} /></label></>, { approvalId: a.id, decision }))}</li>)}</ol>{["APPROVED", "REJECTED"].includes(d.review.request.status) && command("RELEASE_DECISION", "Release management decision", <>{reason}<label>Candidate-visible message<textarea name="candidateMessage" maxLength={1000} /></label></>)}</>}</section>}
    {!d.offerConfigured && <p>OFFER NOT CONFIGURED</p>}
    {!own && can("offer.prepare") && d.offerConfigured && ["APPROVED", "OFFER"].includes(d.status) && !d.offers.some(o => o.active) && command("PREPARE_OFFER", "Prepare offer", reason)}
    {d.offers.map(o => <article key={o.reference} className="nj-record"><h3>{String(o.snapshot.title)} / Version {o.number}</h3><strong>{o.expired ? "Validity expired" : o.status.replaceAll("_", " ")}</strong><dl className="nj-detail">{["company", "division", "jobTitle", "jobVersion", "engagement", "startDate", "compensation", "incentives", "expectations", "terms"].map(key => <div key={key}><dt>{key.replace(/([A-Z])/g, " $1")}</dt><dd>{String(o.snapshot[key] || "NOT CONFIGURED")}</dd></div>)}<dt>Issued</dt><dd>{o.issuedAt ? date(o.issuedAt) : "Not issued"}</dd><dt>Valid until</dt><dd>{o.expiresAt ? date(o.expiresAt) : "No configured expiry"}</dd>{o.acceptedAt && <><dt>Accepted</dt><dd>{date(o.acceptedAt)}</dd></>}</dl>
      {own && o.active && !o.expired && ["ISSUED", "VIEWED"].includes(o.status) && <div className="nj-actions">{o.status === "ISSUED" && command("VIEW_OFFER", "Acknowledge offer review", undefined, { offerReference: o.reference, recordRevision: o.revision })}{command("ACCEPT_OFFER", "Accept offer", undefined, { offerReference: o.reference, recordRevision: o.revision })}{command("DECLINE_OFFER", "Decline offer", <label>Decline reason<textarea name="reason" required={!!o.snapshot.declineReasonRequired} maxLength={1000} /></label>, { offerReference: o.reference, recordRevision: o.revision })}</div>}
      {!own && o.active && ["DRAFT", "READY", "ISSUED", "VIEWED"].includes(o.status) && <details><summary>Offer controls</summary>{can("offer.prepare") && can("offer.withdraw") && command("REVISE_OFFER", "Create revised offer", <>{reason}{contentFields(o.snapshot)}</>, { offerReference: o.reference, recordRevision: o.revision })}{o.status === "DRAFT" && can("offer.prepare") && command("READY_OFFER", "Confirm offer reviewed", reason, { offerReference: o.reference, recordRevision: o.revision })}{o.status === "READY" && can("offer.issue") && command("ISSUE_OFFER", "Issue offer", reason, { offerReference: o.reference, recordRevision: o.revision })}{can("offer.withdraw") && command(o.expired ? "EXPIRE_OFFER" : "WITHDRAW_OFFER", o.expired ? "Record offer expiry" : "Withdraw offer", reason, { offerReference: o.reference, recordRevision: o.revision })}</details>}
    </article>)}{d.nextOffers && <Link href={href({ offersAfter: d.nextOffers })}>Older offer records</Link>}
  </section>;
}
