import Link from "next/link";
import { niceJobsService as service } from "@/server/nicejobs/service";
import { configurationSections, workerStates, NiceJobsUnavailable } from "@/server/nicejobs/input";
import { JobForm } from "./job-form";
import { ConfigurationEditor } from "./configuration-editor";
import { RecruitmentConfiguration } from "./recruitment-configuration";
import { recruitmentService } from "@/server/nicejobs/recruitment";
import { onboardingService } from "@/server/nicejobs/onboarding";
import { TrainingConfiguration } from "./training-configuration";
import { AccessError } from "@/server/authorization/engine";
import { ZodError } from "zod";
import { workspaceReturnKeys } from "@/lib/workspace-navigation";
import { WorkspaceReturnFields } from "@/components/ui/workspace-return-fields";

export async function NiceJobsWorkspace({ userId, realm, base, query }: { userId: string; realm: string; base: string; query: Record<string, string | string[] | undefined> }) {
  const value = (key: string) => typeof query[key] === "string" ? query[key] as string : undefined;
  const view = value("view") ?? "templates", mode = ["published", "drafts", "workforce"].includes(view) ? view : "templates";
  try {
    const options = await service.options(userId);
    const filters = { ...(value("companyId") ? { companyId: value("companyId") } : {}), ...(value("divisionId") ? { divisionId: value("divisionId") } : {}), ...(value("jobId") ? { jobId: value("jobId") } : {}), search: value("search") ?? "", ...(value("cursor") ? { after: value("cursor") } : {}), ...(mode === "workforce" ? { ...(value("assignmentStatus") ? { assignmentStatus: value("assignmentStatus") } : {}), ...(value("lifecycle") ? { lifecycle: value("lifecycle") } : {}) } : { ...(mode === "published" ? { status: "PUBLISHED" } : mode === "drafts" ? { status: "DRAFT" } : value("status") ? { status: value("status") } : {}) }) };
    const href = (changes: Record<string, string | undefined>) => { const p = new URLSearchParams(); for (const key of ["view", "companyId", "divisionId", "jobId", "search", "status", "assignmentStatus", "lifecycle", ...workspaceReturnKeys]) if (value(key)) p.set(key, value(key)!); for (const [k, v] of Object.entries(changes)) { if (v) p.set(k, v); else p.delete(k); } return `${base}?${p}`; };
    const jobs = options.readJobs ? await service.jobs(userId, mode === "workforce" ? { ...(value("divisionId") ? { divisionId: value("divisionId") } : {}), status: "PUBLISHED" } : filters) : null;
    const workers = mode === "workforce" ? await service.workforce(userId, filters) : null;
    const detail = value("versionId") ? await service.detail(userId, value("versionId")!) : null;
    const v = detail?.version;
    const trainingAccess = v && !v.publishedAt && v.status === "DRAFT" && detail?.capabilities.edit ? await onboardingService.configurationAccess(userId, v.id) : null;
    const selectedDivision = value("divisionId");
    const people = selectedDivision && options.assignIds.includes(selectedDivision) ? await service.people(userId, selectedDivision, value("personSearch") ?? "", value("peopleCursor")) : null;
    const fields = (edit = false) => <><label>Job title<input name="title" maxLength={200} required defaultValue={edit ? v?.title : ""} /></label>{!edit && <><label>Job code<input name="code" required maxLength={40} pattern="[A-Z0-9][A-Z0-9_-]+" /></label><label>Visibility<select name="visibility"><option value="INTERNAL">Internal</option><option value="PUBLIC">Public when published</option></select></label></>}
      <label>Engagement<select name="engagement" defaultValue={edit ? v?.engagement : "PART_TIME_INCENTIVE"}><option value="PART_TIME_INCENTIVE">Part-time / incentive-based</option><option value="PART_TIME">Part-time</option><option value="FULL_TIME">Full-time</option><option value="CONTRACT">Contract</option></select></label>
      <fieldset><legend>Business areas</legend>{options.divisions.filter(d => (edit ? detail?.capabilities.edit : options.createIds.includes(d.id))).map(d => <label key={d.id} className="nj-check"><input type="checkbox" name="divisionIds" value={d.id} defaultChecked={edit && v?.areas.some(a => a.divisionId === d.id)} />{d.name}</label>)}</fieldset>
      <label>Department / context<input name="context" maxLength={500} defaultValue={edit ? v?.context ?? "" : ""} /></label><label>Description<textarea name="description" maxLength={4000} defaultValue={edit ? v?.description ?? "" : ""} /></label></>;
    return <div className="nj-workspace"><header><p>AIRA Career Hub / Nice Jobs</p><h1>{v ? v.title : mode === "workforce" ? "Workforce" : "Job Templates"}</h1><p>{options.companyName}</p></header>
      <nav aria-label="Nice Jobs">{[["templates", "Job Templates"], ["published", "Published Jobs"], ["drafts", "Drafts"], ["workforce", "Workforce"]].filter(([key]) => key === "workforce" ? options.readWorkers : options.readJobs).map(([key, label]) => <Link key={key} href={href({ view: key, versionId: undefined, cursor: undefined })} aria-current={mode === key ? "page" : undefined}>{label}</Link>)}</nav>
      <nav aria-label="Application workspaces"><Link href={href({ view: "opportunities", versionId: undefined })}>Available jobs</Link><Link href={href({ view: "my-applications", versionId: undefined })}>My Applications</Link><Link href={href({ view: "applications", versionId: undefined })}>Applications</Link></nav>
      {v && detail ? <><Link href={href({ versionId: undefined })}>Back to job list</Link><dl className="nj-detail"><dt>Job</dt><dd>{v.template.code} / v{v.number}</dd><dt>Company</dt><dd>{v.template.company.name}</dd><dt>Business areas</dt><dd>{v.areas.map(a => a.division.name).join(" / ")}</dd><dt>Engagement</dt><dd>{v.engagement === "PART_TIME_INCENTIVE" ? "Part-time / incentive-based" : v.engagement.replaceAll("_", " ")}</dd><dt>Status</dt><dd>{v.publishedAt ? v.template.publishedVersionId !== v.id ? "Historical published version" : v.template.status : v.status}</dd><dt>Description</dt><dd>{v.description || "Not configured yet"}</dd></dl>
        {!v.publishedAt && v.status === "DRAFT" && detail.capabilities.edit && <details><summary>Application and screening configuration</summary><ConfigurationEditor realm={realm} versionId={v.id} revision={v.revision} initial={v.configuration ? JSON.parse(v.configuration) : null} /></details>}
        {trainingAccess && (trainingAccess.orientation || trainingAccess.ojt) && <details><summary>Orientation, OJT and readiness configuration</summary><TrainingConfiguration key={v.revision} realm={realm} versionId={v.id} revision={v.revision} initial={v.configuration ? JSON.parse(v.configuration) : null} access={trainingAccess} /></details>}
        {!v.publishedAt && v.status === "DRAFT" && detail.capabilities.edit && <details><summary>Interview, approval and offer configuration</summary><RecruitmentConfiguration key={v.revision} realm={realm} versionId={v.id} revision={v.revision} initial={v.configuration ? JSON.parse(v.configuration) : null} choices={await recruitmentService.configurationChoices(userId, v.id)} /></details>}
        {!v.template.publishedVersionId && ["DRAFT", "REVIEW"].includes(v.template.status) && detail.capabilities.publish && <details><summary>Publication audience</summary><JobForm realm={realm} operation="job-visibility" id={v.id} revision={v.template.revision} label="Save audience" confirm><label>Audience<select name="to" defaultValue={v.template.visibility}><option value="INTERNAL">Internal</option><option value="PUBLIC">Public when published</option></select></label><label>Reason<textarea name="reason" required maxLength={1000} /></label></JobForm></details>}
        <div className="nj-actions">{!v.publishedAt && v.status === "DRAFT" && detail.capabilities.edit && <details><summary>Edit draft</summary><JobForm realm={realm} operation="edit" id={v.id} revision={v.revision}>{fields(true)}</JobForm></details>}
          {v.publishedAt && v.template.status !== "ARCHIVED" && detail.capabilities.edit && <JobForm realm={realm} operation="version" id={v.id} revision={v.template.revision} label="Create new version" />}
          {(v.template.status === "ARCHIVED" ? [] : [
            ...(!v.publishedAt && v.status === "DRAFT" && detail.capabilities.edit ? [["REVIEW", "Submit for review", v.revision]] : []),
            ...((!v.publishedAt || v.template.status === "PAUSED") && detail.capabilities.publish ? [["PUBLISHED", "Publish", v.publishedAt ? v.template.revision : v.revision]] : []),
            ...(v.publishedAt && v.template.status === "PUBLISHED" && detail.capabilities.pause ? [["PAUSED", "Pause", v.template.revision]] : []),
            ...(detail.capabilities.archive ? [["ARCHIVED", "Archive", v.template.revision]] : [])
          ]).map(([to, label, revision]) => <JobForm key={String(to)} realm={realm} operation="job-state" id={v.id} revision={Number(revision)} label={String(label)} confirm><input type="hidden" name="to" value={String(to)} /><label>Reason<input name="reason" required maxLength={1000} /></label></JobForm>)}</div>
        <h2>Configuration</h2><dl className="nj-detail">{configurationSections.map(key => <div key={key}><dt>{key.replace(/([A-Z])/g, " $1")}</dt><dd>{v.configuration && (JSON.parse(v.configuration)[key]?.reference || JSON.parse(v.configuration)[key] && "Configured") || "Not configured yet"}</dd></div>)}</dl>
      </> : <><form method="get" className="nj-filters"><WorkspaceReturnFields query={query} /><input type="hidden" name="view" value={mode} /><label>Company<select name="companyId" defaultValue={value("companyId") ?? options.companyId}><option value={options.companyId}>{options.companyName}</option></select></label><label>Division<select name="divisionId" defaultValue={selectedDivision ?? ""}><option value="">Authorized divisions</option>{options.divisions.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Search<input name="search" maxLength={200} defaultValue={value("search") ?? ""} /></label>{mode === "workforce" ? <><label>Job<select name="jobId" defaultValue={value("jobId") ?? ""}><option value="">All authorized jobs</option>{jobs?.records.map(j => <option key={j.id} value={j.templateId}>{j.title}</option>)}</select></label><label>Assignment<select name="assignmentStatus" defaultValue={value("assignmentStatus") ?? ""}><option value="">All statuses</option>{["PREPARED", "ACTIVE", "SUSPENDED", "ENDED"].map(s => <option key={s}>{s}</option>)}</select></label><label>Lifecycle<select name="lifecycle" defaultValue={value("lifecycle") ?? ""}><option value="">All stages</option>{workerStates.map(s => <option key={s}>{s}</option>)}</select></label></> : mode === "templates" && <label>Status<select name="status" defaultValue={value("status") ?? ""}><option value="">All statuses</option>{["DRAFT", "REVIEW", "PUBLISHED", "PAUSED", "ARCHIVED"].map(s => <option key={s}>{s}</option>)}</select></label>}<button className="button" type="submit">Filter</button><Link href={`${base}?view=${mode}`}>Clear</Link></form>
        <div className="table-scroll" role="region" aria-label={mode === "workforce" ? "Workforce records" : "Job templates"} tabIndex={0}><table className="business-table"><thead><tr>{(workers ? ["Worker", "Job / Version", "Company", "Division", "Assignment", "Lifecycle", "Start date", "Manager", "Next stage"] : ["Job / Code", "Company", "Business areas", "Engagement", "Version", "Status", "Created", "Updated"]).map(s => <th key={s}>{s}</th>)}</tr></thead><tbody>{workers ? workers.records.map(w => <tr key={w.id}><td>{w.profile.person.displayName}</td><td>{w.version.title} / v{w.version.number}</td><td>{w.version.template.company.name}</td><td>{w.division.name}</td><td>{w.status}</td><td>{w.lifecycle}</td><td>{w.startDate ? w.startDate.toISOString().slice(0, 10) + " UTC" : "Not configured yet"}</td><td>{w.manager?.displayName ?? "Unassigned"}</td><td>{workers.transitionIds.includes(w.division.id) && w.lifecycle !== "EXITED" && <JobForm realm={realm} operation="lifecycle" id={w.id} revision={w.revision} label="Record stage" confirm><label>Next stage<select name="to">{({ APPLICANT: ["APPROVED"], APPROVED: ["OFFERED"], OFFERED: ["OFFER_ACCEPTED"], OFFER_ACCEPTED: ["ORIENTATION"], ORIENTATION: ["OJT"], OJT: ["ACTIVE"], ACTIVE: ["SUSPENDED"], SUSPENDED: ["ACTIVE"] }[w.lifecycle] ?? []).map(s => <option key={s}>{s}</option>)}</select></label><label>Reason / evidence<input name="reason" required maxLength={1000} /></label></JobForm>}</td></tr>) : jobs?.records.map(j => <tr key={j.id}><td><Link href={href({ versionId: j.id })}>{j.title}</Link><br />{j.template.code}</td><td>{j.template.company.name}</td><td>{j.areas.map(a => a.division.name).join(" / ")}</td><td>{j.engagement === "PART_TIME_INCENTIVE" ? "Part-time / incentive-based" : j.engagement}</td><td>v{j.number}</td><td>{j.publishedAt ? j.template.publishedVersionId !== j.id ? "Historical published version" : j.template.status : j.template.status === "ARCHIVED" ? "ARCHIVED" : j.status}</td><td>{j.createdAt.toISOString().slice(0, 10)} UTC</td><td>{j.updatedAt.toISOString().slice(0, 10)} UTC</td></tr>)}</tbody></table></div>
        {!(workers?.records.length ?? jobs?.records.length) && <p>{mode === "workforce" ? "No workforce assignments in this scope." : !options.readJobs ? "Job templates are not authorized for this account." : "No job templates match this view."}</p>}
        {(workers?.nextCursor ?? jobs?.nextCursor) && <Link href={href({ cursor: workers?.nextCursor ?? jobs?.nextCursor ?? undefined })}>Next page</Link>}
        {mode !== "workforce" && <p>More jobs coming soon</p>}
        {options.canCreate && mode === "templates" && <>{options.canSeed && <JobForm realm={realm} operation="seed" label="Configure initial catalogue" confirm />}<details><summary>Create draft job</summary><JobForm realm={realm} operation="create">{fields()}</JobForm></details></>}
        {mode === "workforce" && people && <section><h2>Prepare assignment</h2><form method="get"><WorkspaceReturnFields query={query} /><input type="hidden" name="companyId" value={options.companyId} /><input type="hidden" name="view" value="workforce" /><input type="hidden" name="divisionId" value={selectedDivision} /><label>Find existing person<input name="personSearch" maxLength={200} defaultValue={value("personSearch") ?? ""} /></label><button className="button" type="submit">Search people</button></form>{people.nextCursor && <Link href={href({ peopleCursor: people.nextCursor, personSearch: value("personSearch") })}>Next people</Link>}<JobForm realm={realm} operation="assign" label="Prepare assignment" confirm><input type="hidden" name="divisionId" value={selectedDivision} /><label>Worker<select name="personId" required><option value="">Select person</option>{people.records.map(p => <option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label><label>Published job<select name="versionId" required><option value="">Select job</option>{jobs?.records.filter(j => j.template.publishedVersionId === j.id).map(j => <option key={j.id} value={j.id}>{j.title} / v{j.number}</option>)}</select></label><label>Manager<select name="managerId"><option value="">Unassigned</option>{people.records.map(p => <option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label></JobForm></section>}
      </>}
    </div>;
  } catch (e) {
    if (e instanceof NiceJobsUnavailable) return <section><h1>Nice Jobs</h1><p role="alert">Nice Jobs is currently unavailable. Its company and Career Hub configuration require review.</p></section>;
    if (e instanceof AccessError) return <section><h1>Nice Jobs</h1><p role="alert">This view is not authorized for your current account and scope.</p></section>;
    if (e instanceof ZodError) return <section><h1>Nice Jobs</h1><p role="alert">These filters are invalid.</p><Link href={base}>Reset filters</Link></section>;
    throw e;
  }
}
