import { z } from "zod";
import { requiredUtcDate } from "@/server/domain/execution-input";
const id = z.string().min(1).max(200);
const note = z.string().trim().max(4000);
export const interviewTypes = ["ONLINE", "OFFLINE", "PHONE", "VIDEO"] as const;
export const interviewStates = ["PENDING", "SCHEDULED", "RESCHEDULE_REQUESTED", "COMPLETED", "CANCELLED", "NO_SHOW"] as const;
export const offerStates = ["DRAFT", "READY", "ISSUED", "VIEWED", "ACCEPTED", "DECLINED", "EXPIRED", "WITHDRAWN"] as const;
export const interviewConfiguration = z.object({ enabled: z.boolean(), type: z.enum(interviewTypes), duration: z.number().int().min(5).max(240), minInterviewers: z.number().int().min(1).max(10).default(1), maxInterviewers: z.number().int().min(1).max(10).default(1), questions: z.array(z.object({ key: z.string().regex(/^[a-z][a-z0-9_]{0,49}$/).refine(k => !["constructor", "prototype"].includes(k)), question: z.string().trim().min(1).max(1000), type: z.enum(["TEXT", "SINGLE_SELECT", "MULTI_SELECT", "RATING", "YES_NO"]), required: z.boolean().default(true), order: z.number().int().min(0).max(1000), weight: z.number().int().min(1).max(100).default(1), active: z.boolean().default(true), options: z.array(z.string().min(1).max(120)).max(40).optional() }).strict()).max(40), evaluationRequired: z.boolean().default(true) }).strict().superRefine((c, ctx) => {
  if (c.minInterviewers > c.maxInterviewers || new Set(c.questions.map(q => q.key)).size !== c.questions.length || new Set(c.questions.map(q => q.order)).size !== c.questions.length) ctx.addIssue({ code: "custom", message: "Invalid interviewer/question configuration" });
  for (const q of c.questions) if (["SINGLE_SELECT", "MULTI_SELECT"].includes(q.type) && (!q.options?.length || new Set(q.options).size !== q.options.length)) ctx.addIssue({ code: "custom", message: "Selection questions require unique options" });
  if (c.enabled && c.evaluationRequired && !c.questions.some(q => q.active)) ctx.addIssue({ code: "custom", message: "Required evaluation needs active questions" });
});
export const managementConfiguration = z.object({ policies: z.array(z.object({ divisionId: id, controlPointId: id }).strict()).min(1).max(12) }).strict().refine(c => new Set(c.policies.map(p => p.divisionId)).size === c.policies.length, "One policy per division");
export const offerContent = z.object({ startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v => Number.isFinite(Date.parse(v)) && new Date(v).toISOString().slice(0, 10) === v).nullable().default(null), compensation: note.nullable().default(null), incentives: note.nullable().default(null), expectations: note.nullable().default(null), terms: note.nullable().default(null) }).strict();
export const offerConfiguration = z.object({ title: z.string().trim().min(1).max(200), reference: id.optional(), content: offerContent, validityDays: z.number().int().min(1).max(365).nullable().default(null), declineReasonRequired: z.boolean().default(false) }).strict();
export const recruitmentInput = z.object({ reference: z.string().uuid(), revision: z.number().int().min(0), operation: z.enum(["CREATE_INTERVIEW", "SCHEDULE", "REQUEST_RESCHEDULE", "CANCEL_INTERVIEW", "COMPLETE_INTERVIEW", "NO_SHOW", "EVALUATE", "START_REVIEW", "MORE_REVIEW", "DECIDE", "RELEASE_DECISION", "PREPARE_OFFER", "REVISE_OFFER", "READY_OFFER", "ISSUE_OFFER", "VIEW_OFFER", "ACCEPT_OFFER", "DECLINE_OFFER", "WITHDRAW_OFFER", "EXPIRE_OFFER"]), interviewReference: z.string().uuid().optional(), offerReference: z.string().uuid().optional(), recordRevision: z.number().int().min(0).optional(), scheduledAt: requiredUtcDate.optional(), interviewerIds: z.array(id).min(1).max(10).refine(a => new Set(a).size === a.length).optional(), location: z.string().trim().max(500).optional(), instructions: z.string().trim().max(2000).optional(), reason: z.string().trim().min(1).max(1000).optional(), answers: z.record(z.string(), z.union([z.string().max(4000), z.number().finite(), z.boolean(), z.array(z.string().max(120)).max(40)])).optional(), scores: z.record(z.string(), z.number().min(0).max(10)).optional(), recommendation: z.enum(["RECOMMEND", "DO_NOT_RECOMMEND", "NEEDS_REVIEW"]).optional(), approvalId: id.optional(), decision: z.enum(["APPROVED", "REJECTED"]).optional(), candidateMessage: z.string().trim().max(1000).optional(), content: offerContent.optional() }).strict();
