import { Pagination } from "../pagination";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireSession } from "@/server/auth/guards";
import { communicationsService } from "@/server/communications/service";
import { siaService } from "@/server/sia/service";
import { operationsService } from "@/server/domain/operations-service";
import { CommunicationForm, Composer } from "./forms";
import { WorkspaceReturnFields } from "@/components/ui/workspace-return-fields";
import { UserTime } from "@/components/ui/user-time";
const views = ["overview", "integrations", "messages", "threads", "templates", "policies", "consent", "automation", "jobs", "webhooks", "delivery"] as const;
const titles: Record<string, string> = { overview: "Communication Overview", integrations: "Integrations", messages: "Messages", threads: "Threads", templates: "Templates", policies: "Communication Policies", consent: "Consent", automation: "Automation", jobs: "Scheduled Jobs", webhooks: "Webhooks", delivery: "Delivery Status" };
const utc = (d: Date | null) => <UserTime value={d}/>;
export default async function CommunicationsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const session = await requireSession(), q = await searchParams, view = q.view ?? "overview";
  if (!views.includes(view as typeof views[number])) notFound();
  const data = await communicationsService.workspace(session.userId, q.organizationId || undefined, { status: q.status, channel: q.channel, search: q.search, threadId: q.threadId, view, cursor: q.cursor });
  const org = q.organizationId ?? "", can = (key: string) => !!org && data.capabilities[key].includes(org);
  const selected = data.organizations.find(o => o.id === org);
  const revision = data.messages.find(m => m.id === q.revise && m.creatorUserId === session.userId && m.direction === "OUTBOUND");
  const sia = view === "messages" ? await siaService.workspace(session.userId) : null;
  const accounts = view === "automation" ? (await operationsService.workspace(session.userId)).users : [];
  const revisionHref = (messageId: string, organizationId: string) => {
    const query = new URLSearchParams(Object.entries(q).filter((entry): entry is [string, string] => typeof entry[1] === "string"));
    query.set("view", "messages"); query.set("organizationId", organizationId); query.set("revise", messageId);
    return "/app/communications?" + query.toString();
  };
  return <div className="communication-workspace">
    <header className="page-header"><div><h1>{titles[view]}</h1><p className="muted">{selected?.name ?? "Authorized scopes"}</p></div></header>
    <nav className="communication-tabs" aria-label="Communication views">{views.map(v => <Link key={v} href={`/app/communications?view=${v}${org ? "&organizationId=" + encodeURIComponent(org) : ""}`} aria-current={v === view ? "page" : undefined}>{titles[v]}</Link>)}</nav>
    <form method="get" className="communication-filters"><WorkspaceReturnFields query={q}/><input name="view" type="hidden" value={view} /><label>Organization<select name="organizationId" defaultValue={org}><option value="">All authorized</option>{data.organizations.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Channel<select name="channel" defaultValue={q.channel ?? ""}><option value="">All</option><option>EMAIL</option><option>WHATSAPP</option></select></label><label>Status<select name="status" defaultValue={q.status ?? ""}><option value="">All</option>{["APPROVAL_REQUIRED", "QUEUED", "SENDING", "ACCEPTED", "SENT", "DELIVERED", "READ", "FAILED", "UNKNOWN", "REJECTED", "CANCELLED", "SIMULATED"].map(s => <option key={s}>{s}</option>)}</select></label><label>Search<input name="search" defaultValue={q.search} maxLength={200} /></label><button className="button secondary">Apply</button></form>
    {view === "overview" && <><div className="communication-metrics">{Object.entries(data.overview).map(([key, value]) => <div key={key}><span className="muted">{key.replace(/([A-Z])/g, " $1")}</span><strong>{value}</strong></div>)}</div><h2>Provider Status</h2>{data.integrations.length ? <div className="table-wrap"><table><thead><tr><th>Integration</th><th>Provider</th><th>Status</th></tr></thead><tbody>{data.integrations.map(i => <tr key={i.id}><td>{i.name}</td><td>{i.provider}</td><td>{i.status}</td></tr>)}</tbody></table></div> : <p className="muted">No integrations configured.</p>}</>}
    {view === "integrations" && <>
      {can("integration.manage") && <details><summary>Add Integration</summary><CommunicationForm command="integration" organizationId={org}><Fields><Text name="name" label="Name" /><Channel /><Select name="provider" label="Provider" options={["MOCK", "EMAIL_UNCONFIGURED", "TALKINLABS"]} /><Text name="sender" label="Authorized sender" /><label>Credential reference<input name="credentialReference" placeholder="env:REFERENCE_NAME" autoComplete="off" /></label><label><input type="checkbox" name="enabled" />Enabled</label></Fields></CommunicationForm></details>}
      <Table headings={["Name", "Channel", "Provider", "Status", "Credential", "Action"]} empty="No integrations configured.">{data.integrations.map(i => <tr key={i.id}><td>{i.name}</td><td>{i.channel}</td><td>{i.provider}</td><td>{i.status}</td><td>{i.credentialConfigured ? "Referenced" : "Not configured"}</td><td>{data.capabilities["integration.manage"].includes(i.organizationId) && <CommunicationForm command="integration" organizationId={i.organizationId} id={i.id} version={i.version} label={i.enabled ? "Disable" : "Enable"}><input type="hidden" name="name" value={i.name} /><input type="hidden" name="channel" value={i.channel} /><input type="hidden" name="provider" value={i.provider} /><input type="hidden" name="sender" value={i.sender} />{!i.enabled && <input type="hidden" name="enabled" value="true" />}</CommunicationForm>}</td></tr>)}</Table>
    </>}
    {view === "messages" && <>{can("communication.draft") && <details open><summary>Prepare Message</summary><CommunicationForm command="propose" organizationId={org} label="Prepare preview"><Composer idempotencyKey={crypto.randomUUID()} initial={revision} templates={data.templates.filter(t => t.organizationId === org && t.status === "ACTIVE")}><Select name="integrationId" label="Integration" defaultValue={revision?.integrationId} rows={data.integrations.filter(i => i.organizationId === org)} /><Select name="policyId" label="Policy" defaultValue={revision?.policyId ?? undefined} rows={data.policies.filter(i => i.organizationId === org && !i.projectId && i.status === "ACTIVE")} /><Select name="consentId" label="Recipient" defaultValue={revision?.consentId} rows={data.consents.filter(c => c.organizationId === org && c.status === "OPTED_IN").map(c => ({ id: c.id, name: c.personName + " - " + c.channel + " - " + c.address }))} /><Text name="purpose" label="Purpose" defaultValue={revision?.purpose} /><Select name="category" label="Category" defaultValue={revision?.category} options={["OPERATIONAL", "TRANSACTIONAL"]} /><label>Prepared by<select name="siaId"><option value="">Human operator</option>{sia?.identities.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</select></label></Composer></CommunicationForm></details>}
      <section className="communication-message-list">{data.messages.map(m => <article key={m.id} className="communication-message"><header><strong>{m.subject ?? m.purpose}</strong><span>{m.status}</span></header><dl><dt>Recipient</dt><dd>{m.recipient}</dd><dt>Channel</dt><dd>{m.channel}</dd><dt>Sender</dt><dd>{m.sender}</dd><dt>Purpose</dt><dd>{m.purpose}</dd><dt>Company / Scope</dt><dd>{data.organizations.find(o => o.id === m.organizationId)?.name ?? m.organizationId}</dd><dt>Risk</dt><dd>{m.direction === "OUTBOUND" ? "HIGH_RISK_WRITE" : "Inbound data"}</dd><dt>Approval required</dt><dd>{m.direction === "OUTBOUND" ? data.requestStatuses[m.id] : "Not applicable"}</dd><dt>Recorded</dt><dd>{utc(m.createdAt)}</dd></dl><p className="communication-content">{m.content}</p>{m.requestId && <Link href={`/app/operations/approvals?organizationId=${m.organizationId}`}>Human approval queue</Link>}{m.creatorUserId === session.userId && <div className="communication-actions"><Link href={revisionHref(m.id, m.organizationId)}>Prepare revision</Link>{m.status === "APPROVAL_REQUIRED" && data.requestStatuses[m.id] === "APPROVED" && <CommunicationForm command="confirm" id={m.id} version={m.version} label="Confirm queue"><label><input name="confirmed" type="checkbox" required />I confirm this exact recipient and message</label></CommunicationForm>}{["APPROVAL_REQUIRED", "QUEUED", "FAILED"].includes(m.status) && <CommunicationForm command="cancel" id={m.id} version={m.version} label="Cancel" />}{m.requestId && data.requestStatuses[m.id] === "DRAFT" && <Link href={`/app/operations/requests?organizationId=${m.organizationId}`}>Submit approval request</Link>}</div>}</article>)}{!data.messages.length && <p className="muted">No messages match this view.</p>}</section></>}
    {view === "threads" && <Table headings={["Channel", "Status", "Priority", "Last Activity", "Action"]} empty="No threads.">{data.threads.map(t => <tr key={t.id}><td><Link href={`/app/communications?view=messages&organizationId=${t.organizationId}&threadId=${t.id}`}>{t.channel}</Link></td><td>{t.status}</td><td>{t.priority}</td><td>{utc(t.lastActivityAt)}</td><td>{data.capabilities["communication.draft"].includes(t.organizationId) && <CommunicationForm command="thread" id={t.id}><Select name="status" label="Status" options={[t.status, t.status === "OPEN" ? "CLOSED" : "OPEN"]} /><Select name="priority" label="Priority" options={[t.priority, t.priority === "NORMAL" ? "HIGH" : "NORMAL"]} /></CommunicationForm>}</td></tr>)}</Table>}
    {view === "templates" && <>{can("communication.template.manage") && <details><summary>Add Template Version</summary><CommunicationForm command="template" organizationId={org}><Fields><Text name="name" label="Name" /><Text name="key" label="Key" /><label>Version<input type="number" name="version" defaultValue={1} min={1} max={10000} required /></label><Text name="purpose" label="Purpose" /><Channel /><Text name="subject" label="Subject" required={false} /><Text name="variables" label="Variables" required={false} /><label className="wide">Body<textarea name="content" rows={4} maxLength={4000} required /></label></Fields></CommunicationForm></details>}<Table headings={["Name", "Channel", "Version", "Status", "Action"]} empty="No templates.">{data.templates.map(t => <tr key={t.id}><td>{t.name}<details><summary>Content</summary><p>{t.subject}</p><p className="communication-content">{t.body}</p></details></td><td>{t.channel}</td><td>{t.version}</td><td>{t.status}</td><td>{t.status === "ACTIVE" && data.capabilities["communication.template.manage"].includes(t.organizationId) && <CommunicationForm command="archive" id={t.id} label="Archive"><input type="hidden" name="kind" value="template" /></CommunicationForm>}</td></tr>)}</Table></>}
    {view === "policies" && <>{can("communication.policy.manage") && <details><summary>Add Policy</summary><CommunicationForm command="policy" organizationId={org}><Fields><Text name="name" label="Name" /><Select name="controlPointId" label="Independent approval control" rows={data.controls.filter(c => c.organizationId === org)} /><Channel /><Text name="sender" label="Allowed sender" /><Select name="category" label="Category" options={["OPERATIONAL", "TRANSACTIONAL"]} /><label>Per minute<input name="perMinute" type="number" min={1} max={30} defaultValue={5} required /></label><label>Per day<input name="perDay" type="number" min={1} max={500} defaultValue={100} required /></label><label>UTC start hour<input name="hourStart" type="number" min={0} max={23} /></label><label>UTC end hour<input name="hourEnd" type="number" min={1} max={24} /></label></Fields></CommunicationForm></details>}<Table headings={["Name", "Channels", "Limits", "Approval", "Status", "Action"]} empty="No policies configured.">{data.policies.map(p => { const c = JSON.parse(p.configuration); return <tr key={p.id}><td>{p.name}</td><td>{c.channels.join(", ")}</td><td>{c.perMinute}/minute; {c.perDay}/day</td><td>Independent human</td><td>{p.status}</td><td>{p.status === "ACTIVE" && data.capabilities["communication.policy.manage"].includes(p.organizationId) && <CommunicationForm command="archive" id={p.id} label="Archive"><input name="kind" type="hidden" value="policy" /></CommunicationForm>}</td></tr>; })}</Table></>}
    {view === "consent" && <>{can("communication.consent.manage") && <details><summary>Record Consent</summary><CommunicationForm command="consent" organizationId={org}><Fields><Select name="personId" label="Person" rows={data.people.map(p => ({ id: p.id, name: p.displayName }))} /><Channel /><Select name="status" label="Consent" options={["OPTED_IN", "OPTED_OUT"]} /><Text name="source" label="Evidence source" /></Fields></CommunicationForm></details>}<Table headings={["Person", "Channel", "Address", "Status", "Source", "Recorded", "Action"]} empty="No consent recorded.">{data.consents.map(c => <tr key={c.id}><td>{c.personName}</td><td>{c.channel}</td><td>{c.address}</td><td>{c.status}</td><td>{c.source}</td><td>{utc(c.recordedAt)}</td><td>{data.capabilities["communication.consent.manage"].includes(c.organizationId) && <CommunicationForm command="consent" organizationId={c.organizationId} version={c.version}><input name="personId" type="hidden" value={c.personId} /><input name="channel" type="hidden" value={c.channel} /><Select name="status" label="Consent" options={[c.status, c.status === "OPTED_IN" ? "OPTED_OUT" : "OPTED_IN"]} /><Text name="source" label="Evidence source" /></CommunicationForm>}</td></tr>)}</Table></>}
    {view === "automation" && <>{can("automation.manage") && <details><summary>Add Rule</summary><CommunicationForm command="rule" organizationId={org}><Fields><Text name="name" label="Name" /><Select name="trigger" label="Trigger" options={["TASK_OVERDUE", "APPROVAL_PENDING", "PROJECT_BLOCKED"]} /><Select name="action" label="Action" options={["NOTIFY_OWNER", "REMIND_APPROVER", "FLAG_ATTENTION"]} /><Select name="recipientUserId" label="Responsible person" rows={accounts} /><label>Minimum age (minutes)<input name="minimumAgeMinutes" type="number" min={0} max={525600} defaultValue={0} /></label><label><input name="enabled" type="checkbox" />Enabled</label></Fields></CommunicationForm></details>}<Table headings={["Name", "Trigger", "Action", "Status"]} empty="No automation rules.">{data.rules.map(r => <tr key={r.id}><td>{r.name}</td><td>{r.trigger}</td><td>{r.action}</td><td>{r.enabled ? "Enabled" : "Disabled"}{data.capabilities["automation.manage"].includes(r.organizationId) && r.ownerUserId === session.userId && <CommunicationForm command="rule" organizationId={r.organizationId} id={r.id} version={r.version} label={r.enabled ? "Disable" : "Enable"}><input name="name" type="hidden" value={r.name} /><input name="trigger" type="hidden" value={r.trigger} /><input name="action" type="hidden" value={r.action} /><input name="recipientUserId" type="hidden" value={JSON.parse(r.condition).recipientUserId} /><input name="minimumAgeMinutes" type="hidden" value={JSON.parse(r.condition).minimumAgeMinutes} />{!r.enabled && <input name="enabled" type="hidden" value="true" />}</CommunicationForm>}</td></tr>)}</Table></>}
    {view === "jobs" && <>{can("automation.manage") && <details><summary>Schedule Job</summary><CommunicationForm command="job"><Fields><Select name="ruleId" label="Rule" rows={data.rules.filter(r => r.organizationId === org)} /><label>Next run (UTC)<input name="nextRunAt" type="date" required /></label><label>Interval (minutes)<input name="intervalMinutes" type="number" min={1} max={525600} defaultValue={60} required /></label><label>Maximum runs<input name="maxRuns" type="number" min={1} max={1000} defaultValue={1} required /></label></Fields></CommunicationForm></details>}{can("automation.process") && <CommunicationForm command="processJobs" label="Process due jobs" />}<Table headings={["Rule", "Status", "Runs", "Next Run", "Failure", "Action"]} empty="No scheduled jobs.">{data.jobs.map(j => <tr key={j.id}><td>{data.rules.find(r => r.id === j.ruleId)?.name}</td><td>{j.status}</td><td>{j.runs}/{j.maxRuns}</td><td>{utc(j.nextRunAt)}</td><td>{j.failureCode ?? "None"}</td><td>{j.status === "PENDING" && data.capabilities["automation.manage"].includes(j.organizationId) && <CommunicationForm command="pauseJob" id={j.id} version={j.version} label="Cancel" />}</td></tr>)}</Table></>}
    {view === "webhooks" && <Table headings={["Provider Event", "Type", "Result", "Received", "Failure"]} empty="No verified webhook events.">{data.events.map(e => <tr key={e.id}><td>{e.externalEventId}</td><td>{e.type}</td><td>{e.status}</td><td>{utc(e.receivedAt)}</td><td>{e.failureCode ?? "None"}</td></tr>)}</Table>}
    {view === "delivery" && <>{can("communication.process") && <CommunicationForm command="process" label="Process due deliveries" />}<Table headings={["Message", "Channel", "Status", "Attempts", "Next Retry", "Failure", "Action"]} empty="No deliveries.">{data.messages.filter(m => m.direction === "OUTBOUND").map(m => <tr key={m.id}><td>{m.subject ?? m.purpose}</td><td>{m.channel}</td><td>{m.status}{m.simulated ? " (mock)" : ""}</td><td>{m.attempts}/{m.maxAttempts}</td><td>{utc(m.nextRetryAt)}</td><td>{m.failureCode ?? "None"}</td><td>{data.capabilities["communication.process"].includes(m.organizationId) && (m.status === "QUEUED" || m.status === "FAILED" && m.retryable) && <CommunicationForm command="delivery" id={m.id} label="Process" />}</td></tr>)}</Table></>}
    <Pagination path="/app/communications" query={q} nextCursor={data.nextCursor}/>
  </div>;
}
function Fields({ children }: { children: React.ReactNode }) { return <div className="communication-fields">{children}</div>; }
function Text({ name, label, required = true, defaultValue }: { name: string; label: string; required?: boolean; defaultValue?: string }) { return <label>{label}<input name={name} maxLength={200} required={required} defaultValue={defaultValue} /></label>; }
function Channel() { return <Select name="channel" label="Channel" options={["EMAIL", "WHATSAPP"]} />; }
function Select({ name, label, options, rows, defaultValue }: { name: string; label: string; options?: string[]; rows?: { id: string; name: string }[]; defaultValue?: string }) { return <label>{label}<select name={name} required defaultValue={defaultValue}>{rows ? <><option value="">Choose</option>{rows.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</> : options?.map(o => <option key={o}>{o}</option>)}</select></label>; }
function Table({ headings, children, empty }: { headings: string[]; children: React.ReactNode[]; empty: string }) { return children.length ? <div className="table-wrap"><table><thead><tr>{headings.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div> : <p className="muted">{empty}</p>; }
