import Link from "next/link";
import { ArrowUpRight, AlertTriangle, Bot } from "lucide-react";
import { UserTime } from "@/components/ui/user-time";
import { bossHref } from "@/server/group/boss-reliability";
import { Status } from "@/components/ui/status";
import { workspaceHref } from "@/lib/workspace-navigation";
import type { bossService } from "@/server/group/boss-service";
import { inventoryHref, overviewInventories, overviewHref, overviewKey, overviewQueues, type OverviewQueue, type OverviewInventory } from "@/server/group/boss-overview";
type Data = Awaited<ReturnType<typeof bossService.dashboard>>;

export function OverviewRows({ data, queue, limit, item, query = {} }: { query?: Record<string, string | string[] | undefined>; data: Data; queue: OverviewQueue; limit?: number; item?: string }) {
  const overview = data.overview;
  const sourceHref = (href: string) => workspaceHref(href, data.selectedCompanyId, "overview", new URLSearchParams(Object.entries(query).filter((entry): entry is [string, string] => typeof entry[1] === "string")));
  const rows = overview.queues[queue].filter(r => !item || overviewKey(r) === item).slice(0, limit);
  if (!rows.length) return <p className="executive-empty">{!overview.coverage[queue] ? "Not authorized to assess this source." : item ? "This record is no longer in this queue or is not accessible." : `No ${overviewQueues[queue].toLowerCase()} in accessible records.`}</p>;
  return <ul className="executive-list">{rows.map(row => <li key={overviewKey(row)}><div><Link prefetch={false} href={overviewHref(queue, data.selectedCompanyId, overviewKey(row), query)}>{row.title}<ArrowUpRight size={14}/></Link><small>{row.type.replaceAll("_", " ")} / <Status value={row.status}/></small><p>{overview.nextAction(row)}</p><small>{overview.owner(row)} / Due: <UserTime value={row.dueAt} empty="Not recorded"/></small>{item && <><p>Company/scope: {data.snapshot.options.organizations.find(o => o.id === row.organizationId)?.name ?? "Authorized scope"} / Updated: <UserTime value={row.updatedAt}/></p><Link prefetch={false} href={sourceHref(row.type === "DECISION" ? `/app/boss?view=decisions${data.selectedCompanyId ? `&companyId=${encodeURIComponent(data.selectedCompanyId)}` : ""}&recordId=${encodeURIComponent(row.id)}` : `${row.href}${row.href.includes("?") ? "&" : "?"}recordId=${encodeURIComponent(row.id)}&organizationId=${encodeURIComponent(row.organizationId)}`)}>Open source record<ArrowUpRight size={14}/></Link></>}</div></li>)}</ul>;
}

export async function BossOverview({ data, selection, companies, query }: { query: Record<string, string | string[] | undefined>; data: Data; selection: { queue?: OverviewQueue; inventory?: OverviewInventory; item?: string }; companies: React.ReactNode }) {
  const { overview, selectedCompanyId } = data;
  const sourceHref = (href: string) => workspaceHref(href, selectedCompanyId, "overview", new URLSearchParams(Object.entries(query).filter((entry): entry is [string, string] => typeof entry[1] === "string")));
  if (selection.inventory) {
    const kind = selection.inventory;
    const work = kind === "projects" ? data.snapshot.projects : kind === "goals" ? data.snapshot.goals : kind === "tasks" ? data.snapshot.tasks : kind === "critical" ? data.snapshot.attention.filter(r => r.severity === "CRITICAL" && !["RESOLVED", "DISMISSED"].includes(r.handlingStatus)) : [];
    const registry = kind === "brands" ? data.brands : kind === "products" ? data.products : [];
    const active = registry.filter(r => "status" in r && r.status === "ACTIVE");
    const readable = kind === "companies" ? true : kind === "critical" ? data.snapshot.metrics.some(m => m.value !== null) : data.readable[({ brands: "brand", products: "product", projects: "project", goals: "goal", tasks: "task" } as Record<string, string>)[kind]];
    return <section className="executive-band"><header><h2>{overviewInventories[kind]}</h2><Link prefetch={false} href={bossHref("overview", selectedCompanyId, query)}>Back to overview</Link></header><p className="muted">Current authorized snapshot / Saved work-list filters do not change this selection.</p>{!readable ? <p className="executive-empty">Not authorized to assess this source.</p> : kind === "companies" ? companies : <><ul className="executive-list">{work.map((r, index) => <li key={overviewKey(r) + index}><div><Link prefetch={false} href={sourceHref(`${r.href}${r.href.includes("?") ? "&" : "?"}recordId=${encodeURIComponent(r.id)}&organizationId=${encodeURIComponent(r.organizationId)}`)}>{r.title}<ArrowUpRight size={14}/></Link><Status value={r.status}/><small>{overview.owner(r)} / Due: <UserTime value={r.dueAt} empty="Not recorded"/></small></div></li>)}{active.map(r => <li key={r.id}><div><strong>{"name" in r ? String(r.name) : "Recorded item"}</strong><Status value={"status" in r ? String(r.status) : "Not recorded"}/><small>{"organizationId" in r ? data.companies.find(c => c.organizationId === r.organizationId)?.legalName ?? "Authorized scope" : "Authorized scope"}</small></div></li>)}</ul>{!work.length && !active.length && <p className="executive-empty">No {overviewInventories[kind].toLowerCase()} in accessible records.</p>}</>}</section>;
  }
  if (selection.queue) return <section className="executive-band"><header><h2>{overviewQueues[selection.queue]}</h2><Link prefetch={false} href={bossHref("overview", selectedCompanyId, query)}>Back to overview</Link></header><p className="muted">Current authorized records / Calculated <UserTime value={data.snapshot.calculatedAt}/>. Queue selection is independent of saved work-list filters.</p><OverviewRows query={query} data={data} queue={selection.queue} item={selection.item}/></section>;
  const first = overview.urgent[0] ?? (overview.queues.deadlines[0] ? { queue: "deadlines" as const, row: overview.queues.deadlines[0] } : undefined);
  const urgentCount = overview.urgent.length;
  return <>
    <section className="executive-band boss-next-action" aria-labelledby="next-action-heading"><header><h2 id="next-action-heading"><AlertTriangle size={18}/>What needs attention</h2><span>{urgentCount} distinct items in accessible records</span></header>{first ? <><h3><Link prefetch={false} href={overviewHref(first.queue, selectedCompanyId, overviewKey(first.row), query)}>{first.row.title}<ArrowUpRight size={16}/></Link></h3><p>{overview.nextAction(first.row)}</p><small>{overview.owner(first.row)} / Due: <UserTime value={first.row.dueAt} empty="Not recorded"/></small></> : <><p>No urgent items found in accessible records. This does not establish company health.</p>{!data.snapshot.tasks.length && !data.snapshot.projects.length && <p className="muted">No accessible tasks or projects are recorded. Start with an accountable owner and a deadline.</p>}<nav className="boss-detail-links" aria-label="Authorized next actions">{data.nextActions.map(a => <Link prefetch={false} key={a.href} href={sourceHref(a.href)}>{a.label}<ArrowUpRight size={14}/></Link>)}</nav></>}</section>
    <section className="executive-band"><header><h2>Work & follow-up</h2></header><nav className="workflow-shortcuts" aria-label="Authorized workflow shortcuts">{data.shortcuts.map(a => <Link prefetch={false} className="button secondary" key={a.href} href={sourceHref(a.href)}>{a.label}<ArrowUpRight size={16}/></Link>)}</nav></section>
    <div className="boss-attention-summary">{(Object.keys(overviewQueues) as OverviewQueue[]).filter(q => q !== "deadlines" && q !== "concerns").map(queue => <Link prefetch={false} key={queue} href={overviewHref(queue, selectedCompanyId, undefined, query)}><strong>{overview.coverage[queue] ? overview.queues[queue].length : "Not authorized"}</strong><span>{overviewQueues[queue]}</span></Link>)}</div>
    {overview.queues.concerns.length > 0 && <section className="executive-band"><header><h2>Goal & performance concerns</h2><Link prefetch={false} href={overviewHref("concerns", selectedCompanyId, undefined, query)}>View all ({overview.queues.concerns.length})</Link></header><OverviewRows query={query} data={data} queue="concerns" limit={3}/></section>}
    <section className="executive-band"><header><h2>Daily briefing</h2><span>{overview.day} / {overview.timezone}</span></header><p>{overview.changesToday.length} meaningful changes recorded today. {overview.queues.deadlines.length} accessible deadlines in the next seven days.</p><p className="muted">Priorities use recorded severity, your permitted human decisions and deadlines. Counts cover authorized records only, not a complete group assessment.</p><Link prefetch={false} href={overviewHref("deadlines", selectedCompanyId, undefined, query)}>Review upcoming deadlines<ArrowUpRight size={14}/></Link></section>
    <div className="boss-priorities"><section className="executive-band"><header><h2>Decisions & My Approvals</h2></header><OverviewRows query={query} data={data} queue="decisions" limit={3}/><OverviewRows query={query} data={data} queue="approvals" limit={3}/></section><section className="executive-band"><header><h2>Overdue work & blockers</h2></header><OverviewRows query={query} data={data} queue="overdue" limit={3}/><OverviewRows query={query} data={data} queue="blockers" limit={3}/></section></div>
    <section className="executive-band"><header><h2>Company priorities</h2></header>{companies}</section>
    <section className="executive-band"><header><h2>Recent meaningful changes</h2><Link prefetch={false} href={`/app/boss?view=changes${selectedCompanyId ? `&companyId=${encodeURIComponent(selectedCompanyId)}` : ""}`}>View period changes</Link></header>{!data.snapshot.changes.length && <p className="executive-empty">No meaningful changes recorded in the last seven days in accessible sources.</p>}<ul className="executive-list">{data.snapshot.changes.slice(0, 5).map(change => <li key={change.id}><div><Link prefetch={false} href={`/app/boss?view=changes${selectedCompanyId ? `&companyId=${encodeURIComponent(selectedCompanyId)}` : ""}&changeId=${encodeURIComponent(change.id)}`}>{change.title}<ArrowUpRight size={14}/></Link><small><UserTime value={change.createdAt}/> / {data.snapshot.options.organizations.find(o => o.id === change.organizationId)?.name ?? "Authorized scope"}</small></div></li>)}</ul></section>
    <section className="executive-band"><header><h2><Bot size={18}/>SIA assistance</h2><Status value={data.sia.status}/></header><p>Provider: {data.sia.provider}. Permitted assistance: {data.sia.capabilities.join(", ") || "None available"}.</p><p>{data.sia.canAsk ? "Configured read-only assistance is available for this scope." : "Assistance is unavailable in this scope; use the recorded owners and human decisions above."} Autonomous execution is disabled.</p>{data.sia.canAsk && <Link prefetch={false} href={sourceHref(data.sia.href)}>Ask SIA<ArrowUpRight size={14}/></Link>}</section>
    <section className="executive-band boss-inventory"><h2>Group inventory</h2><div className="boss-summary">{[["Companies", data.cards.length], ["Active brands", data.readable.brand ? data.brands.filter(b => "status" in b && b.status === "ACTIVE").length : "Not authorized"], ["Active products", data.readable.product ? data.products.filter(p => "status" in p && p.status === "ACTIVE").length : "Not authorized"]].map(([label, value]) => <div key={label}><span>{label}</span><strong className={typeof value === "string" ? "boss-summary-text" : undefined}>{value === "Not authorized" ? value : <Link prefetch={false} href={inventoryHref(label === "Companies" ? "companies" : label === "Active brands" ? "brands" : "products", selectedCompanyId, query)}>{value}</Link>}</strong></div>)}</div><Link prefetch={false} href={`/app/boss?view=brands${selectedCompanyId ? `&companyId=${encodeURIComponent(selectedCompanyId)}` : ""}`}>Review brands, domains & evidence<ArrowUpRight size={14}/></Link></section>
  </>;
}
