import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowUpRight, Bot, Building2, Filter, Network, ShieldCheck } from "lucide-react";
import { requireSession } from "@/server/auth/guards";
import { AccessError } from "@/server/authorization/engine";
import { bossService } from "@/server/group/boss-service";
import { ExecutiveView } from "../executive/view";
import { ZodError } from "zod";
import { Prisma } from "@prisma/client";
import { QueryBudgetError } from "@/server/domain/query-bounds";
import { bossFilterKeys, bossHref, bossStatuses, parseBossFilters } from "@/server/group/boss-reliability";

const views = bossViews;
import { bossViews, groupForView, workspaceHref } from "@/lib/workspace-navigation";
import { UserTime } from "@/components/ui/user-time";
import { Status } from "@/components/ui/status";
import { BossOverview } from "./overview";
import { inventoryHref, overviewHref, overviewKey, overviewSelection } from "@/server/group/boss-overview";
import { DomainEvidence } from "./domain-evidence";
type Data = Awaited<ReturnType<typeof bossService.dashboard>>;
const date = (d: Date | null) => <UserTime value={d}/>;
const count = (rows: unknown[]) => rows.length;
function Empty({ authorized = true }: { authorized?: boolean }) { return <p className="executive-empty">{authorized ? "No matching records" : "Not authorized"}</p>; }
const metricCount = (c: Data["cards"][number], source: string, value: number) => c.metrics.some(m => m.source === source && m.value !== null) ? value : "Not authorized";
const criticalCount = (c: Data["cards"][number]) => !c.evidence.readableMetrics ? "Not authorized" : `${c.attention.filter(a => a.severity === "CRITICAL").length}${c.evidence.readableMetrics < c.evidence.totalMetrics ? " / limited coverage" : ""}`;
function Links({ data, query }: { data: Data; query: Record<string, string | string[] | undefined> }) {
  const params = new URLSearchParams(Object.entries(query).flatMap(([key, value]) => typeof value === "string" ? [[key, value]] : []));
  return <nav className="boss-detail-links" aria-label="Company modules">{groupForView("companies").modules.map(m => <Link prefetch={false} key={m.href} href={workspaceHref(m.href, data.selectedCompanyId, typeof query.view === "string" ? query.view : "companies", params)}>{m.label}<ArrowUpRight size={14}/></Link>)}</nav>;
}
function CompanyCards({ data, query }: { data: Data; query: Record<string, string | string[] | undefined> }) {
  return <div className="boss-companies">{data.cards.map(c => <article className="boss-company" key={c.organizationId}>
    <header><Building2 size={22} /><div><h3><Link prefetch={false} href={bossHref("companies", c.organizationId, query)}>{c.legalName ?? c.displayName}</Link></h3><Status value={c.status}/>{" "}<Status value={c.health}/></div></header>
    {(() => { const priority = data.overview.urgent.find(item => [...c.projects, ...c.tasks, ...c.goals, ...c.decisions, ...c.attention].some(r => r.id === item.row.id && r.type === item.row.type) || c.metrics.some(m => m.entities.some(e => e.id === item.row.id))); const deadline = data.overview.queues.deadlines.find(r => [...c.projects, ...c.tasks, ...c.goals].some(item => item.id === r.id)); return <div className="boss-company-action">{priority ? <><Link prefetch={false} href={overviewHref(priority.queue, c.organizationId, overviewKey(priority.row), query)}>{priority.row.title}<ArrowUpRight size={14}/></Link><p>{data.overview.nextAction(priority.row)}</p><small>{data.overview.owner(priority.row)} / Due: <UserTime value={priority.row.dueAt} empty="Not recorded"/></small></> : <p>{c.evidence.recordCount ? "No urgent items found in accessible records." : "No recorded work to assess. Accountable work owners and deadlines are not established."}</p>}{deadline && <p>Next deadline: <Link prefetch={false} href={overviewHref("deadlines", c.organizationId, overviewKey(deadline), query)}>{deadline.title}</Link> / {date(deadline.dueAt)} / {data.overview.owner(deadline)}</p>}</div>; })()}
    <p className="boss-evidence">{c.evidence.coverage}<br />{c.evidence.readableMetrics}/{c.evidence.totalMetrics} readable metrics / {c.evidence.recordCount} recorded work items<br />{c.evidence.freshness}<br />Last record update: {date(c.evidence.lastUpdated)}<br />Calculated: {date(c.evidence.calculatedAt)}</p>
    <dl className="boss-company-counts">{[["Projects", metricCount(c, "PROJECT", c.projects.length)], ["Goals", metricCount(c, "GOAL", c.goals.length)], ["Tasks", metricCount(c, "TASK", c.tasks.length)], ["Critical attention", criticalCount(c)], ["Pending decisions", c.canReadDecisions ? c.decisions.filter(d => d.type === "DECISION").length : "Not authorized"], ["My approvals", metricCount(c, "APPROVAL", c.decisions.filter(d => d.type === "APPROVAL").length)]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value === "Not authorized" ? value : <Link prefetch={false} href={label === "Pending decisions" ? overviewHref("decisions", c.organizationId, undefined, query) : label === "My approvals" ? overviewHref("approvals", c.organizationId, undefined, query) : inventoryHref(label === "Projects" ? "projects" : label === "Goals" ? "goals" : label === "Tasks" ? "tasks" : "critical", c.organizationId, query)}>{value}</Link>}</dd></div>)}</dl>
    <details><summary>Brands, divisions & activity</summary><ul>{c.brands.map(b => <li key={b.id}>{"name" in b ? String(b.name) : "Not recorded"}{"website" in b && b.website ? ` / ${String(b.website)}` : ""}</li>)}</ul>{!c.brands.length && <Empty authorized={data.readable.brand} />}<p>Divisions: {c.divisions.map(d => "name" in d ? String(d.name) : "").join(", ") || (data.readable.organization ? "None recorded" : "Not authorized")}</p>{c.changes.slice(0, 3).map(a => <p key={a.id}>{a.title} / {date(a.createdAt)}</p>)}</details>
  </article>)}</div>;
}
export default async function BossPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const session = await requireSession(), query = await searchParams;
  const companyId = typeof query.companyId === "string" && query.companyId ? query.companyId : undefined;
  const view = typeof query.view === "string" ? query.view : "overview";
  if (!Object.hasOwn(views, view)) notFound();
  let data: Data;
  let selection: ReturnType<typeof overviewSelection.parse>;
  try { selection = overviewSelection.parse({ queue: query.queue || undefined, inventory: query.inventory || undefined, item: query.item || undefined }); data = await bossService.dashboard(session.userId, companyId, parseBossFilters(query)); } catch (e) {
    if (e instanceof Prisma.PrismaClientInitializationError || e instanceof Prisma.PrismaClientKnownRequestError || e instanceof QueryBudgetError) return <section className="business-empty"><h1>Boss Panel unavailable</h1><p>{e instanceof QueryBudgetError ? "The selected scope exceeds query capacity. Select a narrower company scope." : "Current records could not be verified. No counts or health assessment are available."}</p><Link prefetch={false} href="/app/boss">Retry</Link></section>;
    if (!(e instanceof AccessError || e instanceof ZodError)) throw e;
    return <section className="business-empty"><ShieldCheck size={28} /><h1>{e instanceof ZodError ? "Invalid filters" : "Boss Panel not authorized"}</h1><p>{e instanceof ZodError ? "Check the selected dates and filter values." : "You are not authorized for this panel or selected company."}</p><Link prefetch={false} href="/app/boss">Reset filters</Link></section>;
  }
  const href = (nextView: string) => bossHref(nextView, companyId, query);
  return <div className="boss-view"><header className="boss-heading"><div><p className="eyebrow">MAXPASE GROUP</p><h1>{bossViews[view as keyof typeof bossViews]}</h1></div>{data.sia.canAsk ? <Link prefetch={false} className="button secondary" href={data.sia.href}><Bot size={18} />Ask SIA</Link> : <button className="button secondary" disabled title={`SIA: ${data.sia.status}`}><Bot size={18} />SIA: {data.sia.status}</button>}</header>
    <form className="boss-selector" method="get"><input type="hidden" name="view" value={view} />{bossFilterKeys.map(k => typeof query[k] === "string" && query[k] ? <input key={k} type="hidden" name={k} value={query[k]} /> : null)}<label>Company<select name="companyId" defaultValue={companyId ?? ""}><option value="">All Companies</option>{data.companies.map(c => <option key={c.organizationId} value={c.organizationId}>{c.legalName ?? c.displayName}</option>)}</select></label><button className="icon-button" title="Select company" aria-label="Select company"><Filter size={18} /></button><span className="muted">{date(data.executive.calculatedAt)}</span></form>
    <nav className="boss-navigation" aria-label={`${groupForView(view).label} views`}>{groupForView(view).views.map(key => <Link prefetch={false} key={key} href={href(key)} aria-current={view === key ? "page" : undefined}>{bossViews[key]}</Link>)}</nav>
    {view === "overview" && <BossOverview query={query} data={data} selection={selection} companies={<CompanyCards data={data} query={query}/>} />}
    {view === "companies" && <section className="executive-band"><h2>Companies</h2><CompanyCards data={data} query={query} /></section>}
    {view === "brands" && <section className="executive-band"><h2>Brands & Domains</h2>{!data.brands.length && <Empty authorized={data.readable.brand} />}<div className="table-scroll" role="region" aria-label="Brands and domains" tabIndex={0}><table className="business-table boss-brands-table"><colgroup><col /><col /><col /><col /></colgroup><thead><tr><th>Company</th><th>Brand</th><th>Domain</th><th>Type / Status</th></tr></thead><tbody>{data.brands.map(b => <tr key={b.id}><td>{data.companies.find(c => "organizationId" in b && c.organizationId === b.organizationId)?.legalName ?? "Not recorded"}</td><td>{"name" in b ? String(b.name) : "Not recorded"}</td><td><DomainEvidence website={"website" in b && b.website ? String(b.website) : null} metadata={"metadata" in b && b.metadata ? String(b.metadata) : null} people={data.snapshot.options.people} calculatedAt={data.snapshot.calculatedAt}/></td><td><span>Brand / {"status" in b ? String(b.status) : "Not recorded"}</span><small>Evidence recorded separately</small></td></tr>)}</tbody></table></div><Links data={data} query={query} /></section>}
    {view === "people" && <section className="executive-band"><h2>People & Memberships</h2><nav className="boss-detail-links">{[["People", "people"], ["Roles", "roles"], ["Permissions", "permissions"], ["Reporting", "reporting"], ["Responsibilities", "responsibilities"], ["Company & project membership", "memberships"]].map(([label, kind]) => <Link prefetch={false} key={kind} href={workspaceHref(`/app/workforce/${kind}`, companyId, view, new URLSearchParams(Object.entries(query).flatMap(([key, value]) => typeof value === "string" ? [[key, value]] : [])))}>{label}</Link>)}</nav><p>Employment headcount: Unavailable</p><p className="muted">Active memberships are not an employment headcount.</p>{!data.members.length && <Empty authorized={data.readable.membership && data.readable.person} />}<ul className="executive-list">{data.members.slice(0, 50).map(m => <li key={m.id}>{m.name} / {m.projectId ? "Project membership" : "Company/group membership"}</li>)}</ul></section>}
    {view === "graph" && <section className="executive-band"><h2><Network size={18} />Business Graph</h2><Links data={data} query={query} /><ul className="boss-graph">{data.graph.organizations.map(o => <li key={o.id}><span className="status">{o.type}</span> {o.name}{o.parentId && <small> / {data.graph.organizations.find(p => p.id === o.parentId)?.name ?? "Outside visible scope"}</small>}</li>)}</ul><h3>Products</h3>{!data.products.length && <Empty authorized={data.readable.product} />}{data.products.map(p => <p key={p.id}>{"name" in p ? String(p.name) : "Not recorded"}</p>)}<h3>Ownership</h3>{!data.graph.ownership.length ? <Empty authorized={data.readable.ownership} /> : <Link prefetch={false} href="/app/business/ownership">{count(data.graph.ownership)} recorded relationships</Link>}<h3>Relationships</h3>{!data.graph.relationships.length ? <Empty authorized={data.readable.company} /> : <Link prefetch={false} href="/app/business/relationships">{count(data.graph.relationships)} recorded relationships</Link>}</section>}
    {view === "communications" && <section className="executive-band"><h2>Communications</h2><nav className="boss-detail-links">{["threads", "messages", "delivery", "automation", "jobs", "integrations"].map(v => <Link prefetch={false} key={v} href={`/app/communications?view=${v}${companyId ? `&organizationId=${encodeURIComponent(companyId)}` : ""}`}>{v[0].toUpperCase() + v.slice(1)}</Link>)}</nav>{!data.integrations.length && <p className="muted">{data.readable.integration ? "NOT CONFIGURED" : "Not authorized"}</p>}{data.integrations.map(i => <p key={i.id}>{i.name} / {i.channel} / {i.status.replaceAll("_", " ")}</p>)}<p>Automation jobs: {data.readable.automation ? count(data.jobs) : "Not authorized"} / Failed: {data.readable.automation ? count(data.jobs.filter(j => j.status === "FAILED")) : "Not authorized"}</p></section>}
    {view === "audit" && <section className="executive-band"><h2>Audit & Security</h2><nav className="boss-detail-links"><Link prefetch={false} href="/app/operations/activity">Activity</Link><Link prefetch={false} href="/app/operations/events">Operational events</Link><Link prefetch={false} href="/app/operations/approvals">Approvals</Link>{data.sia.canAsk && <Link prefetch={false} href={data.sia.href}>SIA actions & confirmations</Link>}</nav>{!data.audit.length && <Empty authorized={data.readable.audit} />}<ul className="executive-list">{data.audit.map(a => <li key={a.id}><div><strong>{a.action}</strong><small>{a.result} / {a.entityType} / {date(a.createdAt)}</small></div></li>)}</ul></section>}
    {view === "system" && <section className="executive-band"><h2>System Health</h2><h3>Measured on this request</h3><p className="muted">Observed {date(data.executive.calculatedAt)}. This is not uptime or deployment acceptance.</p><dl className="record-details">{Object.entries({ database: data.system.database, application: data.system.application, authentication: data.system.authentication }).map(([key, status]) => <div key={key}><dt>{key}</dt><dd>{status}</dd></div>)}</dl><h3>Operational assurance</h3><dl className="record-details">{Object.entries({ backup: data.system.backup, monitoring: data.system.monitoring, "Deployment verification": data.system.production }).map(([key, status]) => <div key={key}><dt>{key}</dt><dd>{status}</dd></div>)}</dl><h3>Configuration & permitted capabilities</h3><dl className="record-details"><div><dt>SIA</dt><dd>{data.sia.status}</dd></div><div><dt>Provider</dt><dd>{data.sia.provider}</dd></div><div><dt>Permitted SIA tools</dt><dd>{data.sia.capabilities.join(", ") || "None available"}</dd></div><div><dt>Autonomous execution</dt><dd>DISABLED</dd></div><div><dt>Integrations</dt><dd>{!data.readable.integration ? "Not authorized" : data.integrations.length ? "RECORDED / DELIVERY NOT VERIFIED" : "NOT CONFIGURED"}</dd></div><div><dt>Automation</dt><dd>{!data.readable.automation ? "Not authorized" : data.jobs.length ? `${data.jobs.length} recorded jobs / ${data.jobs.filter(j => j.status === "FAILED").length} failed` : "No recorded jobs"}</dd></div></dl></section>}
    {view === "operations" && <nav className="boss-detail-links" aria-label="Operational controls">{[["Workflows", "workflows"], ["Instances", "instances"], ["Requests", "requests"], ["Approvals", "approvals"], ["Recurring work", "recurring"], ["Reminders", "reminders"], ["Escalations", "escalations"], ["Control points", "controls"], ["Events", "events"], ["Activity", "activity"], ["My tasks", "my-tasks"]].map(([label, kind]) => <Link prefetch={false} key={kind} href={workspaceHref(`/app/operations/${kind}`, companyId ?? data.groupId, view, new URLSearchParams(Object.entries(query).flatMap(([key, value]) => typeof value === "string" ? [[key, value]] : [])))}>{label}</Link>)}</nav>}
    {["projects", "goals", "operations", "decisions", "attention", "briefing", "risks", "opportunities", "changes"].includes(view) && <ExecutiveView view={view} query={{ ...query, organizationId: companyId ?? data.groupId }} providedData={data.executive} bossContext={{ companyId, statuses: bossStatuses, unreadable: ({ projects: !data.readable.project, goals: !data.readable.goal, risks: !data.readable.risk, opportunities: !data.readable.opportunity } as Record<string, boolean>)[view] ?? false }} />}
  </div>;
}
