import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, ArrowUpRight, Bot, Building2, Clock, Filter, Network, ShieldCheck } from "lucide-react";
import { requireSession } from "@/server/auth/guards";
import { AccessError } from "@/server/authorization/engine";
import { bossService } from "@/server/group/boss-service";
import { ExecutiveView } from "../executive/view";

const views = { overview: "Command Center", companies: "Companies", brands: "Brands & Domains", people: "People", projects: "Projects", goals: "Goals", operations: "Operations", decisions: "Decisions", attention: "Attention", communications: "Communications", graph: "Business Graph", audit: "Audit & Security", system: "System", briefing: "Briefing", risks: "Risks", opportunities: "Opportunities", changes: "Changes" };
type Data = Awaited<ReturnType<typeof bossService.dashboard>>;
const date = (d: Date | null) => d ? d.toISOString().slice(0, 16).replace("T", " ") + " UTC" : "NO DATA";
const count = (rows: unknown[]) => rows.length || "NO DATA";
function Empty() { return <p className="executive-empty">NO DATA</p>; }
function Links({ data }: { data: Data }) {
  return <nav className="boss-detail-links" aria-label="Detailed workspaces">{[["Group", "/app/business/groups"], ["Companies", "/app/business/companies"], ["Brands", "/app/business/brands"], ["Products", "/app/business/products"], ["Projects", "/app/execution/projects"], ["People", "/app/workforce/people"], ["Ownership", "/app/business/ownership"], ["Relationships", "/app/business/relationships"]].map(([name, href]) => <Link key={name} href={href + (data.selectedCompanyId ? `?organizationId=${encodeURIComponent(data.selectedCompanyId)}` : "")}>{name}<ArrowUpRight size={14} /></Link>)}</nav>;
}
function CompanyCards({ data }: { data: Data }) {
  return <div className="boss-companies">{data.cards.map(c => <article className="boss-company" key={c.organizationId}><header><Building2 size={22} /><div><h3><Link href={`/app/boss?companyId=${encodeURIComponent(c.organizationId)}`}>{c.legalName ?? c.displayName}</Link></h3><span className="status">{c.status} / {c.health.replaceAll("_", " ")}</span></div></header><dl className="boss-company-counts">{[["Projects", c.projects.length], ["Goals", c.goals.length], ["Tasks", c.tasks.length], ["Critical attention", c.attention.filter(a => a.severity === "CRITICAL").length], ["Pending decisions", c.decisions.filter(d => d.type === "DECISION").length], ["My approvals", c.decisions.filter(d => d.type === "APPROVAL").length]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || "NO DATA"}</dd></div>)}</dl><details><summary>Brands, divisions & activity</summary><ul>{c.brands.map(b => <li key={b.id}>{"name" in b ? String(b.name) : "NO DATA"}{"website" in b && b.website ? ` / ${String(b.website)}` : ""}</li>)}</ul>{!c.brands.length && <Empty />}<p>Divisions: {c.divisions.map(d => "name" in d ? String(d.name) : "").join(", ") || "NO DATA"}</p><p>SIA: {data.sia.status === "NOT CONFIGURED" ? "NOT CONFIGURED" : "Select company context"}</p>{c.changes.slice(0, 3).map(a => <p key={a.id}>{a.title} / {date(a.createdAt)}</p>)}</details></article>)}</div>;
}
export default async function BossPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const session = await requireSession(), query = await searchParams;
  const companyId = typeof query.companyId === "string" && query.companyId ? query.companyId : undefined;
  const view = typeof query.view === "string" ? query.view : "overview";
  if (!Object.hasOwn(views, view)) notFound();
  let data: Data;
  try { data = await bossService.dashboard(session.userId, companyId); } catch (e) { if (!(e instanceof AccessError)) throw e; return <section className="business-empty"><ShieldCheck size={28} /><h1>Boss Panel unavailable</h1><p>Access or selected company context is unavailable.</p><Link href="/boss/login">Boss sign-in</Link></section>; }
  const suffix = companyId ? `&companyId=${encodeURIComponent(companyId)}` : "";
  const attention = data.executive.attention.filter(a => !["RESOLVED", "DISMISSED"].includes(a.handlingStatus));
  return <div className="boss-view"><header className="boss-heading"><div><p className="eyebrow">MAXPASE GROUP</p><h1>Master Command Center</h1></div><Link className="button secondary" href={data.sia.href}><Bot size={18} />Ask SIA</Link></header>
    <form className="boss-selector" method="get"><input type="hidden" name="view" value={view} /><label>Company<select name="companyId" defaultValue={companyId ?? ""}><option value="">All Companies</option>{data.companies.map(c => <option key={c.organizationId} value={c.organizationId}>{c.legalName ?? c.displayName}</option>)}</select></label><button className="icon-button" title="Select company" aria-label="Select company"><Filter size={18} /></button><span className="muted">{date(data.executive.calculatedAt)}</span></form>
    <nav className="boss-navigation" aria-label="Boss Panel">{Object.entries(views).map(([key, label]) => <Link key={key} href={`/app/boss?view=${key}${suffix}`} aria-current={view === key ? "page" : undefined}>{label}</Link>)}</nav>
    {view === "overview" && <><div className="boss-summary">{[["Companies", data.cards.length], ["Active brands", data.brands.filter(b => "status" in b && b.status === "ACTIVE").length], ["Active products", data.products.filter(p => "status" in p && p.status === "ACTIVE").length], ["Active projects", data.executive.projects.filter(p => p.status === "ACTIVE").length], ["Open goals", data.executive.goals.filter(g => ["DRAFT", "ACTIVE", "PAUSED", "AT_RISK"].includes(g.status)).length], ["SIA", data.sia.status]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value || "NO DATA"}</strong></div>)}</div>
      <div className="boss-priorities"><section className="executive-band"><header><h2><AlertTriangle size={18} />Attention</h2><Link href={`/app/boss?view=attention${suffix}`}>View all</Link></header>{!attention.length && <Empty />}<ul className="executive-list">{attention.slice(0, 5).map(a => <li key={a.key} className={`signal-${a.severity.toLowerCase()}`}><AlertTriangle size={18} /><div><Link href={a.href}>{a.title}</Link><span className="status">{a.severity}</span><p>{a.explanation}</p><small>{a.nextAction}</small></div></li>)}</ul></section>
      <section className="executive-band"><header><h2>Decisions & My Approvals</h2><Link href={`/app/boss?view=decisions${suffix}`}>View all</Link></header>{!data.executive.decisions.length && <Empty />}<ul className="executive-list">{data.executive.decisions.slice(0, 5).map(d => <li key={d.type + d.id}><div><Link href={d.href}>{d.title}</Link><small>{d.status} / {date(d.dueAt)}</small></div></li>)}</ul></section></div>
      <section className="executive-band"><header><h2>Company Health</h2><Link href={`/app/boss?view=companies${suffix}`}>All companies</Link></header><CompanyCards data={data} /></section>
      <section className="executive-band"><header><h2><Clock size={18} />Important Deadlines</h2><Link href={`/app/boss?view=briefing${suffix}`}>Executive briefing</Link></header>{!data.executive.deadlines.length && <Empty />}<ul className="executive-list">{data.executive.deadlines.slice(0, 6).map(d => <li key={d.type + d.id}><div><Link href={d.href}>{d.title}</Link><small>{date(d.dueAt)}</small></div></li>)}</ul></section>
      <section className="executive-band"><h2>Operational Blockers & Alerts</h2>{!data.executive.briefing.blockedWork.length && !data.executive.operations.EVENT.length && <Empty />}{data.executive.briefing.blockedWork.map(p => <p key={p.id}><Link href={p.href}>{p.title}</Link> / BLOCKED</p>)}{data.executive.operations.EVENT.map(e => <p key={e.id}><Link href={e.href}>{e.title}</Link> / FAILED</p>)}</section></>}
    {view === "companies" && <section className="executive-band"><h2>Companies</h2><CompanyCards data={data} /></section>}
    {view === "brands" && <section className="executive-band"><h2>Brands & Domains</h2>{!data.brands.length && <Empty />}<div className="table-scroll"><table className="business-table"><thead><tr><th>Company</th><th>Brand</th><th>Domain</th><th>Type / Status</th></tr></thead><tbody>{data.brands.map(b => <tr key={b.id}><td>{data.companies.find(c => "organizationId" in b && c.organizationId === b.organizationId)?.legalName ?? "NO DATA"}</td><td>{"name" in b ? String(b.name) : "NO DATA"}</td><td>{"website" in b && b.website ? String(b.website).replace(/^https?:\/\//, "") : "NO DATA"}</td><td>Brand / {"status" in b ? String(b.status) : "NO DATA"}<small>Domain: NOT VERIFIED</small></td></tr>)}</tbody></table></div><Links data={data} /></section>}
    {view === "people" && <section className="executive-band"><h2>People & Memberships</h2><nav className="boss-detail-links">{[["People", "people"], ["Roles", "roles"], ["Permissions", "permissions"], ["Reporting", "reporting"], ["Responsibilities", "responsibilities"], ["Company & project membership", "memberships"]].map(([label, kind]) => <Link key={kind} href={`/app/workforce/${kind}${companyId ? `?organizationId=${encodeURIComponent(companyId)}` : ""}`}>{label}</Link>)}</nav><p>Employees: NO DATA</p>{!data.members.length && <Empty />}<ul className="executive-list">{data.members.slice(0, 50).map(m => <li key={m.id}>{m.name} / {m.projectId ? "Project membership" : "Company/group membership"}</li>)}</ul></section>}
    {view === "graph" && <section className="executive-band"><h2><Network size={18} />Business Graph</h2><Links data={data} /><ul className="boss-graph">{data.graph.organizations.map(o => <li key={o.id}><span className="status">{o.type}</span> {o.name}{o.parentId && <small> / {data.graph.organizations.find(p => p.id === o.parentId)?.name ?? "NO DATA"}</small>}</li>)}</ul><h3>Products</h3>{data.products.map(p => <p key={p.id}>{"name" in p ? String(p.name) : "NO DATA"}</p>)}<h3>Ownership</h3>{!data.graph.ownership.length ? <Empty /> : <Link href="/app/business/ownership">{count(data.graph.ownership)} recorded relationships</Link>}<h3>Relationships</h3>{!data.graph.relationships.length ? <Empty /> : <Link href="/app/business/relationships">{count(data.graph.relationships)} recorded relationships</Link>}</section>}
    {view === "communications" && <section className="executive-band"><h2>Communications</h2><nav className="boss-detail-links">{["threads", "messages", "delivery", "automation", "jobs", "integrations"].map(v => <Link key={v} href={`/app/communications?view=${v}${companyId ? `&organizationId=${encodeURIComponent(companyId)}` : ""}`}>{v[0].toUpperCase() + v.slice(1)}</Link>)}</nav>{!data.integrations.length && <p className="muted">NOT CONFIGURED</p>}{data.integrations.map(i => <p key={i.id}>{i.name} / {i.channel} / {i.status.replaceAll("_", " ")}</p>)}<p>Automation jobs: {count(data.jobs)} / Failed: {count(data.jobs.filter(j => j.status === "FAILED"))}</p></section>}
    {view === "audit" && <section className="executive-band"><h2>Audit & Security</h2><nav className="boss-detail-links"><Link href="/app/operations/activity">Activity</Link><Link href="/app/operations/events">Operational events</Link><Link href="/app/operations/approvals">Approvals</Link><Link href={data.sia.href}>SIA actions & confirmations</Link></nav>{!data.audit.length && <Empty />}<ul className="executive-list">{data.audit.map(a => <li key={a.id}><div><strong>{a.action}</strong><small>{a.result} / {a.entityType} / {date(a.createdAt)}</small></div></li>)}</ul></section>}
    {view === "system" && <section className="executive-band"><h2>System Health</h2><dl className="record-details">{Object.entries({ ...data.system, sia: data.sia.status, integrations: data.integrations.length ? "RECORDED / DELIVERY NOT VERIFIED" : "NOT CONFIGURED", automation: data.jobs.length ? "RECORDED / REVIEW JOB STATUS" : "NO DATA" }).map(([key, status]) => <div key={key}><dt>{key[0].toUpperCase() + key.slice(1)}</dt><dd>{status}</dd></div>)}</dl></section>}
    {view === "operations" && <nav className="boss-detail-links" aria-label="Operational controls">{[["Workflows", "workflows"], ["Instances", "instances"], ["Requests", "requests"], ["Approvals", "approvals"], ["Recurring work", "recurring"], ["Reminders", "reminders"], ["Escalations", "escalations"], ["Control points", "controls"], ["Events", "events"], ["Activity", "activity"], ["My tasks", "my-tasks"]].map(([label, kind]) => <Link key={kind} href={`/app/operations/${kind}?organizationId=${encodeURIComponent(companyId ?? data.groupId)}`}>{label}</Link>)}</nav>}
    {["projects", "goals", "operations", "decisions", "attention", "briefing", "risks", "opportunities", "changes"].includes(view) && <ExecutiveView view={view} query={{ organizationId: companyId ?? data.groupId }} providedData={data.executive} />}
  </div>;
}
