import Link from "next/link";
import { AlertTriangle, ArrowUpRight, Clock, CheckCircle, Filter } from "lucide-react";
import { ZodError } from "zod";
import { requireSession } from "@/server/auth/guards";
import { AccessError } from "@/server/authorization/engine";
import { executiveService } from "@/server/domain/executive-service";
import { ExecutiveAction, ExecutiveEditor, ExecutiveFilterPanel } from "./forms";
type Data = Awaited<ReturnType<typeof executiveService.dashboard>>;
const label = (value: string) => value.replaceAll("_", " ");
const date = (value: Date | string | null | undefined) => value ? new Date(value).toISOString().slice(0, 16).replace("T", " ") + " UTC" : "Not set";
function Empty({ text = "No items" }: { text?: string }) { return <p className="executive-empty">{text}</p>; }
function Sources({ rows, people }: { rows: Data["deadlines"]; people: Data["options"]["people"] }) {
  return rows.length ? <ul className="executive-list">{rows.map(r => <li key={r.type + r.id}><div><Link href={r.href}>{r.title}<ArrowUpRight size={14} /></Link><small>{label(r.status)}{r.dueAt && ` / ${date(r.dueAt)}`} / {people.find(p => p.id === r.ownerPersonId)?.name ?? "Owner not available"}</small></div></li>)}</ul> : <Empty />;
}
function AttentionList({ data, limit }: { data: Data; limit?: number }) {
  const rows = data.attention.filter(a => !["RESOLVED", "DISMISSED"].includes(a.handlingStatus)).slice(0, limit);
  return rows.length ? <ul className="executive-list">{rows.map(a => <li key={a.key} className={`signal-${a.severity.toLowerCase()}`}><AlertTriangle size={18} /><div><Link href={a.href}>{a.title}<ArrowUpRight size={14} /></Link><span className="status">{a.severity} / {label(a.handlingStatus)}</span><p>{a.explanation}</p><small>{data.options.people.find(p => p.id === a.ownerPersonId)?.name ?? "Owner not available"}{a.dueAt && ` / ${date(a.dueAt)}`}</small><p>{a.nextAction}</p>
    {(data.capabilities["attention.manage"].organizations.includes(a.organizationId) || !!a.projectId && data.capabilities["attention.manage"].projects.includes(a.projectId)) && <ExecutiveAction><input type="hidden" name="action" value="attention" /><input type="hidden" name="sourceKey" value={a.key} /><input type="hidden" name="version" value={a.version} /><label>Handling<select name="status" defaultValue="ACKNOWLEDGED">{["ACKNOWLEDGED", "IN_PROGRESS", "RESOLVED", "DISMISSED"].map(s => <option key={s}>{s}</option>)}</select></label><label>Reason<input name="reason" required maxLength={4000} /></label></ExecutiveAction>}
  </div></li>)}</ul> : <Empty text="No active attention in this scope" />;
}
function Changes({ data, limit }: { data: Data; limit?: number }) { return data.changes.length ? <ul className="executive-list">{data.changes.slice(0, limit).map(c => <li key={c.id}><div><Link href={c.href}>{c.title}<ArrowUpRight size={14} /></Link><small>{date(c.createdAt)}</small></div></li>)}</ul> : <Empty text="No meaningful changes in this period" />; }
function CompanyHealth({ data }: { data: Data }) { return data.companies.length ? <div className="table-scroll"><table className="business-table"><thead><tr><th>Company</th><th>Health</th><th>Active projects</th><th>Blocked</th><th>Overdue tasks</th><th>Goal concerns</th></tr></thead><tbody>{data.companies.map(c => <tr key={c.id}><td><Link href={`/app/executive?organizationId=${c.id}`}>{c.name}</Link><small>{c.coverage}</small></td><td>{label(c.health)}<small>{c.reasons.join("; ") || "No concerns in available signals"}</small></td>{["Active projects", "Blocked projects", "Overdue tasks", "Goal concerns"].map(n => <td key={n}>{c.metrics.find(m => m.name === n)?.value ?? "NO DATA"}</td>)}</tr>)}</tbody></table></div> : <Empty text="No authorized company comparison" />; }
function Records({ data, kind }: { data: Data; kind: string }) {
  const rows = data.records.filter(r => r.kind === kind), key = kind.toLowerCase() + ".manage", scopes = data.capabilities[key];
  const states: Record<string, Record<string, string[]>> = {
    DECISION: { DRAFT: ["PENDING", "CANCELLED"], PENDING: ["APPROVED", "REJECTED", "DEFERRED", "CANCELLED"], DEFERRED: ["PENDING", "CANCELLED"], APPROVED: ["COMPLETED"] },
    RISK: { IDENTIFIED: ["MONITORING", "MITIGATING", "REALIZED", "CLOSED", "ACCEPTED"], MONITORING: ["MITIGATING", "REALIZED", "CLOSED", "ACCEPTED"], MITIGATING: ["MONITORING", "REALIZED", "CLOSED", "ACCEPTED"], REALIZED: ["MITIGATING", "CLOSED"], ACCEPTED: ["MONITORING", "CLOSED"], CLOSED: ["MONITORING"] },
    OPPORTUNITY: { IDENTIFIED: ["EVALUATING", "CLOSED"], EVALUATING: ["PURSUING", "CLOSED"], PURSUING: ["REALIZED", "CLOSED"], CLOSED: ["EVALUATING"] }
  };
  return <>{(scopes.organizations.length > 0 || scopes.projects.length > 0) && <ExecutiveEditor kind={kind} organizations={data.options.organizations.filter(o => scopes.organizations.includes(o.id) || data.options.projects.some(p => p.organizationId === o.id && scopes.projects.includes(p.id)))} organizationGrants={scopes.organizations} projects={data.options.projects.filter(p => scopes.organizations.includes(p.organizationId) || scopes.projects.includes(p.id))} people={data.options.people} />}
    {!rows.length && <Empty />}{rows.map(r => {
      const allowedStates = (states[kind]?.[r.status] ?? (kind === "KPI" ? ["OBSERVE"] : [])).filter(s => ["APPROVED", "REJECTED", "DEFERRED"].includes(s) ? r.canDecide : r.canManage);
      return <article className="executive-record" key={r.id}><header><h3>{r.title}</h3><span className="status">{label(r.status)}</span></header><p>{r.payload.description}</p><dl className="record-details"><div><dt>Owner / decision maker</dt><dd>{data.options.people.find(p => p.id === r.ownerPersonId)?.name ?? "Not available"}</dd></div><div><dt>Needed by</dt><dd>{date(r.dueAt)}</dd></div>
        {r.payload.impact && <div><dt>Impact</dt><dd>{r.payload.impact}</dd></div>}{r.payload.options?.length > 0 && <div><dt>Options</dt><dd>{r.payload.options.join("; ")}</dd></div>}{r.payload.recommendedAction && <div><dt>Human recommendation</dt><dd>{r.payload.recommendedAction}</dd></div>}
        {kind === "KPI" && <><div><dt>Target / actual</dt><dd>{r.payload.target} / {r.actual ?? "NO DATA"} {r.payload.unit}</dd></div><div><dt>Trend</dt><dd>{label(r.trend)}</dd></div><div><dt>Period</dt><dd>{date(r.payload.periodStart)} to {date(r.payload.periodEnd)}</dd></div><div><dt>Calculation</dt><dd>{r.payload.direction === "LOWER" ? "Lower" : "Higher"} is preferred; within 10% of target is at risk</dd></div></>}
        {kind === "RISK" && <><div><dt>Severity / probability</dt><dd>{r.payload.severity} / {r.payload.probability ?? "Unknown"}</dd></div><div><dt>Mitigation</dt><dd>{r.payload.mitigation ?? "Not set"}</dd></div></>}
        {r.payload.source && <div><dt>Source</dt><dd>{r.payload.source}</dd></div>}{r.payload.nextAction && <div><dt>Next action</dt><dd>{r.payload.nextAction}</dd></div>}
      </dl>{allowedStates.length > 0 && <ExecutiveAction><input type="hidden" name="action" value="transition" /><input type="hidden" name="recordId" value={r.id} /><input type="hidden" name="version" value={r.version} /><label>Action<select name="status">{allowedStates.map(s => <option key={s}>{s}</option>)}</select></label>{kind === "KPI" && <label>Actual<input name="observation" type="number" step="any" required /></label>}<label>Reason / source evidence<input name="reason" required maxLength={4000} /></label></ExecutiveAction>}
      {r.canManage && kind !== "KPI" && (kind !== "DECISION" || r.status === "DRAFT") && !["CLOSED", "REALIZED", "ACCEPTED"].includes(r.status) && <details><summary>Edit context</summary><ExecutiveAction><input type="hidden" name="action" value="revise" /><input type="hidden" name="recordId" value={r.id} /><input type="hidden" name="version" value={r.version} /><label>Title<input name="title" defaultValue={r.title} required /></label><label>Description<textarea name="description" defaultValue={r.payload.description} required /></label>{r.payload.impact && <label>Impact<textarea name="impact" defaultValue={r.payload.impact} required /></label>}{kind === "RISK" && <><label>Severity<select name="severity" defaultValue={r.payload.severity}>{["LOW", "MEDIUM", "HIGH", "CRITICAL"].map(s => <option key={s}>{s}</option>)}</select></label><label>Probability<input name="probability" type="number" min={0} max={1} step={0.01} defaultValue={r.payload.probability ?? ""} /></label><label>Mitigation<textarea name="mitigation" defaultValue={r.payload.mitigation} /></label></>}{kind === "OPPORTUNITY" && <label>Next action<textarea name="nextAction" defaultValue={r.payload.nextAction} required /></label>}<label>Reason<input name="reason" required /></label></ExecutiveAction></details>}
      <details><summary>History ({r.history.length})</summary><ol className="executive-history">{r.history.map(h => <li key={h.id}><strong>{label(h.toStatus)}</strong> / {date(h.createdAt)}<p>{h.reason}{h.observation !== null && ` / actual ${h.observation}`}</p><small>Actor: {h.actorUserId}</small></li>)}</ol></details></article>;
    })}</>;
}
export async function ExecutiveView({ view, query, providedData }: { view: string; query: Record<string, string | string[] | undefined>; providedData?: Data }) {
  const session = await requireSession(); let data: Data;
  const filter = Object.fromEntries(["organizationId", "projectId", "productId", "from", "until", "severity", "status"].flatMap(k => typeof query[k] === "string" && query[k] ? [[k, query[k]]] : []));
  if (typeof filter.until === "string" && /^\d{4}-\d{2}-\d{2}$/.test(filter.until)) filter.until += "T23:59:59.999Z";
  try { data = providedData ?? await executiveService.dashboard(session.userId, filter); } catch (e) { if (!(e instanceof AccessError || e instanceof ZodError)) throw e; return <section className="business-empty"><h2>Executive view unavailable</h2><p>Check your authorized scope and filter values.</p><Link href="/app/executive">Reset filters</Link></section>; }
  const overview = view === "overview" || view === "briefing", people = data.options.people;
  return <div className="executive-view"><div className="executive-freshness"><Clock size={14} /><span>Calculated {date(data.calculatedAt)} / Updated {date(data.lastUpdated)}</span><span>{date(data.sourcePeriod.from)} to {date(data.sourcePeriod.until)}</span></div>
    <ExecutiveFilterPanel><form className="executive-filters" method="get"><label>Scope<select name="organizationId" defaultValue={String(filter.organizationId ?? "")}><option value="">All authorized scopes</option>{data.options.organizations.map(o => <option key={o.id} value={o.id}>{o.name} ({o.type.toLowerCase()})</option>)}</select></label><label>Project<select name="projectId" defaultValue={String(filter.projectId ?? "")}><option value="">All</option>{data.options.projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Product<select name="productId" defaultValue={String(filter.productId ?? "")}><option value="">All</option>{data.options.products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>From (UTC)<input type="date" name="from" defaultValue={String(filter.from ?? "").slice(0, 10)} /></label><label>Until (UTC)<input type="date" name="until" defaultValue={String(filter.until ?? "").slice(0, 10)} /></label><label>Severity<select name="severity" defaultValue={String(filter.severity ?? "")}><option value="">All</option>{["LOW", "MEDIUM", "HIGH", "CRITICAL"].map(s => <option key={s}>{s}</option>)}</select></label><label>Status<select name="status" defaultValue={String(filter.status ?? "")}><option value="">All</option>{["NEW", "ACKNOWLEDGED", "IN_PROGRESS", "RESOLVED", "DISMISSED", "DRAFT", "PENDING", "APPROVED", "REJECTED", "DEFERRED", "CANCELLED", "COMPLETED", "ON_TRACK", "AT_RISK", "OFF_TRACK", "NO_DATA", "IDENTIFIED", "MONITORING", "MITIGATING", "REALIZED", "CLOSED", "ACCEPTED", "EVALUATING", "PURSUING"].map(s => <option key={s}>{s}</option>)}</select></label><button className="icon-button" title="Apply filters" aria-label="Apply filters"><Filter size={18} /></button></form></ExecutiveFilterPanel>
    {overview && <p className="executive-date">TODAY / {data.briefing.date} UTC</p>}
    <div className={overview ? "executive-priorities" : ""}>
    {(overview || view === "attention") && <section className="executive-band"><header><h2>Attention</h2><Link href="/app/executive/attention">All attention</Link></header><AttentionList data={data} limit={overview ? 5 : undefined} />{view === "attention" && <details><summary>Handled signals</summary>{data.records.filter(r => r.kind === "ATTENTION").map(r => <p key={r.id}>{r.title} / {label(r.status)} / {r.history.at(-1)?.reason}</p>)}</details>}</section>}
    {(overview || view === "decisions") && <section className="executive-band"><header><h2>Decisions</h2><Link href="/app/operations/approvals">My approvals</Link></header><Sources rows={data.decisions.filter(r => r.type === "APPROVAL")} people={people} />{overview ? <Sources rows={data.decisions.filter(r => r.type === "DECISION").slice(0, 5)} people={people} /> : <Records data={data} kind="DECISION" />}</section>}
    {(overview || view === "changes") && <section className="executive-band"><header><h2>What Changed?</h2><Link href="/app/executive/changes">Period changes</Link></header><Changes data={view === "briefing" ? { ...data, changes: data.briefing.changes } : data} limit={overview ? 5 : undefined} /></section>}
    {overview && <section className="executive-band"><header><h2>Upcoming Deadlines</h2><Clock size={18} /></header><Sources rows={data.deadlines.slice(0, 6)} people={people} /></section>}
    </div>
    {(overview || view === "companies") && <section className="executive-band"><h2>Company Health</h2><CompanyHealth data={data} /></section>}
    {(overview || view === "projects") && <section className="executive-band"><h2>Projects</h2>{!data.projects.length && <Empty />}{data.projects.slice(0, overview ? 5 : undefined).map(p => <article className="executive-record" key={p.id}><header><Link href={p.href}>{p.title}<ArrowUpRight size={14} /></Link><span className="status">{label(p.health)}</span></header><p>{p.reasons.join("; ") || "No concerns in available signals"}</p><p>Progress: {p.progress === null ? "NO DATA" : `${p.progress.toFixed(1)}%`}</p>{!overview && <details><summary>Work, dependencies and approvals</summary><Sources rows={[...p.tasks, ...p.blockers, ...p.milestones, ...p.approvals]} people={people} /><p>{p.dependencies.length} authorized dependency records</p><ul>{p.changes.map(c => <li key={c.id}>{c.title} / {date(c.createdAt)}</li>)}</ul></details>}</article>)}</section>}
    {(overview || view === "goals") && <section className="executive-band"><h2>Goals</h2>{!data.goals.length && <Empty />}{data.goals.slice(0, overview ? 5 : undefined).map(g => <article className="executive-record" key={g.id}><header><Link href={g.href}>{g.title}<ArrowUpRight size={14} /></Link><span className="status">{label(g.status)}</span></header><p>Progress: {g.progress === null ? "NO DATA" : `${g.progress.toFixed(1)}%`} / Target: {date(g.dueAt)} / {label(g.trend)}</p>{!overview && <Sources rows={[...g.supportingProjects, ...g.blockers, ...g.overdueDependencies]} people={people} />}</article>)}</section>}
    {(overview || view === "operations" || view === "metrics") && <section className="executive-band"><h2>{view === "metrics" ? "Metrics" : "Operations"}</h2><div className="executive-metrics">{data.metrics.map(m => <div key={m.name}><strong>{m.value ?? "NO DATA"}</strong><span>{m.name}</span><details><summary>Source &amp; calculation</summary><p>{m.definition} / {m.source} / {m.period}</p><small>{m.coverage.replaceAll("_", " ")} / {date(m.lastUpdated)}</small><ul>{m.entities.map(e => <li key={e.id}><Link href={e.href}>{e.title}</Link></li>)}</ul></details></div>)}</div>{view === "operations" && Object.entries(data.operations).map(([type, rows]) => <details key={type}><summary>{label(type)}</summary><Sources rows={rows} people={people} /></details>)}</section>}
    {view === "kpis" && <section className="executive-band"><h2>KPIs</h2><Records data={data} kind="KPI" /></section>}
    {view === "risks" && <section className="executive-band"><h2>Risks</h2><Records data={data} kind="RISK" /></section>}
    {view === "opportunities" && <section className="executive-band"><h2>Opportunities</h2><Records data={data} kind="OPPORTUNITY" /></section>}
    {overview && <section className="executive-band"><header><h2>Recent Wins</h2><CheckCircle size={18} /></header><Sources rows={data.wins.slice(0, 5)} people={people} /></section>}
  </div>;
}
