export const airaRoleNames = [
  "Founder",
  "Chief Executive Officer",
  "Director",
  "Division Head",
  "State Head",
  "District Head",
  "Hub Manager",
  "Centre Manager",
  "Department Head",
  "Operations Manager",
  "Operations Executive",
  "Human Resources Manager",
  "Human Resources Executive",
  "Admission Cell Head",
  "Admission Officer",
  "CRM Manager",
  "Business Development Manager",
  "Business Development Executive",
  "Sales Manager",
  "Sales Executive",
  "Telecaller",
  "Senior Counsellor",
  "Counsellor",
  "Academic Head",
  "Academic Coordinator",
  "Senior Academic Advisor",
  "Junior Academic Advisor",
  "Lead Trainer",
  "Trainer",
  "Mentor",
  "Finance Manager",
  "Finance Executive",
  "Compliance Officer",
  "Auditor",
  "AIRA Labs Head",
  "Product Manager",
  "Product Owner",
  "Technical Lead",
  "Software Developer",
  "UI/UX Designer",
  "Quality Assurance Executive",
  "AIRA Skill Studio Head",
  "Skill Studio Coordinator",
  "AIRA Career Hub Head",
  "Nice Jobs Manager",
  "Employer Relations Manager",
  "Placement Officer",
  "Career Advisor",
  "Marketing Manager",
  "Marketing Executive",
  "Communications Manager",
  "Communications Executive",
  "Technology Head",
  "Platform Administrator",
  "System Administrator",
  "Employee",
  "Student",
  "Entrepreneur",
  "Client",
  "SIA — Virtual CEO"
] as const;
export const canonicalAiraRoles = airaRoleNames.map((name, index) => ({ key: "aira-" + String(index + 1).padStart(2, "0"), name, canonical: true, system: true, principalType: index === 59 ? "AGENT" : "HUMAN", category: index === 59 ? "AI executive agent" : "Designation" }));

