import { randomUUID } from "node:crypto";
import { ShieldCheck, Bot } from "lucide-react";
import { requireSession } from "@/server/auth/guards";
import { siaService } from "@/server/sia/service";
import { memoryCategories } from "@/server/sia/input";
import { Composer, MutationForm, Response } from "./forms";
export default async function SiaPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const session = await requireSession(), query = await searchParams;
  const get = (k: string) => typeof query[k] === "string" ? query[k] as string : "";
  const base = await siaService.workspace(session.userId);
  const siaId = get("siaId") || base.identities[0]?.id;
  const target = get("scope") || base.organizations[0]?.id || (base.projects[0] ? "project:" + base.projects[0].id : "");
  const project = target.startsWith("project:") ? base.projects.find(p => p.id === target.slice(8)) : null;
  const selected = siaId && target ? { siaId, organizationId: project?.organizationId ?? target, ...(project ? { projectId: project.id } : {}) } : null;
  let workspace: Awaited<ReturnType<typeof siaService.workspace>> = base, error = "";
  if (selected) try { workspace = await siaService.workspace(session.userId, selected); } catch { error = "Selected context is unavailable or not authorized."; }
  const c = workspace.current;
  const view = ["conversation", "briefing", "attention", "decisions", "actions", "memory", "tools", "context", "activity"].includes(get("view")) ? get("view") : "conversation";
  let evidence: Awaited<ReturnType<typeof siaService.preview>> | null = null, evidenceError = "";
  if (c && ["briefing", "attention", "decisions"].includes(view)) try { evidence = await siaService.preview(session.userId, c.selection, view === "briefing" ? "prepare_report" : view === "attention" ? "get_attention_items" : "get_pending_decisions"); } catch { evidenceError = "Current evidence is unavailable. Check SIA's scoped capabilities and enabled tools."; }
  const href = (v: string) => "/app/sia?" + new URLSearchParams({ siaId: siaId ?? "", scope: target, view: v });
  return <div className="sia-view"><header className="sia-heading"><div><p className="eyebrow">MAXPASE GROUP VIRTUAL CEO</p><h1><Bot size={28}/> SIA</h1></div><span className="badge">Deterministic development</span></header>
    <p className="sia-safety"><ShieldCheck size={17}/> High-impact autonomous execution is disabled.</p>
    <form method="get" className="sia-selector"><label>SIA identity<select name="siaId" defaultValue={siaId}>{base.identities.map(i => <option key={i.id} value={i.id}>{i.name} / {i.status}</option>)}</select></label><label>Business context<select name="scope" defaultValue={target}>{base.organizations.map(o => <option value={o.id} key={o.id}>{o.name} / {o.type}</option>)}{base.projects.map(p => <option value={"project:" + p.id} key={p.id}>{p.name} / PROJECT</option>)}</select></label><input name="view" type="hidden" value={view}/><button className="button secondary">Open context</button></form>
    {error && <p className="form-error" role="alert">{error}</p>}
    {!c ? <p className="muted">No authorized SIA context is available.</p> : <><nav className="sia-tabs" aria-label="SIA views">{["conversation", "briefing", "attention", "decisions", "actions", "memory", "tools", "context", "activity"].map(v => <Link key={v} href={href(v)} aria-current={v === view ? "page" : undefined}>{v[0].toUpperCase() + v.slice(1)}</Link>)}</nav>
    {view === "conversation" && <><Composer selection={c.selection} requestKey={randomUUID()}/><div className="sia-source-links"><Link href="/app/executive/briefing">Executive briefing</Link><Link href="/app/executive/attention">Attention</Link><Link href="/app/executive/decisions">Human decisions</Link></div></>}
    {["briefing", "attention", "decisions"].includes(view) && <>{evidenceError && <p className="form-error" role="alert">{evidenceError}</p>}{evidence && <Response response={evidence}/>}</>}
    {view === "actions" && <><section><h2>Task proposal</h2><MutationForm selection={c.selection} mode="proposal" label="Prepare approval request" icon="plus"><input type="hidden" name="idempotencyKey" value={randomUUID()}/><label>Task title<input name="title" maxLength={200} required/></label><label>Description<textarea name="description" maxLength={4000}/></label><label>Reason<textarea name="reason" maxLength={1000} required/></label><div className="sia-fields"><label>Due date (UTC)<input type="date" name="dueDate"/></label><label>Priority<select name="priority" defaultValue="NORMAL">{["LOW", "NORMAL", "HIGH", "CRITICAL"].map(v => <option key={v}>{v}</option>)}</select></label></div><label>Independent approval policy<select name="controlPointId" required><option value="">Select policy</option>{c.policies.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label></MutationForm></section>
      <section><h2>Actions</h2>{!c.actions.length && <p className="muted">No proposals in this context.</p>}{c.actions.map(a => <article className="sia-action" key={a.id}><h3>{a.parameters.title}</h3><dl className="sia-facts"><div><dt>What</dt><dd>Create one task</dd></div><div><dt>Why</dt><dd>{a.reason}</dd></div><div><dt>Target</dt><dd>{c.selection.projectId ? "Selected project" : "Selected organization"}</dd></div><div><dt>Scope</dt><dd>{project?.name ?? base.organizations.find(o => o.id === target)?.name ?? "Selected authorized context"}</dd></div><div><dt>Risk</dt><dd>{a.risk}</dd></div><div><dt>Approval</dt><dd>Required / {a.approvalStatus}</dd></div><div><dt>Execution</dt><dd>{a.status} / {a.verificationStatus}</dd></div><div><dt>Next</dt><dd>{a.approvalStatus === "APPROVED" ? "Explicit confirmation, current authorization, controlled execution and verification" : "Submit the draft and obtain independent human decisions"}</dd></div></dl>{a.requestId && <Link href="/app/operations/requests">Open approval request</Link>}{a.status === "APPROVAL_REQUIRED" && a.approvalStatus === "APPROVED" && <MutationForm selection={c.selection} mode="execute" label="Create approved task" icon="shield"><input type="hidden" name="id" value={a.id}/><input type="hidden" name="version" value={a.version}/><label className="sia-check"><input type="checkbox" name="confirmed" required/>Confirm this approved task creation</label></MutationForm>}{a.resultId && <Link href="/app/execution/tasks">View created task</Link>}</article>)}</section></>}
    {view === "memory" && <><section><h2>Memory</h2>{c.canManageMemory && <MutationForm selection={c.selection} mode="memory" label="Create draft" icon="plus"><label>Reference key<input name="key" pattern="[a-z][a-z0-9_.-]{2,99}" required/></label><label>Category<select name="category">{memoryCategories.map(v => <option key={v}>{v}</option>)}</select></label><label>Context<textarea name="value" maxLength={4000} required/></label><div className="sia-fields"><label>Source<select name="sourceType">{["HUMAN_ATTESTATION", "ORGANIZATION", "PROJECT", "TASK", "GOAL", "REQUEST", "APPROVAL", "DECISION"].map(v => <option key={v}>{v}</option>)}</select></label><label>Source ID<input name="sourceId"/></label></div><div className="sia-fields"><label>Confidence<input name="confidence" type="number" min="0" max="1" step="0.01"/></label><label>Review (UTC)<input name="reviewAt" type="date"/></label><label>Expiry (UTC)<input name="expiresAt" type="date"/></label></div></MutationForm>}{!c.memories.length && <p className="muted">No structured memory in this context.</p>}{c.memories.map(m => <article className="sia-action" key={m.id}><h3>{m.key}</h3><p>{m.value}</p><p className="muted">{m.category} / {m.status} / {m.sourceType} {m.sourceId ?? ""}</p>{c.canManageMemory && m.status !== "ARCHIVED" && <MutationForm selection={c.selection} mode="review" label="Record review" icon="check"><input type="hidden" name="id" value={m.id}/><input type="hidden" name="version" value={m.version}/><label>Decision<select name="status">{m.status === "DRAFT" && <option value="APPROVED">Approve as context</option>}<option value="ARCHIVED">Archive</option></select></label></MutationForm>}</article>)}</section></>}
    {view === "tools" && <section><h2>Controlled tools</h2><div className="table-wrap"><table><thead><tr><th>Tool</th><th>Risk</th><th>Access</th><th>Enabled</th></tr></thead><tbody>{c.tools.map(t => <tr key={t.key}><td>{t.name}<small>{t.permission}</small></td><td>{t.risk}{t.approvalRequired && <small>Independent approval required</small>}</td><td>{t.available ? "Authorized" : "Unavailable"}</td><td>{c.canConfigure ? <MutationForm selection={c.selection} mode="tool" label="Save"><input type="hidden" name="toolKey" value={t.key}/><label className="sia-check"><input type="checkbox" name="enabled" defaultChecked={t.enabled}/>Enabled</label></MutationForm> : t.enabled ? "Yes" : "No"}</td></tr>)}</tbody></table></div></section>}
    {view === "context" && <section><h2>Executive configuration</h2><p>{c.identity.name} / {c.identity.title} / {c.identity.status}</p>{c.canConfigure ? <MutationForm selection={c.selection} mode="configuration"><input type="hidden" name="version" value={c.identity.configurationVersion}/><label>Name<input name="name" defaultValue={c.identity.configuration.name} required/></label><label>Role<input name="role" defaultValue={c.identity.configuration.role} required/></label><div className="sia-fields"><label>Communication<select name="communicationStyle" defaultValue={c.identity.configuration.communicationStyle}>{["CONCISE", "BALANCED", "DETAILED"].map(v => <option key={v}>{v}</option>)}</select></label><label>Tone<select name="executiveTone" defaultValue={c.identity.configuration.executiveTone}>{["DIRECT", "COLLABORATIVE", "FORMAL"].map(v => <option key={v}>{v}</option>)}</select></label></div><label>Response preferences<textarea name="responsePreferences" defaultValue={c.identity.configuration.responsePreferences.join("\n")}/></label><label>Decision principles<textarea name="decisionPrinciples" defaultValue={c.identity.configuration.decisionPrinciples.join("\n")}/></label><label>Operating principles<textarea name="operatingPrinciples" defaultValue={c.identity.configuration.operatingPrinciples.join("\n")}/></label></MutationForm> : <p className="muted">{c.identity.configuration.communicationStyle} / {c.identity.configuration.executiveTone}</p>}</section>}
    {view === "activity" && <section><h2>Recent SIA requests</h2>{!c.runs.length && <p className="muted">No SIA requests in this context.</p>}{c.runs.map(r => <div className="sia-row" key={r.id}><div><strong>{r.toolKey?.replaceAll("_", " ") ?? "Executive request"}</strong><small>{r.createdAt.toISOString()} UTC</small></div><span className="badge">{r.status}</span></div>)}</section>}
    </>}
  </div>;
}
import Link from "next/link";
