"use client";
import Link from "next/link";
import { useActionState, useState } from "react";
import { Plus, Pencil, Save, X, Inbox, Check, MailOpen, Play } from "lucide-react";
import type { airaService } from "@/server/domain/aira-service";
import type { CompanyKind } from "@/server/domain/company-input";
import { programStatuses, batchStatuses, locationStatuses } from "@/server/domain/company-input";
import { saveAira } from "./actions";
import { companyLabels } from "./labels";
import { ActionForm } from "../operations/operations-manager";
type Workspace = Awaited<ReturnType<typeof airaService.workspace>>;
type Row = { id: string; [key: string]: unknown };
type Field = { key: string; label: string; source?: string; values?: readonly string[]; type?: string; required?: boolean };
const name: Field = { key: "name", label: "Name", required: true }, slug: Field = { key: "slug", label: "Reference", required: true }, description: Field = { key: "description", label: "Description", type: "textarea" }, org: Field = { key: "organizationId", label: "Organization", source: "organizations", required: true };
const status = (values: readonly string[]): Field => ({ key: "status", label: "Status", values });
const life = ["ACTIVE", "INACTIVE", "ARCHIVED"];
const ref = (key: string, label: string, source: string, required = false): Field => ({ key, label, source, required });
const program = ref("programId", "Program", "programs");
const fields: Partial<Record<CompanyKind, Field[]>> = {
  programs: [org, name, slug, description, { key: "kind", label: "Offering", values: ["PROGRAM", "SERVICE"] }, status(programStatuses), { key: "durationDays", label: "Duration (days)", type: "number" }, { key: "capacity", label: "Capacity", type: "number" }, { key: "priceMinor", label: "Price (minor units)", type: "number" }, { key: "currency", label: "Currency code" }, ref("productId", "Product / service", "products"), ref("brandId", "Brand", "brands")],
  batches: [{ ...program, required: true }, name, status(batchStatuses), { key: "startDate", label: "Start date (UTC)", type: "date" }, { key: "endDate", label: "End date (UTC)", type: "date" }, { key: "capacity", label: "Capacity", type: "number" }, ref("locationId", "Location", "locations")],
  locations: [org, name, { key: "type", label: "Type", values: ["CAMPUS", "DISTRICT_HUB", "COMMUNITY_CENTRE", "ONLINE", "OTHER"] }, status(locationStatuses), { key: "address", label: "Address", type: "textarea" }, { key: "city", label: "City" }, { key: "region", label: "Region" }, { key: "country", label: "Country" }, { key: "postalCode", label: "Postal code" }],
  divisions: [ref("parentId", "Parent", "organizations", true), name, slug, { key: "type", label: "Type", values: ["DIVISION", "BUSINESS_UNIT"] }, description, status(life)],
  departments: [ref("parentId", "Parent", "organizations", true), name, slug, { key: "type", label: "Type", values: ["DEPARTMENT"] }, description, status(life)],
  teams: [ref("parentId", "Parent", "organizations", true), name, slug, { key: "type", label: "Type", values: ["TEAM"] }, description, status(life)],
  products: [org, name, slug, description, ref("divisionId", "Division", "divisions"), ref("brandId", "Brand", "brands"), { key: "type", label: "Type", values: ["PRODUCT", "SERVICE", "PLATFORM"] }, { key: "lifecycle", label: "Lifecycle", values: ["CONCEPT", "DEVELOPMENT", "LIVE", "RETIRED"] }, status(life)],
  projects: [org, name, slug, description, program, status(["PLANNED", "ACTIVE", "PAUSED", "BLOCKED", "COMPLETED", "CANCELLED", "ARCHIVED"]), ref("ownerPersonId", "Owner", "people"), ref("accountablePersonId", "Accountable person", "people"), { key: "targetDate", label: "Target date (UTC)", type: "date" }],
  goals: [org, { key: "title", label: "Objective", required: true }, description, program, ref("projectId", "Project", "projects"), status(["DRAFT", "ACTIVE", "PAUSED", "AT_RISK", "ACHIEVED", "MISSED", "CANCELLED", "ARCHIVED"]), ref("ownerPersonId", "Owner", "people"), ref("accountablePersonId", "Accountable person", "people"), { key: "targetDate", label: "Target date (UTC)", type: "date" }],
  responsibilities: [org, ref("personId", "Person", "people", true), { key: "title", label: "Responsibility", required: true }, { key: "kind", label: "Kind", values: ["RESPONSIBLE", "OWNER", "ACCOUNTABLE", "ACADEMIC", "OPERATIONS", "MANAGER", "TRAINER", "MENTOR"] }, program, ref("batchId", "Batch", "batches"), ref("locationId", "Location", "locations"), ref("projectId", "Project", "projects"), ref("productId", "Product", "products"), ref("goalId", "Goal", "goals"), ref("teamId", "Responsible team", "teams"), status(life)],
  participants: [ref("batchId", "Batch", "batches", true), ref("personId", "Person", "people", true), status(["PLANNED", "ACTIVE", "COMPLETED", "WITHDRAWN"])]
};
const manageKeys: Partial<Record<CompanyKind, string>> = { divisions: "organization.manage", departments: "organization.manage", teams: "organization.manage", programs: "program.manage", batches: "batch.manage", participants: "batch.manage", locations: "location.manage", products: "product.manage", projects: "project.manage", goals: "goal.manage", responsibilities: "responsibility.manage" };
const label = (v: unknown) => typeof v === "string" || typeof v === "number" ? String(v).replaceAll("_", " ") : "";
export function CompanyManager({ kind, rows, workspace: w }: { kind: CompanyKind; rows: Row[]; workspace: Workspace }) {
  const [editing, setEditing] = useState<Row | null | undefined>(undefined);
  const key = manageKeys[kind], canManage = !!key && !!w.capabilities[key]?.length;
  const names = new Map([...w.organizations, ...w.programs, ...w.batches, ...w.locations, ...w.products, ...w.projects, ...w.goals.map(g => ({ id: g.id, name: g.title })), ...w.people.map(p => ({ id: p.id, name: p.displayName }))].map(o => [o.id, o.name]));
  const who = (id: unknown) => typeof id === "string" ? names.get(id) ?? "" : "";
  return <><div className="view-heading"><h2>{companyLabels[kind]}</h2>{canManage && fields[kind] && <button className="button" onClick={() => setEditing(editing === undefined ? null : undefined)}><Plus size={16}/>{editing === undefined ? "New" : "Close"}</button>}</div>
    {kind === "programs" && <nav className="company-division-tabs" aria-label="Program divisions"><Link href="/app/aira/programs">All</Link>{w.organizations.filter(o => o.type === "DIVISION").map(d => <Link key={d.id} href={`/app/aira/programs?divisionId=${d.id}`}>{d.name}</Link>)}</nav>}
    {kind === "employers" && <Link href="/app/business/relationships">Company relationships</Link>}
    {kind === "workflows" && <Link href={`/app/operations/workflows?organizationId=${w.company.id}`}>Manage workflows</Link>}
    {kind === "instances" && <Link href="/app/operations/instances">Manage workflow runs</Link>}
    {kind === "requests" && <Link href={`/app/operations/requests?organizationId=${w.company.id}`}>Create request</Link>}
    {editing !== undefined && <Editor key={editing?.id ?? "new"} kind={kind} workspace={w} initial={editing} close={() => setEditing(undefined)}/>}
    {!rows.length ? <div className="business-empty"><Inbox size={24}/><h3>No records</h3></div> : <div className="table-scroll"><table className="business-table operations-table"><thead><tr><th>Name</th><th>Status</th><th>Relationships</th><th>Schedule / Configuration</th><th>Actions</th></tr></thead><tbody>{rows.map(r => <tr key={r.id}><td>{label(r.name ?? r.title ?? r.displayName ?? r.relationship)}{r.description ? <small>{label(r.description)}</small> : null}{r.message ? <small>{label(r.message)}</small> : null}</td><td><span className="status">{kind === "notifications" ? r.readAt ? "READ" : "UNREAD" : label(r.status)}</span>{r.kind ? <small>{label(r.kind)}</small> : null}{r.lifecycle ? <small>{label(r.lifecycle)}</small> : null}</td><td>{who(r.organizationId)}{["divisionId", "programId", "locationId", "batchId", "productId", "projectId", "teamId"].map(k => who(r[k]) ? <small key={k}>{who(r[k])}</small> : null)}{r.programName ? <small>{label(r.programName)}</small> : null}{r.personId ? <small>{who(r.personId)}</small> : null}</td><td>{["startDate", "endDate", "targetDate"].map(k => r[k] ? <small key={k}>{k === "startDate" ? "Start" : k === "endDate" ? "End" : "Target"}: {String(r[k]).slice(0,10)} UTC</small> : null)}{r.capacity != null && <small>Capacity: {label(r.capacity)}</small>}{r.durationDays != null && <small>{label(r.durationDays)} days</small>}{kind === "programs" && <small>{r.priceMinor == null ? "Price not configured" : `${label(r.priceMinor)} ${label(r.currency)} minor units`}</small>}</td><td><div className="row-actions">{canManage && fields[kind] && (w.capabilities[key!].includes(String(r.organizationId)) || kind === "divisions" || kind === "departments" || kind === "teams") && <button className="icon-button" title="Edit" aria-label="Edit" onClick={() => setEditing(r)}><Pencil size={16}/></button>}{kind === "projects" && <Link href={`/app/execution/projects/${r.id}`}>Open</Link>}{kind === "goals" && <Link href={`/app/execution/goals?organizationId=${r.organizationId}`}>Progress</Link>}{kind === "approvals" && r.actionable ? <ActionForm operation="decision" id={r.id}><label>Comment<input name="reason" required maxLength={4000}/></label><button name="decision" value="APPROVED" className="icon-button" title="Approve" aria-label="Approve"><Check size={16}/></button><button name="decision" value="REJECTED" className="icon-button" title="Reject" aria-label="Reject"><X size={16}/></button></ActionForm> : null}{kind === "notifications" && <ActionForm operation="read" id={r.id}><button name="read" value={r.readAt ? "false" : "true"} className="icon-button" title={r.readAt ? "Mark unread" : "Mark read"} aria-label={r.readAt ? "Mark unread" : "Mark read"}><MailOpen size={16}/></button></ActionForm>}{["programs", "batches", "locations"].includes(kind) && w.capabilities["workflow.manage"].includes(String(r.organizationId)) && <Launch row={r} kind={kind} workspace={w}/>}</div></td></tr>)}</tbody></table></div>}</>;
}
function Editor({ kind, workspace: w, initial, close }: { kind: CompanyKind; workspace: Workspace; initial: Row | null; close: () => void }) {
  const [state, action, pending] = useActionState(saveAira, {});
  const options: Record<string, { id: string; name: string }[]> = { organizations: w.organizations.filter(o => w.capabilities[manageKeys[kind]!]?.includes(o.id) && (kind !== "programs" || ["DIVISION", "BUSINESS_UNIT"].includes(o.type)) && (kind !== "products" || o.id === w.company.id)), divisions: w.organizations.filter(o => ["DIVISION", "BUSINESS_UNIT"].includes(o.type)), teams: w.organizations.filter(o => o.type === "TEAM"), programs: w.programs, batches: w.batches, locations: w.locations, products: w.products, brands: w.brands, people: w.people.map(p => ({ id: p.id, name: p.displayName })), projects: w.projects, goals: w.goals.map(g => ({ id: g.id, name: g.title })) };
  return <section className="editor-band"><h3>{initial ? "Edit" : "New"} {companyLabels[kind]}</h3><form action={form => {
    const raw: Record<string, unknown> = {};
    // Preserve omitted shared execution relationships when editing in company context.
    if (initial && ["projects", "goals", "responsibilities"].includes(kind)) for (const k of ["brandId", "productId", "priority", "health", "progressMode", "parentGoalId", "startDate", "taskId", "milestoneId"]) if (initial[k] !== undefined) raw[k] = initial[k];
    for (const f of fields[kind] ?? []) {
      const v = String(form.get(f.key) ?? "");
      raw[f.key] = f.type === "number" ? v ? Number(v) : null : v || null;
    }
    if (initial?.metadata) { try { raw.metadata = JSON.parse(String(initial.metadata)); } catch { raw.metadata = null; } }
    form.set("payload", JSON.stringify(raw)); action(form);
  }} className="business-form"><input type="hidden" name="kind" value={kind}/><input type="hidden" name="recordId" value={initial?.id ?? ""}/>{(fields[kind] ?? []).map(f => <label key={f.key} className={f.type === "textarea" ? "wide-field" : ""}>{f.label}{f.source || f.values ? <select name={f.key} required={f.required} defaultValue={String(initial?.[f.key] ?? f.values?.[0] ?? "")} disabled={pending}><option value="">Select</option>{f.values?.map(v => <option key={v} value={v}>{v.replaceAll("_", " ")}</option>)}{(options[f.source ?? ""] ?? []).map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select> : f.type === "textarea" ? <textarea name={f.key} defaultValue={label(initial?.[f.key])} disabled={pending} maxLength={4000}/> : <input name={f.key} type={f.type ?? "text"} min={f.type === "number" ? 0 : undefined} step={f.type === "number" ? 1 : undefined} required={f.required} defaultValue={f.type === "date" ? String(initial?.[f.key] ?? "").slice(0,10) : initial?.[f.key] == null ? "" : String(initial[f.key])} disabled={pending} maxLength={f.key === "currency" ? 3 : 200}/> }</label>)}<div className="wide-field form-footer"><button className="button" disabled={pending}><Save size={16}/>{pending ? "Saving..." : "Save"}</button><button type="button" className="button secondary" onClick={close}><X size={16}/>Close</button></div>{state.error && <p className="wide-field error" role="alert">{state.error}</p>}{state.success && <p className="wide-field" role="status">{state.success}</p>}</form></section>;
}
function Launch({ row, kind, workspace: w }: { row: Row; kind: CompanyKind; workspace: Workspace }) {
  const [state, action, pending] = useActionState(saveAira, {});
  const [idempotencyKey] = useState(() => crypto.randomUUID());
  const definitions = w.workflows.filter(d => d.organizationId === row.organizationId);
  if (!definitions.length) return null;
  return <details><summary>Workflow</summary><form action={form => { form.set("kind", "launch"); form.set("payload", JSON.stringify({ resourceType: kind === "programs" ? "PROGRAM" : kind === "batches" ? "BATCH" : "LOCATION", resourceId: row.id, definitionId: form.get("definitionId"), title: label(row.name), idempotencyKey })); action(form); }}><label>Process<select name="definitionId" required>{definitions.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button className="icon-button" title="Start workflow" aria-label="Start workflow" disabled={pending}><Play size={16}/></button>{state.error && <p role="alert">{state.error}</p>}{state.success && <p role="status">{state.success}</p>}</form></details>;
}
