import Link from "next/link";
import { requireSession } from "@/server/auth/guards";
import { airaService } from "@/server/domain/aira-service";
export default async function AiraOverview() {
  const session = await requireSession(), data = await airaService.overview(session.userId), w = data.workspace;
  const divisions = w.organizations.filter(o => o.type === "DIVISION" || o.type === "BUSINESS_UNIT");
  const queues = [{ name: "Active programs", value: data.activePrograms.length, href: "/app/aira/programs?status=ACTIVE" }, { name: "Upcoming batches", value: data.upcoming.length, href: "/app/aira/batches" }, { name: "Registered locations", value: w.locations.length, href: "/app/aira/locations" }, { name: "Active projects", value: data.activeProjects.length, href: "/app/aira/projects?status=ACTIVE" }, { name: "My actionable approvals", value: data.pending.length, href: "/app/aira/approvals" }, { name: "Blocked projects", value: data.blocked.length, href: "/app/aira/projects?status=BLOCKED" }].filter(q => w.navigation.some(k => q.href.startsWith("/app/aira/" + k)));
  return <section><div className="view-heading"><h2>Operating Overview</h2></div><div className="operations-overview">{queues.map(q => <Link key={q.name} href={q.href}><span>{q.name}</span><strong>{q.value}</strong></Link>)}</div><section className="company-band"><h2>Divisions</h2>{divisions.length ? <ul className="company-divisions">{divisions.map(d => <li key={d.id}><Link href={`/app/aira/${d.name === "AIRA Labs" ? "products" : "programs"}?divisionId=${d.id}`}>{d.name}</Link></li>)}</ul> : <p className="muted">No divisions available.</p>}</section><section className="company-band"><h2>Upcoming</h2>{data.upcoming.length ? data.upcoming.map(b => <p key={String(b.id)}><Link href="/app/aira/batches">{String(b.name)}</Link> <time>{(b.startDate as Date).toISOString().slice(0,10)} UTC</time></p>) : <p className="muted">No dated upcoming batches.</p>}</section><section className="company-band"><h2>Needs Attention</h2>{!data.blocked.length && !data.atRisk.length && !data.pending.length ? <p className="muted">No attention items in your accessible company scope.</p> : <><p><Link href="/app/aira/projects?status=BLOCKED">Blocked projects: {data.blocked.length}</Link></p><p><Link href="/app/aira/goals?status=AT_RISK">At-risk or missed goals: {data.atRisk.length}</Link></p><p><Link href="/app/aira/approvals">Actionable approvals: {data.pending.length}</Link></p></>}</section><section className="company-band"><h2>Responsibility</h2>{data.responsibilities.length ? <ul>{data.responsibilities.map(r => <li key={String(r.id)}>{String(r.title)}: {String(r.name)}{r.teamName ? ` / ${r.teamName}` : ""}</li>)}</ul> : <p className="muted">No active responsibility assignments.</p>}</section></section>;
}
