"use client";
import Link from "next/link";
import { createContext, startTransition, useActionState, useContext, useEffect, useRef, useState, type ReactNode } from "react";
import { useSearchParams } from "next/navigation";
import { workspaceHref } from "@/lib/workspace-navigation";
import { withinOrganization } from "@/lib/work-list";
import { Status } from "@/components/ui/status";
import { Check, X, Plus, Play, Save, Mail, MailOpen, Archive, Pause, Bell, Pencil } from "lucide-react";
import { operationAction } from "./actions";
import type { operationsService } from "@/server/domain/operations-service";
import type { OperationsKind } from "@/server/domain/operations-input";
import { UserTime } from "@/components/ui/user-time";
type Workspace = Awaited<ReturnType<typeof operationsService.workspace>>;
export type Row = { id: string; [key: string]: unknown };
const FeedbackContext = createContext<((message: string) => void) | null>(null);
type Option = { id: string; name: string };
type Target = Option & { organizationId: string; projectId?: string | null; resourceType: string };
const label = (v: unknown) => typeof v === "string" || typeof v === "number" ? String(v).replaceAll("_", " ") : "";
const content = (v: unknown) => typeof v === "string" || typeof v === "number" ? String(v) : "";
const date = (v: unknown) => <UserTime value={typeof v === "string" ? v : null}/>;
const object = (v: unknown) => v && typeof v === "object" ? v as Record<string, unknown> : {};
const array = (v: unknown) => Array.isArray(v) ? v as Record<string, unknown>[] : [];
const names: Record<OperationsKind, string> = { "my-tasks": "My Tasks", approvals: "Approvals", requests: "Requests", notifications: "Notifications", activity: "Activity", workflows: "Workflows", instances: "Workflow Runs", events: "Operational Events", reminders: "Reminders", recurring: "Recurring Work", escalations: "Escalations", controls: "Control Points", preferences: "Notification Preferences", sia: "SIA Proposals" };
export function ActionForm({ operation, id, payload = {}, children, className = "operation-action" }: { operation: string; id?: string; payload?: unknown; children: ReactNode; className?: string }) {
  const feedback = useContext(FeedbackContext);
  const submitted = useRef(false);
  const [state, action, pending] = useActionState(async (previous: Parameters<typeof operationAction>[0], form: FormData) => {
    try {
      const result = await operationAction(previous, form);
      if (result.success) feedback?.(result.success);
      return result;
    } finally { submitted.current = false; }
  }, {});
  const [duplicate, setDuplicate] = useState(false);
  useEffect(() => { if (!pending) submitted.current = false; }, [pending, state]);
  return <form method="post" className={className} aria-busy={pending} onSubmit={event => {
    event.preventDefault();
    if (submitted.current || pending) { event.preventDefault(); setDuplicate(true); return; }
    const submitter = (event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null;
    const form = new FormData(event.currentTarget);
    if (submitter?.name) form.set(submitter.name, submitter.value);
    const status = form.get("status");
    if ((operation === "decision" || operation === "submit" || operation === "cancel" || ["ARCHIVED", "CANCELLED", "RESOLVED"].includes(String(status))) && !window.confirm(operation === "decision" ? `Confirm ${submitter?.value === "APPROVED" ? "approval" : "rejection"} of this request? This records your human decision; it does not authorize autonomous SIA execution.` : "Confirm this change?")) { event.preventDefault(); return; }
    submitted.current = true; setDuplicate(false); feedback?.("");
    // Dispatch explicitly so React does not reset controlled policy/resource selectors.
    startTransition(() => action(form));
  }}><input type="hidden" name="operation" value={operation}/><input type="hidden" name="recordId" value={id ?? ""}/><input type="hidden" name="payload" value={JSON.stringify(payload)}/><fieldset disabled={pending}>{children}</fieldset>{pending && <p role="status">Saving...</p>}{duplicate && <p role="status">Already submitting. Wait for the result before trying again.</p>}{state.error && <p role="alert" className="error">{state.error}</p>}{state.success && !feedback && <p role="status" className="muted">{state.success}</p>}</form>;
}
function Icon({ title, children, ...props }: { title: string; children: ReactNode; name?: string; value?: string }) { return <button className="icon-button" title={title} aria-label={title} {...props}>{children}</button>; }
function Select({ name, options, required = true, value, onChange }: { name: string; options: Option[]; required?: boolean; value?: string; onChange?: (value: string) => void }) { return <select name={name} required={required} value={value} onChange={onChange ? e => onChange(e.target.value) : undefined}><option value="">Select</option>{options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select>; }
const manageKeys: Partial<Record<OperationsKind, string>> = { workflows: "workflow.manage", instances: "workflow.transition", controls: "control.manage", requests: "request.manage", notifications: "notification.generate", reminders: "reminder.manage", recurring: "recurrence.manage", escalations: "escalation.manage", events: "event.manage", sia: "sia.propose" };
export function OperationsManager({ kind, rows, workspace: w, targets }: { kind: OperationsKind; rows: Row[]; workspace: Workspace; targets: Target[] }) {
  const query = useSearchParams();
  const companyId = query.get("companyId") ?? query.get("organizationId") ?? undefined;
  const href = (path: string) => workspaceHref(path, companyId, query.get("returnView") ?? undefined, new URLSearchParams(query.toString()));
  const [creating, setCreating] = useState(query.get("create") === "true");
  const [selectedApproval, setSelectedApproval] = useState(query.get("recordId") ?? "");
  const [editing, setEditing] = useState<Row | null>(null);
  const [feedback, setFeedback] = useState("");
  const key = manageKeys[kind];
  const canCreate = kind === "preferences" || !!key && !!w.scopes[key] && (w.scopes[key].organizations.length + w.scopes[key].projects.length > 0);
  const labels = new Map([...w.organizations, ...w.projects, ...w.users, ...w.definitions, ...w.policies, ...targets].map(o => [o.id, o.name]));
  const who = (id: unknown) => typeof id === "string" && id ? labels.get(id) ?? "Outside visible directory" : "Not assigned";
  return <FeedbackContext.Provider value={setFeedback}><div className="view-heading"><h1>{kind === "approvals" ? "Approval inbox" : names[kind]}</h1><div className="row-actions">{kind === "workflows" && <Link prefetch={false} className="button secondary" href={href("/app/operations/instances")}>Runs</Link>}{kind === "notifications" && <Link prefetch={false} className="button secondary" href={href("/app/operations/preferences")}>Preferences</Link>}{canCreate && <button className="button" onClick={() => setCreating(!creating)}><Plus size={16}/>{creating ? "Close" : "New"}</button>}</div></div>
    {feedback && <p role="status" className="operation-feedback">{feedback}</p>}
    {creating && canCreate && <Editor kind={kind} workspace={w} targets={targets} initial={{ id: "", organizationId: query.get("organizationId") ?? "", projectId: query.get("projectId") ?? "" }}/>}
    {editing && <><button className="button secondary" onClick={() => setEditing(null)}><X size={16}/>Close draft</button><Editor key={editing.id} kind="workflows" workspace={w} targets={targets} initial={editing}/></>}
    {kind === "approvals" ? <section className="approval-inbox" aria-label="Approval inbox"><div className="approval-list">{!rows.length && <p className="business-empty">No approvals match these filters in accessible records.</p>}{rows.map(r => <button type="button" className="approval-item" key={r.id} aria-pressed={(rows.some(row => row.id === selectedApproval) ? selectedApproval : rows[0]?.id) === r.id} onClick={() => setSelectedApproval(r.id)}><strong>{content(r.title)}</strong><Status value={String(r.status)}/><small>Requester: {who(r.requesterUserId)} / {who(r.organizationId)}</small><small>{label(r.nextStep)}</small><small>Requested: {date(r.createdAt)}</small></button>)}</div><div className="approval-detail">{(() => {
      const r = rows.find(r => r.id === selectedApproval) ?? rows[0];
      if (!r) return null;
      return <><h2>{content(r.title)}</h2><Status value={String(r.status)}/><dl className="record-details"><div><dt>Requester</dt><dd>{who(r.requesterUserId)}</dd></div><div><dt>Assigned approver</dt><dd>{who(r.approverUserId)}</dd></div><div><dt>Scope</dt><dd>{who(r.organizationId)} / {who(r.projectId)}</dd></div><div><dt>Approval policy</dt><dd>{label(r.policyName)}</dd></div><div><dt>Expires</dt><dd>{date(r.expiresAt)}</dd></div></dl><h3>Reason & supporting evidence</h3><p className="approval-reason">{content(r.description) || "No supporting reason was recorded. Seek clarification before deciding."}</p><p>Target: {label(r.resourceType)} / {who(r.resourceId)}</p>{r.communicationPreview != null && <CommunicationPreview value={r.communicationPreview}/>}{r.canOpenRequest === true && <Link prefetch={false} href={href(`/app/operations/requests?recordId=${encodeURIComponent(String(r.requestId))}&organizationId=${encodeURIComponent(String(r.organizationId))}`)}>Open supporting request</Link>}{r.workflowInstanceId != null && r.canOpenWorkflow === true && <p><Link prefetch={false} href={href(`/app/operations/instances?recordId=${encodeURIComponent(String(r.workflowInstanceId))}&organizationId=${encodeURIComponent(String(r.organizationId))}`)}>Open controlled workflow (version {String(r.instanceVersion)})</Link></p>}<h3>Decision history</h3><ol className="approval-history">{array(r.approvals).map(a => <li key={String(a.id)}><strong>Stage {Number(a.stageIndex) + 1} / {who(a.approverUserId)}</strong><Status value={String(a.status)}/><p>{content(a.comment) || "No decision comment recorded."}</p>{a.decidedAt != null && <small>{date(a.decidedAt)}</small>}</li>)}</ol><p role="status">{label(r.nextStep)}</p><RowActions kind={kind} row={r} workspace={w} onEdit={() => {}}/></>;
    })()}</div></section> : !rows.length ? <div className="business-empty"><Bell size={24}/><h2>No records match these filters</h2><p>Only currently accessible records are shown.</p></div> : <div className="table-scroll" role="region" aria-label={`${names[kind]} records`} tabIndex={0}><table className="business-table operations-table"><thead><tr><th>Work</th><th>Status</th><th>Scope &amp; Responsibility</th><th>Time</th><th>Actions</th></tr></thead><tbody>{rows.map(r => <tr key={r.id}>
      <td>{content(r.title ?? r.name ?? r.eventType ?? r.reason ?? r.type)}{r.message != null && <small>{content(r.message)}</small>}{r.description != null && <small>{content(r.description)}</small>}{r.entityType != null && <small>{label(r.entityType)}: {label(r.entityId)}</small>}{r.resourceType != null && <small>{label(r.resourceType)}: {who(r.resourceId)}</small>}{r.currentState != null && <small>{label(object(r.currentState).name)} · v{label(r.version)}</small>}{r.frequency != null && <small>Every {label(r.interval)} {label(r.frequency)} · {label(r.occurrences)}/{label(r.maxOccurrences)}</small>}{r.channel != null && <small>{label(r.channel)}</small>}{r.kind != null && <small>{label(r.kind)}{r.requiredPermission != null ? ` · ${label(r.requiredPermission)}` : ""}</small>}
        {kind === "workflows" && <details><summary>States &amp; transitions</summary>{array(r.states).map(s => <p key={label(s.id)}>{label(s.name)} {s.initial ? "(initial)" : ""} {s.terminal ? "(terminal)" : ""}</p>)}{array(r.transitions).map(t => <p key={label(t.id)}>{label(object(t.fromState).name)} → {label(object(t.toState).name)} · {label(t.requiredPermission)}</p>)}</details>}
        {array(r.approvals).length > 0 && <details><summary>Approval chain</summary>{array(r.approvals).map(a => <p key={label(a.id)}>Stage {Number(a.stageIndex) + 1}: {who(a.approverUserId)} · {label(a.status)}{a.comment ? ` · ${content(a.comment)}` : ""}</p>)}</details>}
        {r.communicationPreview != null && <CommunicationPreview value={r.communicationPreview} />}
        {array(r.history).length > 0 && <details><summary>History</summary>{array(r.history).map(h => <p key={label(h.id)}>{label(h.fromState)} → {label(h.toState)} · {who(h.actorUserId)} · {date(h.createdAt)}</p>)}</details>}
        {array(r.rules).length > 0 && <details><summary>Approval policy</summary>{array(r.rules).map(a => <p key={label(a.id)}>Stage {Number(a.stageIndex) + 1}: {who(a.approverUserId)} · {label(a.requiredPermission)}</p>)}</details>}
        {array(r.runs).length > 0 && <details><summary>Occurrences</summary>{array(r.runs).map(a => <p key={label(a.id)}>{date(a.scheduledAt)} · {label(a.status)} · {label(a.resultResourceId)}</p>)}</details>}
      </td><td><span className="status">{kind === "notifications" ? r.readAt ? "READ" : "UNREAD" : label(r.status ?? (r.enabled ? "ENABLED" : "DISABLED"))}</span>{r.priority != null && <small>{label(r.priority)}</small>}{r.failureCode != null && <small>{label(r.failureCode)}</small>}</td>
      <td>{who(r.organizationId)}<small>{who(r.projectId)}</small><small>{who(r.approverUserId ?? r.requesterUserId ?? r.actorUserId ?? r.recipientUserId ?? r.responsibleUserId ?? r.ownerUserId)}</small>{kind === "my-tasks" && <small>Assigned to you / {r.status === "BLOCKED" ? "Review blockers with the project owner" : "Review the task and permitted next actions"}</small>}{kind === "reminders" && <small>Recipient: {who(r.recipientUserId)} / {r.status === "PENDING" ? "Pending scheduled processing; cancel if no longer needed" : "Review recorded outcome"}</small>}{kind === "escalations" && <small>Owner: {who(r.responsibleUserId)} / Level {label(r.level)} / {r.status === "OPEN" ? "Review the reason and resolve after follow-up" : "Resolution recorded"}</small>}</td>
      <td>{date(r.remindAt ?? r.nextRunAt ?? r.dueDate ?? r.createdAt)}{r.expiresAt != null && <small>Expires {date(r.expiresAt)}</small>}</td>
      <td><RowActions kind={kind} row={r} workspace={w} onEdit={() => { setCreating(false); setEditing(r); }}/></td>
    </tr>)}</tbody></table></div>}</FeedbackContext.Provider>;
}
function CommunicationPreview({ value }: { value: unknown }) {
  const query = useSearchParams();
  const p = object(value);
  return <details open><summary>Communication Preview</summary><p>Recipient: {String(p.recipient)}<br />Channel: {String(p.channel)}<br />Sender: {String(p.sender)}<br />Purpose: {String(p.purpose)}<br />Risk: HIGH_RISK_WRITE<br />Approval required: Independent human</p><strong>{String(p.subject ?? "")}</strong><p style={{ whiteSpace: "pre-wrap" }}>{String(p.content)}</p><Link prefetch={false} href={workspaceHref(`/app/communications?view=messages&organizationId=${encodeURIComponent(String(p.organizationId))}`, query.get("companyId") ?? query.get("organizationId") ?? undefined, query.get("returnView") ?? undefined, new URLSearchParams(query.toString()))}>Open communication</Link></details>;
}
function RowActions({ kind, row: r, workspace: w, onEdit }: { kind: OperationsKind; row: Row; workspace: Workspace; onEdit: () => void }) {
  const query = useSearchParams(), companyId = query.get("companyId") ?? query.get("organizationId") ?? undefined;
  const href = (path: string) => workspaceHref(path, companyId, query.get("returnView") ?? undefined, new URLSearchParams(query.toString()));
  const allowed = (key: string) => !!w.scopes[key] && (w.scopes[key].organizations.includes(String(r.organizationId)) || w.scopes[key].projects.includes(String(r.projectId)));
  if (kind === "my-tasks") return <Link prefetch={false} href={href(`/app/execution/tasks?recordId=${encodeURIComponent(r.id)}&organizationId=${encodeURIComponent(String(r.organizationId))}`)}>Open task</Link>;
  if (kind === "notifications") return <ActionForm operation="read" id={r.id}><Icon title={r.readAt ? "Mark unread" : "Mark read"} name="read" value={r.readAt ? "false" : "true"}>{r.readAt ? <Mail size={16}/> : <MailOpen size={16}/>}</Icon></ActionForm>;
  if (kind === "approvals" && r.actionable && r.approverUserId === w.userId && allowed("approval.decide")) return <ActionForm operation="decision" id={r.id}><label>Decision comment<input name="reason" required maxLength={4000}/></label><div className="row-actions"><Icon title="Approve" name="decision" value="APPROVED"><Check size={16}/></Icon><Icon title="Reject" name="decision" value="REJECTED"><X size={16}/></Icon></div></ActionForm>;
  if ((kind === "requests" || kind === "sia") && allowed("request.manage")) return <>{r.status === "DRAFT" && r.requesterUserId === w.userId && <><ActionForm operation="submit" id={r.id}><button className="button secondary"><Play size={14}/>Submit</button></ActionForm><details><summary>Edit</summary><ActionForm operation="update" id={r.id}><label>Title<input name="title" defaultValue={content(r.title)} required/></label><label>Description<textarea name="description" defaultValue={content(r.description)}/></label><Icon title="Save"><Save size={16}/></Icon></ActionForm></details></>}{["DRAFT", "SUBMITTED"].includes(String(r.status)) && <ActionForm operation="cancel" id={r.id}><Icon title="Cancel request"><X size={16}/></Icon></ActionForm>}</>;
  if (kind === "workflows" && allowed("workflow.manage")) return <>{r.status === "DRAFT" && <><ActionForm operation="publish" id={r.id}><button className="button secondary"><Play size={14}/>Publish</button></ActionForm><button className="button secondary" onClick={onEdit}><Pencil size={14}/>Edit draft</button></>}{r.status !== "ARCHIVED" && <StatusForm kind="workflow" id={r.id} status="ARCHIVED"/>}</>;
  if (kind === "instances" && r.status === "PENDING" && allowed("workflow.transition")) return <>{array(object(r.definition).transitions).filter(t => t.fromStateId === r.currentStateId).map(t => <div key={label(t.id)}><ActionForm operation="transition" payload={{ instanceId: r.id, transitionId: t.id, expectedVersion: r.version, idempotencyKey: `transition-${r.id}-${r.version}-${t.id}` }}><label>Reason<input name="reason" required={!!t.requireReason} maxLength={4000}/></label><button className="button secondary"><Play size={14}/>{label(t.key)}</button></ActionForm>{t.controlPointId != null && allowed("control.evaluate") && <details><summary>Verification</summary><ActionForm operation="verify" id={r.id}><input type="hidden" name="controlPointId" value={label(t.controlPointId)}/><label>Verification reason<input name="reason" required/></label><Icon title="Pass verification" name="passed" value="true"><Check size={16}/></Icon><Icon title="Fail verification" name="passed" value="false"><X size={16}/></Icon></ActionForm></details>}</div>)}</>;
  if (kind === "reminders" && r.status === "PENDING" && allowed("reminder.manage")) return <StatusForm kind="reminder" id={r.id} status="CANCELLED"/>;
  if (kind === "recurring" && allowed("recurrence.manage") && !["COMPLETED", "CANCELLED"].includes(String(r.status))) return <><StatusForm kind="recurrence" id={r.id} status={r.status === "ACTIVE" ? "PAUSED" : "ACTIVE"}/><StatusForm kind="recurrence" id={r.id} status="CANCELLED"/></>;
  if (kind === "escalations" && r.status === "OPEN" && allowed("escalation.manage")) return <StatusForm kind="escalation" id={r.id} status="RESOLVED"/>;
  if (kind === "controls" && r.status === "ACTIVE" && allowed("control.manage")) return <StatusForm kind="control" id={r.id} status="ARCHIVED"/>;
  return null;
}
function StatusForm({ kind, id, status }: { kind: string; id: string; status: string }) { return <ActionForm operation="status" id={id}><input type="hidden" name="kind" value={kind}/><input type="hidden" name="status" value={status}/><Icon title={status === "PAUSED" ? "Pause" : status === "ACTIVE" ? "Resume" : status === "RESOLVED" ? "Resolve" : status === "ARCHIVED" ? "Archive" : "Cancel"}>{status === "PAUSED" ? <Pause size={16}/> : status === "ACTIVE" ? <Play size={16}/> : status === "RESOLVED" ? <Check size={16}/> : <Archive size={16}/>}</Icon></ActionForm>; }
function Editor({ kind, workspace: w, targets, initial }: { kind: OperationsKind; workspace: Workspace; targets: Target[]; initial?: Row }) {
  const manage = w.scopes[manageKeys[kind] ?? ""];
  const query = useSearchParams();
  const contextId = query.get("organizationId");
  const eligibleTargets = targets.filter(t => (!contextId || withinOrganization(t.organizationId, contextId, w.organizations)) && !!manage && (manage.organizations.includes(t.organizationId) || !!t.projectId && manage.projects.includes(t.projectId)));
  const preferredTarget = eligibleTargets.find(t => t.id === query.get("targetId")) ?? eligibleTargets.find(t => t.resourceType === "ORGANIZATION" && t.id === initial?.organizationId);
  const [values, setValues] = useState<Record<string, string>>({ version: initial?.id ? String(initial.version) : "1", organizationId: String(initial?.organizationId ?? ""), projectId: String(initial?.projectId ?? ""), target: preferredTarget?.id ?? "", name: String(initial?.name ?? ""), requiredPermission: "approval.decide", kind: kind === "recurring" ? "TASK" : "APPROVAL", frequency: "WEEKLY", interval: "1", maxOccurrences: "12", level: "1", type: "ALL", channel: "IN_APP", enabled: "true", key: String(initial?.key ?? ""), title: "" });
  const [requestKey] = useState(() => crypto.randomUUID());
  const [states, setStates] = useState(initial?.id ? array(initial.states).map(s => ({ key: String(s.key), name: String(s.name), initial: !!s.initial, terminal: !!s.terminal })) : [{ key: "DRAFT", name: "Draft", initial: true, terminal: false }, { key: "COMPLETED", name: "Completed", initial: false, terminal: true }]);
  const [transitions, setTransitions] = useState(initial?.id ? array(initial.transitions).map(t => ({ key: String(t.key), from: String(object(t.fromState).key), to: String(object(t.toState).key), requiredPermission: String(t.requiredPermission), requireReason: !!t.requireReason, controlPointId: String(t.controlPointId ?? "") })) : [{ key: "COMPLETE", from: "DRAFT", to: "COMPLETED", requiredPermission: "workflow.transition", requireReason: false, controlPointId: "" }]);
  const [rules, setRules] = useState([{ stage: 1, approverUserId: "", requiredPermission: "approval.decide" }]);
  const set = (key: string, value: string) => setValues(v => ({ ...v, [key]: value }));
  const field = (key: string, name: string, options?: Option[], type = "text", required = true) => <label key={key}>{name}{options ? <Select name={key} options={options} value={values[key] ?? ""} onChange={v => set(key, v)} required={required}/> : <input name={key} type={type} value={values[key] ?? ""} onChange={e => set(key, e.target.value)} required={required} maxLength={type === "text" ? 4000 : undefined}/>}</label>;
  const opts = (items: string[]) => items.map(id => ({ id, name: id.replaceAll("_", " ") }));
  const target = targets.find(t => t.id === values.target);
  const scopedPolicies = w.policies.filter(p => p.organizationId === (target?.organizationId ?? values.organizationId) && (p.projectId ?? "") === (target?.projectId ?? values.projectId ?? ""));
  const scopedDefinitions = w.definitions.filter(p => p.organizationId === target?.organizationId && (p.projectId ?? "") === (target?.projectId ?? ""));
  const resource = target ? { organizationId: target.organizationId, projectId: target.projectId ?? null, resourceType: target.resourceType, resourceId: target.id } : {};
  const scope = { organizationId: values.organizationId, projectId: values.projectId || null };
  const utc = (key: string) => values[key] ? new Date(values[key] + "Z").toISOString() : null;
  let payload: Record<string, unknown> = { ...values, ...resource, idempotencyKey: requestKey, reference: requestKey };
  const operations: Partial<Record<OperationsKind, string>> = { workflows: "workflow", controls: "control", instances: "instance", requests: "request", notifications: "notice", reminders: "reminder", recurring: "recurring", escalations: "escalation", events: "event", preferences: "preference", sia: "proposal" };
  if (kind === "controls") payload = { ...values, ...scope, allowSelfApproval: values.allowSelfApproval === "true", stages: ["APPROVAL", "HUMAN_DECISION"].includes(values.kind) ? [...new Set(rules.map(r => r.stage))].sort((a,b) => a-b).map(stage => rules.filter(r => r.stage === stage).map(({ approverUserId, requiredPermission }) => ({ approverUserId, requiredPermission }))) : [] };
  if (kind === "workflows") payload = { ...values, ...scope, version: Number(values.version), states, transitions: transitions.map(t => ({ ...t, controlPointId: t.controlPointId || null })) };
  if (kind === "requests" || kind === "sia") payload = { ...payload, expiresAt: utc("expiresAt"), workflowInstanceId: values.workflowInstanceId || null };
  if (kind === "reminders") payload = { ...payload, remindAt: utc("remindAt") };
  if (kind === "recurring") payload = { ...payload, interval: Number(values.interval), maxOccurrences: Number(values.maxOccurrences), timezone: "UTC", startAt: utc("startAt"), until: utc("until"), definitionId: values.kind === "WORKFLOW" ? values.definitionId : null, template: values.kind === "TASK" ? { title: values.taskTitle, assigneePersonId: values.assigneePersonId || null, priority: "NORMAL" } : null };
  if (kind === "escalations") payload = { ...payload, level: Number(values.level) };
  if (kind === "events") payload = { ...payload, eventType: values.eventType };
  if (kind === "preferences") payload = { ...payload, enabled: values.enabled === "true" };
  return <section className="editor-band"><ActionForm operation={operations[kind] ?? ""} id={initial?.id} payload={payload} className="operation-editor"><div className="business-form">
    {["controls", "workflows"].includes(kind) ? <>{field("organizationId", "Organization", w.organizations.filter(o => manage?.organizations.includes(o.id)))}{field("projectId", "Project", w.projects.filter(p => p.organizationId === values.organizationId && (manage?.organizations.includes(p.organizationId) || manage?.projects.includes(p.id))), "text", false)}{field("name", "Name")}</> : kind !== "preferences" && field("target", "Resource", eligibleTargets.filter(t => kind !== "recurring" || ["PROJECT", "ORGANIZATION"].includes(t.resourceType)))}
    {["instances", "requests", "recurring", "sia"].includes(kind) && field("title", "Title")}
    {kind === "controls" && <>{field("kind", "Control type", opts(["APPROVAL", "VALIDATION", "CONFIRMATION", "VERIFICATION", "HUMAN_DECISION"]))}{field("requiredPermission", "Required capability", w.permissions)}<label>Allow self approval<input type="checkbox" checked={values.allowSelfApproval === "true"} onChange={e => set("allowSelfApproval", String(e.target.checked))}/></label>{["APPROVAL", "HUMAN_DECISION"].includes(values.kind) && <div className="wide-field"><h2>Approval stages</h2>{rules.map((r,i) => <div className="operation-rule" key={i}><label>Stage<input type="number" min={1} max={10} value={r.stage} onChange={e => setRules(v => v.map((a,j) => j === i ? { ...a, stage: Number(e.target.value) } : a))}/></label><label>Approver<Select name={`approver-${i}`} options={w.users} value={r.approverUserId} onChange={v => setRules(a => a.map((b,j) => j === i ? { ...b, approverUserId: v } : b))}/></label><label>Capability<Select name={`cap-${i}`} options={w.permissions} value={r.requiredPermission} onChange={v => setRules(a => a.map((b,j) => j === i ? { ...b, requiredPermission: v } : b))}/></label><button type="button" className="icon-button" title="Remove approver" onClick={() => setRules(v => v.filter((_,j) => j !== i))}><X size={16}/></button></div>)}<button type="button" className="button secondary" onClick={() => setRules(v => [...v, { stage: v.length + 1, approverUserId: "", requiredPermission: "approval.decide" }])}><Plus size={16}/>Approver</button></div>}</>}
    {kind === "workflows" && <>{field("key", "Process key")}{field("version", "Version", undefined, "number")}<div className="wide-field"><h2>States</h2>{states.map((s,i) => <div className="operation-rule" key={i}><label>Key<input required value={s.key} onChange={e => setStates(v => v.map((a,j) => j === i ? { ...a, key: e.target.value.toUpperCase() } : a))}/></label><label>Name<input required value={s.name} onChange={e => setStates(v => v.map((a,j) => j === i ? { ...a, name: e.target.value } : a))}/></label><label>Initial<input type="radio" name="initial-state" checked={s.initial} onChange={() => setStates(v => v.map((a,j) => ({ ...a, initial: j === i })))}/></label><label>Terminal<input type="checkbox" checked={s.terminal} onChange={e => setStates(v => v.map((a,j) => j === i ? { ...a, terminal: e.target.checked } : a))}/></label><button type="button" className="icon-button" title="Remove state" onClick={() => setStates(v => v.filter((_,j) => j !== i))}><X size={16}/></button></div>)}<button type="button" className="button secondary" onClick={() => setStates(v => [...v, { key: "", name: "", initial: false, terminal: false }])}><Plus size={16}/>State</button><h2>Transitions</h2>{transitions.map((t,i) => <div className="operation-rule" key={i}><label>Key<input required value={t.key} onChange={e => setTransitions(v => v.map((a,j) => j === i ? { ...a, key: e.target.value.toUpperCase() } : a))}/></label>{(["from", "to", "requiredPermission", "controlPointId"] as const).map(k => <label key={k}>{k === "requiredPermission" ? "Capability" : k === "controlPointId" ? "Control point" : k === "from" ? "From" : "To"}<Select name={`${k}-${i}`} required={k !== "controlPointId"} options={k === "requiredPermission" ? w.permissions : k === "controlPointId" ? scopedPolicies : states.map(s => ({ id: s.key, name: s.name }))} value={t[k]} onChange={value => setTransitions(v => v.map((a,j) => j === i ? { ...a, [k]: value } : a))}/></label>)}<label>Reason required<input type="checkbox" checked={t.requireReason} onChange={e => setTransitions(v => v.map((a,j) => j === i ? { ...a, requireReason: e.target.checked } : a))}/></label><button type="button" className="icon-button" title="Remove transition" onClick={() => setTransitions(v => v.filter((_,j) => j !== i))}><X size={16}/></button></div>)}<button type="button" className="button secondary" onClick={() => setTransitions(v => [...v, { key: "", from: "", to: "", requiredPermission: "workflow.transition", requireReason: false, controlPointId: "" }])}><Plus size={16}/>Transition</button></div></>}
    {kind === "instances" && field("definitionId", "Workflow", scopedDefinitions)}
    {(kind === "requests" || kind === "sia") && <>{field("controlPointId", "Approval policy", scopedPolicies.filter(p => ["APPROVAL", "HUMAN_DECISION"].includes(p.kind)))}{field("workflowInstanceId", "Workflow run", targets.filter(t => t.resourceType === "INSTANCE"), "text", false)}{field("description", "Description", undefined, "text", false)}{field("expiresAt", "Expiry (UTC)", undefined, "datetime-local", false)}</>}
    {kind === "sia" && <>{field("siaId", "SIA identity", w.identities)}{field("toolKey", "Proposed action", [{ id: "organization.read", name: "Read organization" }, { id: "recommendation.create", name: "Prepare recommendation" }])}</>}
    {["notifications", "reminders"].includes(kind) && field("recipientUserId", "Recipient", w.users)}
    {["notifications", "reminders", "escalations"].includes(kind) && field("reason", "Reason")}
    {kind === "reminders" && field("remindAt", "Reminder time (UTC)", undefined, "datetime-local")}
    {kind === "recurring" && <>{field("kind", "Work type", opts(["TASK", "WORKFLOW"]))}{values.kind === "TASK" ? <>{field("taskTitle", "Task title")}{field("assigneePersonId", "Assignee", w.people, "text", false)}</> : field("definitionId", "Workflow", scopedDefinitions)}{field("frequency", "Frequency", opts(["DAILY", "WEEKLY", "MONTHLY"]))}{field("interval", "Interval", undefined, "number")}{field("startAt", "Start (UTC)", undefined, "datetime-local")}{field("until", "End (UTC)", undefined, "datetime-local", false)}{field("maxOccurrences", "Maximum occurrences", undefined, "number")}</>}
    {kind === "escalations" && <>{field("responsibleUserId", "Responsible person", w.users)}{field("trigger", "Trigger", opts(["PENDING_APPROVAL", "OVERDUE_TASK", "BLOCKED_PROJECT", "AT_RISK_GOAL", "REQUIRED_ACTION"]))}{field("level", "Level", undefined, "number")}</>}
    {kind === "events" && <>{field("eventType", "Event type")}{field("status", "Result", opts(["PENDING", "PROCESSING", "SUCCEEDED", "FAILED", "CANCELLED", "EXPIRED"]))}{field("correlationId", "Correlation reference", undefined, "text", false)}</>}
    {kind === "preferences" && <>{field("type", "Notification type", opts(["ALL", "TASK_ASSIGNED", "APPROVAL_REQUIRED", "APPROVAL_COMPLETED", "DEADLINE_APPROACHING", "TASK_OVERDUE", "PROJECT_BLOCKED", "GOAL_AT_RISK", "SYSTEM_EVENT", "REMINDER", "ESCALATION"]))}{field("channel", "Channel", opts(["IN_APP", "EMAIL", "WHATSAPP", "SMS", "PUSH"]))}<label>Enabled<input type="checkbox" checked={values.enabled === "true"} onChange={e => set("enabled", String(e.target.checked))}/></label></>}
    <div className="form-footer wide-field"><button className="button"><Save size={16}/>Save</button></div>
  </div></ActionForm></section>;
}
